---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: RNA Quantification - C.gigas RNA Lifestage Carryover from 20240615 and 20240617
date: '2024-06-17'
draft: false
engine: knitr
categories: 
  - "2024"
  - "project-gigas-carryover"
  - "Crassostrea gigas"
  - "Pacific oyster"
  - "seed"
  - "adult"
  - "juvenile"
  - "Qubit"
  - "RNA HS assay"
---
# INTRO

I was [asked to isolate RNA from a list of samples](https://github.com/RobertsLab/resources/issues/1891) (GitHub Issue) from a number of [_Crassostrea gigas_ (Pacific oyster)](http://en.wikipedia.org/wiki/Pacific_oyster) spat, seed, and adults that had been collected as part of the [`project-gigas-carryover`](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover) (GitHub repo). The full list of all samples needing processing is here:

- [`20240508_rna_extractions.csv`](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/sampling_metadata/20240508_rna_extractions.csv)

I previously isolated RNA on [20240615](../2024-06-15-RNA-Isolation---C.gigas-Lifestage-Carryover-Seed-Juvenile-Adult/index.qmd) (Notebook) and [20240617](../2024-06-17-RNA-Isolation---C.gigas-Lifestage-Carryover-Seed-Juvenile-and-Adult/index.qmd) and needed to quantify them.

# RNA Quantification
RNA was quantified with the Roberts Lab Qubit 3.0 fluorometer (Invitrogen). Samples were quantified with the Qubit RNA High Sensitivity (HS) assay (Invitrogen). 1uL of sample was used for the assay(s).

# RESULTS

Raw Qubit data is here:

- [`20240617-cgig-qubit-RNA.hs-carryover.csv`](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/qubit/20240617-cgig-qubit-RNA.hs-carryover.csv) (GitHub)



| sample_ID | Original sample conc. (ng/uL) |
|-----------|-------------------------------|
| 201       | 142                           |
| 202       | 142                           |
| 203       | 128                           |
| 204       | 142                           |
| 205       | 81.2                          |
| 207       | 186                           |
| 208       | 122                           |
| 209       | 132                           |
| 213       | 4.8                           |
| 214       | 65.2                          |
| 216       | 91                            |
| 219       | 25.2                          |
| 227       | 4.8                           |
| 229       | 54                            |
| 230       | 60                            |
| 231       | 18.5                          |

# SUMMARY

All samples yielded RNA.
