---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Samples Submitted - Cod RNA-seq Liver Replacements for Blood Samples
date: '2024-01-08'
draft: true
engine: knitr
categories: 
  - Samples Submitted
  - 2024
  - Pacific cod
  - RNA-seq
  - Gadus macrocephalus
  - 30-943133806
---
[We previously sent samples](https://robertslab.github.io/sams-notebook/posts/2023/2023-12-18-Samples-Submitted---Gadus-macrocephalus-liver-tissues-to-Azenta-for-RNA-seq/) to Azenta as part of this project, which included four blood samples. We were informed that since blood is processed differently (and we hadn't actually listed this tissue type on our initial quote), we'd have to pay more for sequencing. As such, we opted to replace those four with more liver tissue samples. Additionally, this gave us the opportunity to [replace sample 90, which had been accidentally duplicated](https://github.com/RobertsLab/resources/issues/1764#issuecomment-1877332382) (GitHub Issue).

Updated sample sheet:

| Sample # | General Information |                     |                     |                | Amount of Material |   |   |
|----------|---------------------|---------------------|---------------------|----------------|--------------------|---|---|
|          | Sample Name*        | Sample Type*        | Species/Strain*     | Sample Buffer* | Total Amount*      |   |   |
| 1        | 1                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 2        | 2                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 3        | 3                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 4        | 4                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 5        | 5                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 6        | 10                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 7        | 11                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 8        | 12                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 9        | 13                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 10       | 18                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 11       | 19                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 12       | 20                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 13       | 21                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 14       | 28                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 15       | 29                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 16       | 30                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 17       | 31                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 18       | 37                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 19       | 38                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 20       | 39                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 21       | 40                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 22       | 41                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 23       | 47                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 24       | 48                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 25       | 49                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 26       | 50                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 27       | 57                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 28       | 58                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 29       | 59                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 30       | 60                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 31       | 67                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 32       | 68                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 33       | 69                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 34       | 70                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 35       | 78                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 36       | 79                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 37       | 80                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 38       | 83                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 39       | 88                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 40       | 90                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 41       | 94                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 42       | 91                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 43       | 92                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 44       | 97                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 45       | 98                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 46       | 99                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 47       | 100                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 48       | 107                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 49       | 108                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 50       | 109                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 51       | 110                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 52       | 117                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 53       | 118                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 54       | 119                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 55       | 120                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 56       | 121                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 57       | 127                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 58       | 128                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 59       | 129                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 60       | 131                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 61       | 137                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 62       | 138                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 63       | 139                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 64       | 140                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 65       | 147                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 66       | 148                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 67       | 149                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 68       | 150                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 69       | 36                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 70       | 76                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 71       | 116                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 72       | 156                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 73       | 19-G                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 74       | 20-G                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 75       | 57-G                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 76       | 58-G                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 77       | 19-S                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 78       | 20-S                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 79       | 57-S                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |
| 80       | 58-S                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               |   |   |