---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: qPCRs - C.gigas Lifestage Carryover cDNA
date: '2024-03-25'
draft: true
engine: knitr
categories: 
  - qPCR
  - SsoFast
  - CFX Connect
  - HSP70
  - HSP90
  - GAPDH
  - VIPERIN
  - ATPsynthase
  - cGAS
  - DMNT1
  - citrate synthase
  - Crassostrea gigas
  - Pacific oyster
  - cDNA
---
# INTRO

Ran qPCRs on the cDNA I made [last week](../2024-03-19-Reverse-Transcription---C.gigas-Lifestage-Carryover-Seed-and-Spat/) (Notebook), as part of the [`project-gigas-carryover`](../../../../project-gigas-carryover/lifestage_carryover/) (GitHub Repo). The following primer sets were selected, based on previous usage in other stress (heat) experiments:

| SR ID | Primer Name          |
|-------|----------------------|
| 1385  | Cg_ATPsynthase_F     |
| 1386  | Cg_ATPsynthase_R     |
| 1383  | Cg_citratesynthase_F |
| 1384  | Cg_citratesynthase_R |
| 1172  | Cg_GAPDH_205_F       |
| 1173  | Cg_GAPDH_355_R       |
| 599   | Cg_HSP70_F           |
| 598   | Cg_HSP70_R           |
| 1532  | Cg_Hsp90_F           |
| 1533  | Cg_Hsp90_R           |
| 1829  | Cg_VIPERIN_F         |
| 1828  | Cg_VIPERIN_R         |
| 1825  | Cg_cGAS_F            |
| 1824  | CG_cGAS_R            |

# MATERIALS & METHODS

All samples were run in duplicate, on low-profile, white 96-well plates (USA Scientific) in a CFX Connect (BioRad) real-time thermalcycler. All reactions consisted of the following:

| Component                                          | Stock Concentration | Volume (uL) |
|----------------------------------------------------|---------------------|-------------|
| cDNA                                               | NA                  | 1           |
| SsoAdvanced Universal SYBR Green Supermix (BioRad) | 2x                  | 10          |
| P<sub>F</sub>                                      | 10uM                | 0.5         |
| P<sub>R</sub>                                      | 10uM                | 0.5         |
| H<sub>2</sub>O                                     | NA                  | 8           |
| TOTAL                                              |                     | 20          |

For cycling parameters, plate layouts, etc. see the [RESULTS](#results) section below.

Baseline threshold analysis was set to "Target" ("Fluorophore" is the default) in the CFX Maestro (BioRad) software for each plate.

# RESULTS