---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
date: 2016-02-05 04:48:50+00:00
layout: post
slug: data-management-high-throughput-sequencing-data
title: Data Management - High-throughput Sequencing Data
categories:
  - 2016
  - fusion table
  - nightingales
  - owl
---

We've had a recent influx of sequencing data, which is great, but it created a bit of a backlog documenting what we've received.

I updated our Google Sheet (Nightingales) with the data from [geoduck genome sequencing data from BGI](../2016-01-28-data-received-panopea-generosa-genome-sequencing-files-from-bgi/index.qmd), [Olympia oyster genome sequencing data from BGI](../2016-01-28-data-received-ostrea-lurida-genome-sequencing-files-from-bgi/index.qmd), and [MBD bisulfite sequencing data from ZymoResearch](../2016-02-03-data-received-ostrea-lurida-mbd-enriched-bs-seq/index.qmd).

I also fixed the "FileLocation" column by replacing the "HYPERLINK" function with "CONCATENATE".

Google Sheet: [Nightingales](https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/pubhtml)





After updating the Nightingales Google Sheet, I updated the corresponding Google Fusion Table (also called Nightingales).

To update the Fusion Table, you have to do the following:




    
  * delete all rows in the Nightingales Google Fusion Table (Edit > Delete all rows)

    
  * Import data from the Nightingales Google Spreadsheet (File > Import more rows...)



Fusion Table: ( Fustion tables discontinued in 2019)



At initial glance, the Fusion Table appears the same as the Google Sheet. However, if you follow the link to the full Fusion Table, it offers some unique ways to visually explore the data contained in the Fusion Table.



After that I decided to deal with the fact that many of the directories on Owl (https://owl.fish.washington.edu/nightingales/) lack readme files and subsequent information about the sequencing files in those folders.

So, I took an inordinate amount of time to write a script that would automate as much of the process as I could think of.


The goal of the script is to perform the following:





  * Identify folders that do not have readme files.



  * Identify folders that do not have checksum files.



  * Create readme files in those directories lacking readme files



  * Append the directory path to each new readme file



  * Append sequencing file names and corresponding read counts to the new readme files






Will run the script. Hope it works...
