---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: RNA Isolation - C.gigas Lifestage Carryover Samples Using Direct-zol RNA MiniPrep Plus Kit
date: '2025-05-13'
draft: false
engine: knitr
categories: 
  - "2025"
  - "Crassostrea gigas"
  - "Pacific oyster"
  - "RNA isolation"
  - "Direct-zol RNA MiniPrep Plus Kit"
  - "Magallana gigas"
---
# INTRO

I was [asked to isolate RNA from a list of 60 samples](https://github.com/RobertsLab/resources/issues/2062) (GitHub Issue) from a number of [_Crassostrea gigas_ (Pacific oyster)](http://en.wikipedia.org/wiki/Pacific_oyster) spat and seed that had been collected as part of the [`project-gigas-carryover`](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover) (GitHub repo). Yesterday, I [homogenized samples in TriZol](../2025-05-12-Sample-Homogenization---C.gigas-Lifestage-Carryover-Samples-Using-TriZol-and-Bullet-Blender/index.qmd) and stored them at -20<sup>o</sup>C. RNA from the other samples listed in this project [were isolated yesterday immediately after homogenization](../2025-05-12-Sample-Homogenization---C.gigas-Lifestage-Carryover-Samples-Using-TriZol-and-Bullet-Blender/index.qmd) (Notebook entry).

Here's the list of samples I isolated RNA from today:

`78`
`79`
`81`
`83`
`86`
`88`
`89`
`92`
`93`
`96`
`97`
`98`

## RNA Isolation
RNA isolations were conducted using the Direct-zol RNA MiniPrep Plus Kit (Zymo Research) according to the manufacturer's protocol, including the optional DNase treatment step. All samples were eluted with 50 µL of nuclease-free water.

## Sample Storage
Samples were stored on ice in preparation for [quantification](../2025-05-13-RNA-Quantification---C.gigas-Lifestage-Carryover-RNA-Samples-Using-Qubit-High-Sensitivity-RNA-Assay/index.qmd) (Notebook entry).

