---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: RNA Isolation - C.gigas PolyIC Mechanical Trials for Valentina Using Quick-DNA RNA Miniprep Plus Kit
date: '2025-09-02'
draft: false
engine: knitr
categories: 
  - "2025"
  - "PolyIC"
  - "RNA Isolation"
  - "Qubit"
  - "Magallana gigas"
  - "Pacific oyster"
  - "Quick DNA/RNA Miniprep Plus Kit"
---
# INTRO

Continued RNA isolation for this project, which was [initially started on 20250804.](../2025-08-04-RNA-Isolation-and-Quantification---C.gigas-PolyIC-Mechanical-Trials-for-Valentina-Using-Quick-DNA-RNA-MiniPrep-Plus-Kit/index.qmd)

I isolated RNA from the remaining 100 tissue samples. See [RNA quantification on 20250910](../2025-09-10-RNA-Quantification---C.gigas-PolyIC-Mechanical-Trials-RNA-from-20250902/index.qmd) for the full list of samples.

# MATERIALS & METHODS

Whole body tissue had been snap frozen and stored at -80<sup>o</sup>C.


## Homogenization

300uL of DNA/RNA Shield (ZymoResearch) were added to the frozen tissue. Samples and DNA/RNA Shield were transferred to 1.5mL SafeLock (Eppendorf) microcentrifuge tubes containing ~50uL of 0.5mm zirconium oxide beads and ~50uL of 0.15mm zirconium oxide beads. Samples were homogenized using the Roberts Lab Bullet Blender 5E Gold + (NextAdvance) with 1.5mL tube adapters for 3mins at speed 12. The Bullet Blender was pre-cooled, and cooled, using dry ice.

## RNA Isolation

RNA was isolated using the Quick-DNA/RNA MiniPrep Plus Kit, according to the manufacturer's protocol with the following changes/notes:

:::: {.callout-note}
- Treated with optional DNase step.

- Eluted with 50uL of H<sub>2</sub>O.
:::

Samples were stored in Valentina's original boxes in the middle -80<sup>o</sup>C for quantification at a later date.

::: {.callout-important}
The following seven samples yielded no RNA [when they were quantified on 20250910](../2025-09-10-RNA-Quantification---C.gigas-PolyIC-Mechanical-Trials-RNA-from-20250902/index.qmd) and their tubes were discarded:

- `C4PC`
- `C5PC`
- `C1PM`
- `C2PM`
- `C3PM`
- `C4PM`
- `C5PM`

:::