---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: DNA Isolation Quantification and Concentration - S.namaycush Siscowet Liver Samples Using Zymo Quick-DNA RNA MiniPrep Plus Kit
date: '2025-07-08'
draft: false
engine: knitr
categories: 
  - "2025"
  - "Salvelinus namaycush"
  - "Lake trout"
  - "siscowet"
  - "DNA isolation"
  - "DNA quantification"
  - "Qubit"
---

::: {.callout-important}
These samples were shipped to Angie Schmoldt at Univ. of Wisconsin-Milwaukee on 20250714.
:::

# INTRO

Steven asked that I [isolate gDNA from more Siscowet lake trout (_S.namaycush_) liver samples](https://github.com/RobertsLab/resources/issues/2217) (GitHub Issue) to send to Angie for sequencing - part of Rick's project. 

# METHODS

DNA was isolated using the Quick-DNA/RNA Miniprep Plus Kit (ZymoResearch), according to the manufacturer's protocol. Liver tissues had been stored @ -20<sup>o</sup>C in RNALater (Ambion). I thawed the tubes, transferred the entire liver tissue (which was very small) to a disposable mortar/pestle combo (1.5mL tube) and homogenized in 1x DNA/RNA Shield. Insoluble material was pelleted and the remainder of the protocol was followed (note: I did _not_ perform Proteinase K lysis). DNA was eventually eluted with 50uL of water.

Subsequently, DNA was quantified using the dsDNA Broad Range Qubit Assay (ThermoFisher). One microliter of sample was combined with 199uL of the dye/buffer mix and measured on a Qubit 3.0.

All samples were subjected to concentrating using a SpeedVac on the "High Drying Rate" setting for ~1hr, as Angie needs highly concentrated DNA for sequencing, with a targeted final volume of ~10uL.

DNA was stored in a box labelled "Lake Trout Liver gDNA" in the FTR 209 -20<sup>o</sup>C freezer.


# RESULTS

## Qubit data

- [20250708-snam-qubit-DNA.br-liver](https://docs.google.com/spreadsheets/d/1O5Ic79ugw0NnnWsVgZchF5aTQ3DQ9PsCiCAFYnIJKJU/edit?usp=sharing) (Google Sheet)


| sample_ID | Concentration (ng/uL) | Volume (uL) | Yield (ng) |
|-----------|-----------------------|-------------|------------|
| FA 244    | 29                    | 40          | 1160       |
| FA 245    | 270                   | 40          | 10800      |
| FA 251    | 104                   | 40          | 4160       |
| FA 252    | 183                   | 40          | 7320       |
| FA 253    | 195                   | 40          | 7800       |

::: {.callout-note}
This table details sample info _before_ concentrating. Samples were _not_ measured after concentrating.
:::