---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Homogenization - June 2026 SORMI M.gigas Ctenidia from Families 1 and 9 for Glycogen Glo Assay
date: '2026-07-22'
draft: false
engine: knitr
categories: 
  - "2026"
  - "SORMI"
  - "Magallana gigas"
  - "ctenidia"
  - "Pacific oyster"
  - "Crassostrea gigas"
  - "glycogen"
  - "Glycogen Glo"
  - "homogenization"
---
# INTRO

A large experiment and sampling event was conducted on [20260626](https://github.com/RobertsLab/sormi-assay-development/tree/main/sampling-event-metadata/june-2026) (GitHub repo) as part of the [`sormi-assay-development` project](https://github.com/RobertsLab/sormi-assay-development/tree/main) (GitHub repo). As part of this, we decided to evaluate glycogen content in ctenidia from two families of oysters (USDA Families 1 and 9) from the ambient and 36°C treatments using the Glycogen Glo Assay. Family selection was decided by Steven.

# MATERIALS & METHODS

Frozen ctenidia samples (stored at -80°C) from Families 1 and 9, ambient and 36°C treatments (n = 8 from each treatment in each family), were placed on dry ice. A small portion of each ctenidia sample was weighed (to the nearest 0.01 g) and placed into a 1.5mL Safe-Lock tube (Eppendorf) containting ~300uL of 0.5mm glass beads (Reseach Products Internationsl) and 500uL of PBS. Immediatley after adding tissue, 250uL of 0.3N HCl was added and vortexed, per the Glycogen Glo Assay protocol. The samples were then homogenized in a Bullet Blender 5E Gold+ using the 1.5mL adapters. Homogenization was performed for 10 minutes at Speed 12. After homogenization, 250uL of TRIS Buffer was added to each tube and vortexed, per the Glycogen Glo Assay protocol. Samples were stored at -20°C until further processing.

Table of oyster IDs and weights (mg) of ctenidia samples used for the Glycogen Glo Assay:

| oyster_ID    | weight.mg |
|--------------|-----------|
| 1-01-Ambient | 7         |
| 1-02-Ambient | 4.7       |
| 1-03-Ambient | 2.5       |
| 1-04-Ambient | 10.7      |
| 1-05-Ambient | 7.9       |
| 1-06-Ambient | 11        |
| 1-07-Ambient | 6.1       |
| 1-08-Ambient | 24.8      |
| 1-01-36C     | 9.6       |
| 1-02-36C     | 9.2       |
| 1-03-36C     | 3.1       |
| 1-04-36C     | 12.4      |
| 1-05-36C     | 25.7      |
| 1-06-36C     | 13        |
| 1-07-36C     | 6.1       |
| 1-08-36C     | 8.8       |
| 9-01-Ambient | 7.3       |
| 9-02-Ambient | 4.4       |
| 9-03-Ambient | 4.3       |
| 9-04-Ambient | 1.8       |
| 9-05-Ambient | 18.6      |
| 9-06-Ambient | 2.8       |
| 9-07-Ambient | 5.8       |
| 9-08-Ambient | 7.4       |
| 9-01-36C     | 7.7       |
| 9-02-36C     | 15.7      |
| 9-03-36C     | 10.4      |
| 9-04-36C     | 11.3      |
| 9-05-36C     | 9.2       |
| 9-06-36C     | 4.3       |
| 9-07-36C     | 2.4       |
| 9-08-36C     | 4.9       |


For reference, here's a link to the experiment metadata for the June 2026 SORMI experiment: 

- [https://github.com/RobertsLab/sormi-assay-development/blob/main/sampling-event-metadata/june-2026/sampling-log.csv](https://github.com/RobertsLab/sormi-assay-development/blob/main/sampling-event-metadata/june-2026/sampling-log.csv) (GitHub).