---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: DNA Isolation Quantification and Gel - Lake Trout Liver Samples
date: '2024-10-25'
draft: false
engine: knitr
categories: 
  - 2024
  - DNA isolation
  - Qubit
  - DNA quantification
  - agarose gel
  - lake trout
  - Salvelinus namaycush
  - liver
---
# INTRO

Steven asked that I [isolate gDNA from a subset of lake trout (_S.namaycush_) liver samples](https://github.com/RobertsLab/resources/issues/1981) (GitHub Issue).

# METHODS

DNA was isolated using the Quick-DNA Miniprep Kit (ZymoResearch), according to the manufacturer's protocol - including the recommended addition of beta-mercaptoethanol to the lysis buffer. Liver tissues had been stored @ -20<sup>o</sup>C in RNALater (Ambion). I thawed the tubes, transferred the entire liver tissue (which was very small) to a disposable mortar/pestle combo (1.5mL tube) and homogenized. DNA was eventually eluted with 50uL of Elution Buffer.

Subsequently, DNA was quantified using the 1x dsDNA Broad Range Qubit Assay (ThermoFisher). One microliter of sample was combined with 199uL of the dye/buffer mix and measured on a Qubit 3.0.

DNA was stored in a box labelled "Lake Trout Liver gDNA" in the FTR 209 -20<sup>o</sup>C freezer.


# RESULTS

## Qubit data

- [20241025-snam-qubit-DNA.br-liver](./20241025-snam-qubit-DNA.br-liver)


| sample_ID | Original sample conc. (ng/uL) | yield(ng) |
|-----------|-------------------------------|-----------|
| FA046     | 224                           | 8960      |
| FA047     | 984                           | 39360     |
| FA048     | 1180                          | 47200     |
| FA049     | 584                           | 23360     |
| FA050     | 185                           | 7400      |
| FA051     | 990                           | 39600     |
| FA055     | 770                           | 30800     |
| FA056     | 792                           | 31680     |

::: {.callout-note}
Yield calculation is based on a total sample volume of 40uL. This is likely a conservative volume estimation for each sample, so the total yield is likely a bit higher for each.
:::