---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Daily Bits - May 2024
date: '2024-05-01'
draft: false
engine: knitr
categories: 
  - Daily Bits
  - 2024
---
## 20240531

### In lab

- Ran _G.macrocephalus_ [gDNA on a gel](../2024-05-31-Agarose-Gel---G.macrocephalus-gDNA-from-20240521/index.qmd).

- Transferred HDDs from old Owl Synology NAS to new Synology NAS and got Owl set back up. This event provided further support for why I love Synology NAS devices! The process was totally painless and all of our data/settings were still intact! Whew!

## 20240530

### Miscellaneous

- I actually have the microphone working, as well as my Ubuntu/Kubuntu virtual machines!! Seems like there's a necessary order of operations (start VMs first, then insert mic). I also got the Rode Connect software configured to have "virtual" microphone/speaker for use in video chats (e.g. Zoom). Whew! Glad this is figured out!

### Lab Meeting

- Updated everyone on my horrible experience with this new microphone...

## 20240529

### Miscellaneous

- Still can't get Ubuntu-based virtual machines to start. Installed kubuntu to see if that would work, but also did not. Fedora is the only one which will start.

  - This issue seems like it might be related to a new microphone I am trying to use (Rode VideoMic GO II) and/or the Rode Connect software! I'm unable to open Windows 10 "Sound Settings" - it just hangs at the blue screen with the gear icon. Additionally, when the microphone is unplugged, things all seem to operate completely normally! Weird... Will continue to play around to see if I can figure out if its a software thing or a hardware thing...


## 20240528

### Miscellaneous

- Ubuntu virtual machine in VMWare Player refused to boot up. Spent a significant amount of time working to restore it. Even tried booting from a backup, but that didn't work either! Resorted to using existing Fedora Silverblue VM that I had been messing around with.

- Submitted PO request for [Azenta mussel sRAN-seq project](https://github.com/RobertsLab/resources/issues/1902#issuecomment-2129794535) (GitHub Issue).

## 202405213

### In lab

- Received a bunch of packages. Documented and put away.

- Unpacked new Synology server - Owl replacement.

- Isolated/quantified Pacific cod liver DNA.

## 20240513

### Miscellaneous

- Identified and purchased reagents/supplies for the RNA isolation for lifestage carryover project.

- Identified and purchased reagents/supplies for DNA isolation for cod project.

- Purchased new Synology server to replace Owl.

- Requsted quote from UW NWGC for mussel WGBS.

- Requested quote from UW PacBio for mussel genome methylation sequencing.

- Requested quote from UW NanoPore for mussel genome methylation sequencing.

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Figured out how to transfer trimmed FastQs to Javi.

## 20240510

### Science Hour

## 20240509

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

-   Developer came through with a fix for the ShortStack [`index error out of range` issue](https://github.com/MikeAxtell/ShortStack/issues/146#issuecomment-2093495262) (GitHub Issue)!!

- Started to run [`ShortStack`](https://github.com/MikeAxtell/ShortStack) on *P.evermanni*.

### Pub-a-thon

- Need to write up the *P.evermanni* [`ShortStack`](https://github.com/MikeAxtell/ShortStack) results (finally!).

### Lab meeting

- Spent the time discussing gene enrichment.

## 20240508

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Continued to try to troubleshoot the [`index error out of range` issue](https://github.com/MikeAxtell/ShortStack/issues/146#issuecomment-2093495262) (GitHub Issue) for *P.evermanni*.

    - Developer responded! Tested out some things.

    - Met with Steven to try to run on different computer.

## 20240507

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Continued to try to troubleshoot the [`index error out of range` issue](https://github.com/MikeAxtell/ShortStack/issues/146#issuecomment-2093495262) (GitHub Issue) for *P.evermanni*.

    - No real progress. I've added various print statements to the source code to try to figure out where things are going wrong, but it's not very informative.

    - Tried a different set of trimming parameters (30bp instead of 30) to see if that might make a difference, but it didn't...

## 20240506

### In lab

- Helped Eric with additional qPCR analysis.

## 20240503

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Continued to try to troubleshoot the [`index error out of range` issue](https://github.com/MikeAxtell/ShortStack/issues/146#issuecomment-2093495262) (GitHub Issue) for *P.evermanni*.

### Science Hour

- Discussed gene enrichment analysis with Grace L. and Laura Spencer.

    - Laura provided a nice, concise walk-through of using the [DAVID website](https://david.ncifcrf.gov/tools.jsp).

## 20240502

### Lab meeting

- Covered a lot of lab stuff for summer: undergrads, hack week, how-tos

- Discussed sections of "Braiding Sweetgrass"

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Started to troubleshoot [`ShortStack`](https://github.com/MikeAxtell/ShortStack) `index error out of range` issue with *P.evermanni*.

### Pub-a-thon

- This actually evolved into discussion of differences between genome-guided alignments and alignment-free approaches.

## 20240501

### Miscellaneous

- Updated Gannet's list of notebook backups.

- Read sections of "Braiding Sweetgrass" for lab meeting tomorrow.
