---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: RNA Isolation - C.gigas Lifestage Carryover Seed and Spat
date: '2024-03-19'
draft: false
engine: knitr
categories: 
  - "RNA isolation"
  - "Crassostrea gigas"
  - "Lifestage carryover"
  - "Pacific oyster"
  - "2024"
---
# INTRO

I was [asked to isolate RNA from a list of samples](https://github.com/RobertsLab/resources/issues/1844#issuecomment-1998021805) (GitHub Issue) from a number of [_Crassostrea gigas_ (Pacific oyster)](http://en.wikipedia.org/wiki/Pacific_oyster) spat and seed that had been collected as part of the [`project-gigas-carryover`](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover) (GitHub repo).

# MATERIALS & METHODS
Oysters had been previously preserved in RNAlater (Ambion), supernatant removed, and then frozen @ -80<sup>o</sup>C. All samples were treated in the following fashion (12 spat were processed, followed by 12 seed samples.). Here's the full [list of samples](https://github.com/RobertsLab/project-gigas-carryover/blob/82f1a4bcd5e2ce80cea9916f271bf1d54f740bd1/lifestage_carryover/data/sampling_metadata/20240314_rna_extractions.csv) (GitHub; commit `82f1a4b`).

## RNA Isolation
RNA isolations were conducted using the Directzol RNA Miniprep Kit (ZymoResearch).

- Added 350uL of TriReagent (ZymoResearch) to existing 1.5mL tubes containing the sample.
- Homogenized using disposble pestles.
- Centrigured at 21,000g to pellet insoluble material.
- Transferred 325uL of homogenate to a 1.5mL tube.
- Added 325uL (i.e. equal volume) of 100% ethanol to homogenate and vortexed.
- Transferred solution to spin columns.
- Followed kit protocol, including DNase step.
- Elutions:

  - Spat: 50uL of H<sub>2</sub>.
  - Seed: 100uL of H<sub>2</sub>.

Samples were temporarily stored on ice for quantification and reverse transcription.

## RNA Quantification
RNA was quantified with the Roberts Lab Qubit 3.0 fluorometer (Invitrogen). Samples were quantified with either the Qubit RNA Broad Range (BR) asssay (Invitrogen) or, if a sample had insufficient concentrations of RNA to be detected, with the High Sensitivity (HS) assay (Invitrogen). 1uL of sample was used for the assay(s).

# RESULTS

Raw Qubit data is here:

- [`20240319-cgig-qubit-carryover-spat-seed.csv`](../../../../project-gigas-carryover/lifestage_carryover/data/qubit/20240319-cgig-qubit-carryover-spat-seed.csv)

The following spat samples didn't yield any RNA:

- 262
- 274

The following seed samples didn't yield any RNA:

- 211
- 234
- 256
- 264
- 266

::: {.callout-warning}
The seed samples consisted of large quantities of tissue, which I think caused issues with the TriReagent extraction. This resulted in some strange results after homogenization and centfiguation. Many of them appeared to separate into phases (a dark red top phase and a clear bottom phase). Additionally, after combining with ethanol, there were large quantities of precipitate in most of the samples; these precipitates were _not_ transferred to columns. The red phase still contained a lot of insoluble material, which possibly clogged columns and inhibited RNA binding.
:::


Overall, it would seem that going forward, a significantly large quantity of TriReagent should be used and/or taking a section of the sample (instead of the entire sample) might be warranted. In regards to the latter, I'm not sure if this is desirable, as these are whole oysters and I'm not certain what the implications for comparative transcriptomics would be if using only a portion of the oyster.

Next up, create some cDNA...
