---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
date: 2011-08-12 02:53:30+00:00
layout: post
slug: qpcr-c-gigas-v-vulnificus-exposure-cdna-from-20110311
title: qPCR - C.gigas V.vulnificus Exposure cDNA (from 20110311)
categories:
  - "2011"
  - "cDNA"
  - "CFX96"
  - "Crassostrea gigas"
  - "defensin"
  - "GAPDH"
  - "Pacific oyster"
  - "qPCR"
  - "Vibrio exposure"
  - "Vibrio vulnificus"
---

Ran a qPCR using 3hr Vibrio vulnificus exposure cDNA from [20110311](../2011-03-11-reverse-transcription-c-gigas-bbdh-dnased-rna-from-20090507-for-props/index.qmd). Original experiment conducted on 20110111 with defensin primers (SR IDs: 1109 & 1070) and GAPDH (SR IDs: 1172 & 1173). [Master mix calcs are here](https://eagle.fish.washington.edu/Arabidopsis/Notebook%20Workup%20Files/20110811-01.jpg). Cycling params, plate layout, etc can be seen in the qPCR Report (see Results). This was performed to help Herschel.

Results:

qPCR Report (dead link - was on purple pelican 2011-08-11%2009-47-09_CC009827.pdf) (PDF)

qPCR Data File (dead link - was on purple pelican Roberts%20Lab_2011-08-11%2009-47-09_CC009827.pcrd) (CFX96)

Initial glance at data looks good. GAPDH exhibits highly consistent Cq values across all samples, controls and exposed. Although, there is slight amplification of something in the two water samples for GAPDH, the melt curve shows that this product has a different melting temperature than our intended target. As such, I believe the GAPDH data to be useable, since no other samples exhibit this smaller product. Defensin shows clean water sample and clean melt curves with a single peak. However, it seems like we may not see an effect on defensin expression in response to the Vibrio vulnificus exposure...
