---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Sample Homogenization - C.gigas Lifestage Carryover Samples Using TriZol and Bullet Blender
date: '2025-05-12'
draft: false
engine: knitr
categories: 
  - "2025"
  - "Bullet Blender"
  - "homogenization"
  - "TriZol"
  - "Crassostrea gigas"
  - "Pacific oyster"
  - "Magallana gigas"
---
# INTRO

I was [asked to isolate RNA from a list of 60 samples](https://github.com/RobertsLab/resources/issues/2062) (GitHub Issue) from a number of [_Crassostrea gigas_ (Pacific oyster)](http://en.wikipedia.org/wiki/Pacific_oyster) spat and seed that had been collected as part of the [`project-gigas-carryover`](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover) (GitHub repo).

# MATERIALS & METHODS

Oysters had been previously preserved in RNAlater (Ambion), supernatant removed, and then frozen @ -80<sup>o</sup>C. All samples were treated in the following fashion. Here's the full [list of samples](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/sampling_metadata/20241230_rna_extractions.csv) (GitHub).

Samples were transferred to 1.5mL SafeLock (Eppendorf) microcentrifuge tubes containig ~100uL of 0.5mm zirconium oxide beads and 250uL of TriZol. Samples were homogenized using the Roberts Lab Bullet Blender 5E Gold + (NextAdvance) with 1.5mL tube adapters for 5mins at speed 12. The Bullet Blender was pre-cooled, and cooled, using dry ice.

Samples with shells which did not appear to fully homogenize were manually disrupted in the existing tube using a disposable microfuge pestle.

After homogenization, 500uL of TriZol was added to each tube, vortexed, incubated at room temperature for ~10mins, and subsequently processed for RNA isolation.

::: {.callout-note}
Due to time constraints, the following samples were stored overnight at -20<sup>o</sup>C:

`78`
`79`
`81`
`83`
`86`
`88`
`89`
`92`
`93`
`96`
`97`
`98`
:::

