---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Genome Assembly - S.namaycush Siscowet Ecotype with PacBio HiFi Reads Using hifiasm on Hyak
date: '2026-03-31'
draft: false
engine: knitr
categories: 
  - "2026"
  - "Genome Assembly"
  - "PacBio"
  - "HiFi Reads"
  - "hifiasm"
  - "Salvelinus namaycush"
  - "Lake Trout"
  - "Siscowet"
  - "Klone"
  - "Hyak"
---
# INTRO

As part of [`project-lake-trout`](https://github.com/RobertsLab/project-lake-trout) (GitHub repo), Steven [asked that I assemble the genome of a siscowet ecotype of lake trout](https://github.com/RobertsLab/resources/issues/2409) (GitHub Issue), *Salvelinus namaycush*, using PacBio HiFi reads. I previously assembled this genome [using Flye, on 20260326](../2026-03-26-Genome-Assembly---S.namaycush-Siscowet-Ecotype-with-PacBio-HiFi-Reads-Using-Flye/index.qmd) (notebook entry), but [Steven asked me to also try hifiasm](https://github.com/RobertsLab/resources/issues/2409#issuecomment-4150948212) (GitHub Issue)for the assembly.

I performed the assembly on Hyak (Klone), UW's high-performance computing cluster. I used our Apptainer (Singularity) container to run the job (`srlab-R4.4-bioinformatics-container-e5bcfea.sif`), which includes hifiasm version 0.25.0.

Below is the rendered markdown from `13.1-hifiasm-genome-assembly-siscowet.Rmd`. The run was _very_ fast; it only took a day and half.

# PRIMARY OUTPUTS

hifiasm produces three assemblies: a primary assembly, and two haplotype-resolved assemblies. Below are the links to the FastA files. The outputs are only GFA graph files. I had to convert them to FastA using [gfatools](https://github.com/lh3/gfatools).

Primary assembly:

- FastA (3.8GB): https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/pb-hifiasm-siscowet-assembly.fa

- MD5: https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/pb-hifiasm-siscowet-assembly.fa.md5

- FastA index: https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/pb-hifiasm-siscowet-assembly.fa.fai

Haplotype 1:

- FastA (3.4GB): https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/pb-hifiasm-siscowet-hap1-assembly.fa

- MD5: https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/pb-hifiasm-siscowet-hap1-assembly.fa.md5

- FastA index: https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/pb-hifiasm-siscowet-hap1-assembly.fa.fai

Haplotype 2:

- FastA (3.2GB): https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/pb-hifiasm-siscowet-hap2-assembly.fa

- MD5: https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/pb-hifiasm-siscowet-hap2-assembly.fa.md5

- FastA index: https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/pb-hifiasm-siscowet-hap2-assembly.fa.fai

After this, I'll compare the two assemblies (Flye vs. hifiasm) using [QUAST](https://github.com/ablab/quast), which will provide a more comprehensive set of assembly statistics and metrics.

---

# 1 BACKGROUND

Use [hifiasm](https://github.com/chhylp123/hifiasm) (GitHub) (Cheng et
al. 2021, 2022, 2024) to assemble PacBio reads for *S.namaycush*
`siscowet` ecotype.

Due to large file sizes, the outputs will not be on GitHub. They may be
found here instead:

- <https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-hifiasm-genome-assembly-siscowet/>

# 2 SETUP

## 2.1 Libraries

## 2.2 Set R variables

``` r
# OUTPUT DIRECTORY
data_dir <- "/mmfs1/gscratch/scrubbed/samwhite/gitrepos/RobertsLab/project-lake-trout/data/pacbio-siscowet"
output_dir <- "../output/13.1-hifiasm-genome-assembly-siscowet"

# PROGRAMS
gfatools <- c("/srlab/programs/gfatools/gfatools")
hifiasm <- c("/srlab/programs/miniforge3-24.7.1-0/envs/hifiasm-0.25.0_env/bin/hifiasm")


# SETTINGS
threads <- "40"


# Export these as environment variables for bash chunks.
Sys.setenv(
  data_dir = data_dir,
  gfatools = gfatools,
  hifiasm=hifiasm,
  output_dir = output_dir,
  threads = threads
)
```

# 3 RUN HIFIASM

``` bash
# Make output directory, if it doesn't exist
mkdir --parents "${output_dir}"

cd "${output_dir}"

# Create an array of .fastq.gz files
fastqs=(${data_dir}/*.fastq.gz)

# Print the result (optional, for verification)
## newline-delimited format
echo "List of FastQs used for assembly:"

printf "%s\n" "${fastqs[@]}" \
| tee input_fastqs.txt

# Run hifiasm assembly
"${hifiasm}" \
-o pb-hifiasm-siscowet-assembly.asm \
-t "${threads}" \
"${fastqs[@]}" \
> pb-hifiasm-siscowet-assembly.log 2>&1
```

# 4 GFATOOLS

## 4.1 Primary contigs to FastA

This will extract a FastA file from the graph files output by hifiasm.

``` bash
cd "${output_dir}"

"${gfatools}" gfa2fa \
pb-hifiasm-siscowet-assembly.asm.bp.p_ctg.gfa \
> pb-hifiasm-siscowet-assembly.fa

samtools faidx pb-hifiasm-siscowet-assembly.fa
```

## 4.2 Haplotype 1 contigs to FastA

This will extract a FastA file from the graph files output by hifiasm.

``` bash
cd "${output_dir}"

"${gfatools}" gfa2fa \
pb-hifiasm-siscowet-assembly.asm.bp.hap1.p_ctg.gfa \
> pb-hifiasm-siscowet-hap1-assembly.fa

samtools faidx pb-hifiasm-siscowet-hap1-assembly.fa
```

## 4.3 Haplotype 2 contigs to FastA

This will extract a FastA file from the graph files output by hifiasm.

``` bash
cd "${output_dir}"

"${gfatools}" gfa2fa \
pb-hifiasm-siscowet-assembly.asm.bp.hap2.p_ctg.gfa \
> pb-hifiasm-siscowet-hap2-assembly.fa

samtools faidx pb-hifiasm-siscowet-hap2-assembly.fa
```

## 4.4 Generate checksums

``` bash
cd "${output_dir}"

for fasta in *.fa
do
  md5sum "${fasta}" \
  | tee "${fasta}".md5
done
```

    ## d41d8cd98f00b204e9800998ecf8427e  pb-hifiasm-lean-assembly.fa
    ## c5e88b1d81585383b3fb7354aa624f34  pb-hifiasm-siscowet-assembly.fa
    ## cb85945e4b07c42fba548865e3039d00  pb-hifiasm-siscowet-hap1-assembly.fa
    ## 5d813ba82405afef60628e3c8325306f  pb-hifiasm-siscowet-hap2-assembly.fa

# 5 REFERENCES

<div id="refs" class="references csl-bib-body hanging-indent">

<div id="ref-cheng2024" class="csl-entry">

Cheng, Haoyu, Mobin Asri, Julian Lucas, Sergey Koren, and Heng Li. 2024.
“Scalable Telomere-to-Telomere Assembly for Diploid and Polyploid
Genomes with Double Graph.” *Nature Methods* 21 (6): 967–70.
<https://doi.org/10.1038/s41592-024-02269-8>.

</div>

<div id="ref-cheng2021" class="csl-entry">

Cheng, Haoyu, Gregory T. Concepcion, Xiaowen Feng, Haowen Zhang, and
Heng Li. 2021. “Haplotype-Resolved de Novo Assembly Using Phased
Assembly Graphs with Hifiasm.” *Nature Methods* 18 (2): 170–75.
<https://doi.org/10.1038/s41592-020-01056-5>.

</div>

<div id="ref-cheng2022" class="csl-entry">

Cheng, Haoyu, Erich D. Jarvis, Olivier Fedrigo, et al. 2022.
“Haplotype-Resolved Assembly of Diploid Genomes Without Parental Data.”
*Nature Biotechnology* 40 (9): 1332–35.
<https://doi.org/10.1038/s41587-022-01261-x>.

</div>

</div>