---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: qPCRs - C.gigas Lifestage Carryover ATP_synthase cGAS citrate_synthase and VIPERIN
date: '2025-06-03'
draft: true
engine: knitr
categories: 
  - "2025"
  - "Crassostrea gigas"
  - "Pacific oyster"
  - "VIPERIN"
  - "citrate synthase"
  - "ATP synthase"
  - "cGAS"
  - "SsoFast"
  - "CFX Connect"
  - "CFX96"
  - "project-gigas-carryover"
---
# INTRO

Continuing work with [`project-gigas-carryover` lifestage_carryover](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover) (GitHub repo) after [creating cDNA on 20250516](../2025-05-16-Reverse-Transcription---C.gigas-Lifestage-Carryover-RNA/index.qmd), it was finally time to run the qPCRs.

This notebook describes how the qPCRs were run and links to the various output files. It also provides a brief overview of each primer set's amplification profiles. This notebook does _not_ have any analysis. This will be performed later.

# MATERIALS & METHODS

Based on [results from an initial round of qPCRs on 20240327](../2024-03-27-qPCR-Analysis---C.gigas-Lifestages-Carryover-from-20240325/index.qmd) (Notebook entry), the following primer sets were selected:

| SR ID | Primer Name          |
|-------|----------------------|
| 1385  | Cg_ATPsynthase_F     |
| 1386  | Cg_ATPsynthase_R     |
| 1383  | Cg_citratesynthase_F |
| 1384  | Cg_citratesynthase_R |
| 1829  | Cg_VIPERIN_F         |
| 1828  | Cg_VIPERIN_R         |
| 1827  | Cg_cGAS_F            |
| 1826  | Cg_cGAS_R            |

All samples were run in triplicate, on low-profile, white 96-well plates (USA Scientific) in a CFX Connect (Bio-Rad) or CFX96 (Bio-Rad) real-time thermalcycler. All reactions consisted of the following:

| Component                                          | Stock Concentration | Volume (uL) |
|----------------------------------------------------|---------------------|-------------|
| cDNA                                               | NA                  | 1           |
| SsoAdvanced Universal SYBR Green Supermix (BioRad) | 2x                  | 10          |
| P<sub>F</sub>                                      | 10uM                | 0.5         |
| P<sub>R</sub>                                      | 10uM                | 0.5         |
| H<sub>2</sub>O                                     | NA                  | 8           |
| TOTAL                                              |                     | 20          |

Master mixes were distributed across one plate for each primer set and included no template controls (NTCs).

For cycling parameters, plate layouts, etc. see the [RESULTS](#results) section below.


# RESULTS