---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
layout: post
title: Daily Bits - July 2023
date: '2023-07-05 07:30'
tags: 
  - daily bits
categories: 
  - 2023
  - Daily Bits
---




20230726

- In lab.

  - [_C.gigas_ polyIC qPCRs](https://robertslab.github.io/sams-notebook/posts/2023/2023-07-26-qPCR---C.gigas-polyIC/)./

  - Started _M.magister_ (Dungeness crab) read extraction from MEGAN.



20230725

- Spent time reviewing [CEABIGR](https://github.com/sr320/ceabigr) work/progress.

- Helped [troubleshoot UniProt Python API](https://github.com/RobertsLab/resources/issues/1672) (GitHub Issue).

- Meeting with Steven and Noah to review qPCR results.

- [DuMOAR](https://github.com/laurahspencer/DuMOAR) meeting.

  - Reviewed MEGAN results.

  - Assigned to pull out `Arthropoda` and `Not Assigned` reads.



20230724

- CEABIGR meeting

  - Reviewed Steven's genetic relatedness matrix results.

  - Reviewed Zach's lncRNA expression analyses.



20230721

- In lab.

  - qPCRs for Noah's _C.gigas_ heat/mechanical stress project. 

    - [Notebook entry](https://robertslab.github.io/sams-notebook/posts/2023/2023-07-21-qPCR---C.gigas-Ctenidia-cDNA-for-Noahs-Heat-Mechanical-Stress-Project/)/

  - RNA quantification for Matt's _C.gigas_ polyIC project.

    - [Notebook entry](https://robertslab.github.io/sams-notebook/posts/2023/2023-07-21-RNA-Quantification---C.gigas-PolyIC/)/

  - Reverse transcription for Matt's _C.gigas_ polyIC project.

    - [Notebook entry](https://robertslab.github.io/sams-notebook/posts/2023/2023-07-21-Reverse-Transcription---C.gigas-PolyIC-RNA/)/



20230720

- Meeting w/Steven & Noah.

- Pub-a-thon.

- Lab meeting.



20230719

- In lab.

  - qPCRs for Noah's _C.gigas_ heat/mechanical stress project. 

    - [Notebook entry](https://robertslab.github.io/sams-notebook/posts/2023/2023-07-19-qPCR---C.gigas-Ctenidia-cDNA-for-Noahs-Heat-Mechanical-Stress-Project/)/



20230713

- In lab.

  - RNA quantification for Noah's _C.gigas_ heat/mechanical stress project.

    - [Notebook entry](https://robertslab.github.io/sams-notebook/posts/2023/2023-07-13-RNA-Quantification---C.gigas-RNA-from-Noahs-Heat-Mechanical-Stress-Project/)/

  - Reverse transcription of Noah's RNA isolated yesterday.

    - [Notebook entry](https://robertslab.github.io/sams-notebook/posts/2023/2023-07-13-Reverse-Transcription---C.gigas-RNA-from-Noahs-Heat-Mechanical-Stress-Project/)/

  - qPCR primer test for Noah's _C.gigas_ heat/mechanical stress project.

    - [Notebook entry](https://robertslab.github.io/sams-notebook/posts/2023/2023-07-13-qPCR---C.gigas-cDNA-Primer-Tests-for-Noahs-Heat-Mechanical-Stress-Project/)/

- Lab meeting.



20230712

- In lab.

  - RNA isolations for Noah's _C.gigas_ heat/mechanical stress project.

    - [Notebook entry](https://robertslab.github.io/sams-notebook/posts/2023/2023-07-12-RNA-Isolation---C.gigas-Ctenidia-from-Noahs-Heat-Mechanical-Stress-Project/)/