---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: DNA Isolation - Pacific cod liver
date: '2024-05-21'
draft: false
engine: knitr
categories: 
  - DNA isolation
  - Pacific cod
  - liver
  - Gadus macrocephalus
  - DNA quantification
  - Qubit
  - 2024
---
# INTRO

We recently sent a bunch of liver samples off to Psomagagen for whole genome bisulfite sequencing (WGBS). As documented in [this GitHub Issue](https://github.com/RobertsLab/resources/issues/1894), Psomagen discovered that the DNA quality from the samples was poor (i.e. heavily degraded). Steven asked to test DNA isolations on our end with four untouched samples, and four of the samples sent to Psomagen:

:::{.callout-note}
Untouched liver samples (never sent for RNA or DNA extraction), one from each treatment:
6, 42, 95, 122

Liver samples that were sent for DNA extraction for which we still have tissue, one from each treatment:
12, 39, 79, 118
:::

::: {.callout-warning}
Sample 118 did not have any tissue in the tube.
:::

# METHODS

DNA was isolated using the Quick-DNA Miniprep Kit (ZymoResearch), according to the manufacturer's protocol - including the recommended addition of beta-mercaptoethanol to the buffer. Briefly, small tissue sections (unweighed, just "eyeballed") were subsampled and homogenized with a disposable mortar/pestle combo (1.5mL tube). DNA was eventually eluted with 50uL of H<sub>2</sub>O.

Subsequently, DNA was quantified using the 1x dsDNA Qubit Assay (ThermoFisher). One microliter of sample was combined with 199uL of the dye/buffer mix and measured on a Qubit 3.0.

DNA integrity will be assessed via agarose gel in the near future.

# RESULTS

## Qubit data

- [20240521-qubit-pcod-liver-DNA](https://docs.google.com/spreadsheets/d/11OkLDmC0je-4edhpRV_CxbT_ZFI20xsMvpv4c90M-fE/edit?usp=sharing) (Google Sheet)


## DNA Yields

| Sample_ID | Concentration (ng) | Untouched (Y/N) |
|-----------|--------------------|-----------------|
| 6         | 342                | Y               |
| 42        | 173                | Y               |
| 95        | 200                | Y               |
| 122       | 302                | Y               |
| 12        | 1180               | N               |
| 39        | 1220               | N               |
| 79        | 1200               | N               |
| 118       | Out of range       | N               |

: DNA yields {.striped .hover}


We see higher yields in the samples that had previously been sampled (12, 39, 79), but I can't be sure if this was due to using larger amounts of tissue or not. Will run on a gel to evaluate integrity later.