---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: qPCR - C.gigas Alternative Oxidases Primer Tests
date: '2025-05-27'
draft: true
engine: knitr
categories: 
  - "2025"
  - "Crassotrea gigas"
  - "Pacific oyster"
  - "Magallana gigas"
  - "primers"
  - "AOX"
  - "alternative oxidase"
  - "XM_066083499.1"
  - "XM_034462847.2"
  - "NM_001305360.1"
---
# INTRO

I previously designed primers for three alternative oxidase (AOX) variants on [20250117](../2025-01-17-Primer-Design---C.gigas-Alternative-Oxidase-AOX-Variants-Using-Primer3/index.qmd) (Notebook entry). Alternative oxidase is a mitochondrial gene/enzyme known to be
responsive to oxidative stress, so this may be a useful biomarker that
we haven’t previously considered.

I needed to test the primer sets to see if they worked and were template-specific. I also used this as an opportunity to introduce some of the undergrads in lab to qPCR.


## Alternative oxidase variants

The primers were designed on the following NCBI sequences:

- [NP_001292289.1](https://www.ncbi.nlm.nih.gov/protein/NP_001292289.1?report=genbank&log$=protalign&blast_rank=1&RID=SMV9RMT6013):
  alternative oxidase, mitochondrial-like $$Magallana gigas$$

  - Nucleotide:
    [`NM_001305360.1`](https://www.ncbi.nlm.nih.gov/nuccore/NM_001305360.1)

  - Gene: `LOC105322704`

- [`XP_034318738.2`](https://www.ncbi.nlm.nih.gov/protein/XP_034318738.2?report=genbank&log$=protalign&blast_rank=2&RID=SMV9RMT6013):
  alternative oxidase, mitochondrial-like isoform X2 $$Magallana
  gigas$$

  - Nucleotide:
    [`XM_034462847.2`](https://www.ncbi.nlm.nih.gov/nuccore/XM_034462847.2)

  - Gene: `LOC105322704`

- [`XP_065939571.1`](https://www.ncbi.nlm.nih.gov/protein/XP_065939571.1?report=genbank&log$=protalign&blast_rank=3&RID=SMV9RMT6013):
  alternative oxidase, mitochondrial-like isoform X1 $$Magallana
  gigas$$

  - Nucleotide:
    [`XM_066083499.1`](https://www.ncbi.nlm.nih.gov/nuccore/XM_066083499.1)

  - Gene: `LOC105322704`

# MATERIALS & METHODS

## Primers

| sr_ID | Primer name               |
|-------|---------------------------|
| 1849  | cgig-AOX-XM_066083499.1-R |
| 1848  | cgig-AOX-XM_066083499.1-F |
| 1847  | cgig-AOX-XM_034462847.2-R |
| 1846  | cgig-AOX-XM_034462847.2-F |
| 1845  | cgig-AOX-NM_001305360-R   |
| 1844  | cgig-AOX-NM_001305360-F   |

## Reactions

All samples were run in duplicate, on low-profile, white 96-well plates (USA Scientific) in a CFX Connect (BioRad) real-time thermalcycler. All reactions consisted of the following:

| Component                                          | Stock Concentration | Volume (uL) |
|----------------------------------------------------|---------------------|-------------|
| cDNA                                               | NA                  | 1           |
| SsoAdvanced Universal SYBR Green Supermix (BioRad) | 2x                  | 10          |
| P<sub>F</sub>                                      | 10uM                | 0.5         |
| P<sub>R</sub>                                      | 10uM                | 0.5         |
| H<sub>2</sub>O                                     | NA                  | 8           |
| TOTAL                                              |                     | 20          |

For cycling parameters, plate layouts, etc. see the [RESULTS](#results) section below.

