---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: DNA RNA Isolation and Quantification - G.macrocephalus Blood Using Bullet Blender and Zymo Quick DNA RNA MiniPrep
date: '2025-04-30'
draft: true
engine: knitr
categories: 
  - "2025"
  - "Bullet Blender"
  - "Pacific cod"
  - "Gadus macrocephalus"
  - "blood"
  - "DNA isolation"
  - "RNA isolation"
  - "DNA quantification"
  - "RNA quantification"
  - "Qubit"
---
# INTRO

Continued with co-isolation of DNA and RNA from [Pacific cod blood samples selected by Laura](https://github.com/RobertsLab/resources/issues/1951#issuecomment-2667027910) (GitHub Issue). See the [RESULTS section](#results) for a list of samples.

# MATERIALS & METHODS

## HOMOGENIZATION

Blood samples were thawed on ice and then 200uL of 2x DNA/RNA Shield was added to each and vortexed. The liquid and the gelatinous blood clot were transferred to 1.5mL SafeLock snap cap tubes (Eppendorf). I then added beads in the recommended proportions for the [Bullet Blender Fresh Blood protocol](https://www.nextadvance.com/homogenization-protocols/classic/bloodfresh-76-43.html). Samples were subjected to blending in the Bullet Blender 5E Gold+, precooled with dry ice, for 5mins at Speed 12.

Here is a brief overview of the protocol:

Bead combination:

- 0.5 mm zirconium oxide beads (ZROB05). Use a volume of beads equivalent to 0.25 x the volume of the sample plus
- 0.15 mm zirconium oxide beads (ZROB015). Use a volume of beads equivalent to 0.25 x the volume of the sample

Procedure

1. Place the sample in the tube with the beads.
2. Close the tubes tightly and place them in the Bullet Blender.
3. Set the controls for Speed 12 and Time 5. Press Start.
4. After the run, remove the tubes from the instrument and visually inspect the samples. If homogenization is incomplete, repeat the homogenization step.
5.Proceed with your downstream application.

## DNA/RNA Isolation

DNA and RNA isolations were performed using the Quick-DNA/RNA MiniPrep Plus Kit (ZymoResearch). 

::: {.callout-note}
Protocol was followed with the following notes/changes:

- Did _not_ perform Proteinase K digestion after homogenization.
- RNA was treated with DNase I.
- DNA was eluted with 100uL of H<sub>2</sub>O.
- RNA was eluted with 50uL of H<sub>2</sub>O.
:::

## Quantification

DNA was quantified using the Roberts Lab Qubit 3.0 and the 1x High Sensitivity dsDNA Assay (Invitrogen), using 1uL of each sample.

RNA was quantified using Roberts Lab Qubit 3.0 and the RNA High Sensitivity Assay (Invitrogen), using 1uL of each sample.



# RESULTS


# SUMMARY
## DNA

Qubit (Google Sheets):

- [20250430-gmac-qubit-DNA.hs-blood-01](https://docs.google.com/spreadsheets/d/1azVk4eW8n1lTG1Mz2CGU6UcMLIrx9iwWnaZ6MQJmThE/edit?usp=sharing)

- [20250430-gmac-qubit-DNA.hs-blood-02](https://docs.google.com/spreadsheets/d/1tyE4pFV_CT-mdOoHs-T7UFOHrp1G26SNs8ShyZLOoUA/edit?usp=sharing)


| sample_ID | Concentration (ng/uL) | Dilution factor | Volume (uL) | Yield (ng) |
|-----------|-----------------------|-----------------|-------------|------------|
| 125B      | 12.4                  | 1               | 90          | 1116       |
| 126B      | 64.6                  | 10              | 90          | 58140      |
| 127B      | 19.6                  | 1               | 90          | 1764       |
| 128B      | 10.6                  | 1               | 90          | 954        |
| 130B      | 7.78                  | 1               | 90          | 700.2      |
| 131B      | 86                    | 1               | 90          | 7740       |
| 132B      | 27.2                  | 1               | 90          | 2448       |
| 133B      | 10.4                  | 1               | 90          | 936        |
| 134B      | 14.5                  | 10              | 90          | 13050      |
| 135B      | 47.4                  | 1               | 90          | 4266       |
| 136B      | 22.6                  | 1               | 90          | 2034       |
| 137B      | 10.1                  | 1               | 90          | 909        |
| 138B      | 13.6                  | 1               | 90          | 1224       |
| 139B      | 48.8                  | 10              | 90          | 43920      |
| 140B      | 26.2                  | 1               | 90          | 2358       |
| 141B      | 15.9                  | 1               | 90          | 1431       |
| 142B      | 28.8                  | 1               | 90          | 2592       |
| 143B      | 27.8                  | 1               | 90          | 2502       |
| 144B      | 54                    | 10              | 90          | 48600      |
| 145B      | 39.2                  | 10              | 90          | 35280      |
| 146B      | 54.6                  | 10              | 90          | 49140      |
| 147B      | 17.2                  | 1               | 90          | 1548       |
| 148B      | 64.6                  | 10              | 90          | 58140      |
| 150B      | 19.5                  | 10              | 90          | 17550      |

## RNA

Qubit (Google Sheets):

- [20250430-gmac-qubit-RNA.hs-blood-01](https://docs.google.com/spreadsheets/d/1T0HkNfvnqDyEed7-SP2E9VhMvXNvd7vXd26QaOHPtnU/edit?usp=sharing)

- [20250430-gmac-qubit-RNA.hs-blood-02](https://docs.google.com/spreadsheets/d/1-td5-ub6kqWrKXzYx7Ub6Ayw_OAE80oYuQKfs4jMFto/edit?usp=sharing)

| sample_ID | Concentration (ng/uL) | Dilution factor | Volume (uL) | Yield (ng) |
|-----------|-----------------------|-----------------|-------------|------------|
| 125B      | 6.12                  | 1               | 40          | 244.8      |
| 126B      | 7.7                   | 1               | 40          | 308        |
| 127B      | 21.2                  | 1               | 40          | 848        |
| 128B      | 67.2                  | 1               | 40          | 2688       |
| 130B      | Out of range          | 1               | 40          | 0          |
| 131B      | Out of range          | 1               | 40          | 0          |
| 132B      | 22.2                  | 1               | 40          | 888        |
| 133B      | 7.58                  | 1               | 40          | 303.2      |
| 134B      | 8.78                  | 1               | 40          | 351.2      |
| 135B      | 46.4                  | 1               | 40          | 1856       |
| 136B      | 92.2                  | 1               | 40          | 3688       |
| 137B      | 12.7                  | 1               | 40          | 508        |
| 138B      | 9.88                  | 1               | 40          | 395.2      |
| 139B      | 79.2                  | 1               | 40          | 3168       |
| 140B      | 13.9                  | 1               | 40          | 556        |
| 141B      | 7.94                  | 1               | 40          | 317.6      |
| 142B      | 11.8                  | 1               | 40          | 472        |
| 143B      | 14                    | 1               | 40          | 560        |
| 144B      | 73.2                  | 1               | 40          | 2928       |
| 145B      | 73                    | 1               | 40          | 2920       |
| 146B      | 104                   | 1               | 40          | 4160       |
| 147B      | 10.5                  | 1               | 40          | 420        |
| 148B      | 90.8                  | 1               | 40          | 3632       |
| 150B      | 23                    | 1               | 40          | 920        |

# SUMMARY

