---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Data Received - Sea Lice PacBio Genome Sequencing
date: '2026-05-07'
draft: false
engine: knitr
categories: 
  - "2026"
  - "Data Received"
  - "PacBio"
  - "Caligus rogercresseyi"
  - "sea lice"
  - "Genome Sequencing"
---
# INTRO

PacBio genome sequencing data for Caligus rogercresseyi (sea lice) was received from the Cristian Gallardo-Escárate lab at the University of Concepción in Chile. This is part of a project to generate a high-quality reference genome for C. rogercresseyi, which is an important ectoparasite of salmonids in Chile and other regions. The data will be used for genome assembly and annotation, as well as comparative genomics analyses with other sea lice species.

After the data is downloaded to our server, I'll [perform genome assemblies of the two samples](https://github.com/RobertsLab/resources/issues/2421) (GitHub Issue).

# DATA

Data was downloaded to our server, Owl, via `lftp` from the Gallardo-Escárate lab's server. The data consists of PacBio HiFi reads in FASTQ format. No checksums were provided at the time of transfer, so the integrity of the data could not be verified after transfer. However, the files were transferred successfully without any errors reported by `lftp`.


Data is available here:

- [https://owl.fish.washington.edu/nightingales/C_rogercresseyi/HIFI_Caligus/](https://owl.fish.washington.edu/nightingales/C_rogercresseyi/HIFI_Caligus/)