---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Samples Submitted - Gadus macrocephalus liver tissues to Azenta for RNA-seq
date: '2023-12-18'
draft: false
engine: knitr
categories:
  - 2023
  - Gadus macrocephalus
  - Pacific cod
  - Azenta
  - RNA-seq
  - Samples Submitted
  - liver
  - spleen
  - gill
  - blood
---
Shipped box of 80 Pacific cod tissues selected by Steven (mostly liver, some blood, gills, and spleen) to Azenta overnight on dry ice for RNA-seq.

Sample sheet provided to Azenta:

| General Information |                     |                     |                | Amount of Material |             |              | Miscellaneous        |                       | QC Method Used By Customer   |                                   |                                 | Special Comments                                                                  |
|---------------------|---------------------|---------------------|----------------|--------------------|-------------|--------------|----------------------|-----------------------|------------------------------|-----------------------------------|---------------------------------|-----------------------------------------------------------------------------------|
| Sample Name*        | Sample Type*        | Species/Strain*     | Sample Buffer* | Total Amount*      | Volume (µL) | Conc (ng/µL) | Purification Method* | Biosafety Level (BSL) | Method Used for Fluorescence | Method Used for Spectrophotometry | Method Used for Electrophoresis |                                                                                   |
| 1                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 2                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 3                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 4                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 5                   | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 10                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 11                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 12                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 13                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 18                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 19                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 20                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 21                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 28                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 29                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 30                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 31                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 37                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 38                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 39                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 40                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 41                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 47                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 48                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 49                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 50                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 57                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 58                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 59                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 60                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 67                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 68                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 69                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 70                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 78                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 79                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 80                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 83                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 88                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 90                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 90-dup              | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver - accidental duplicate of 90. No need to process second tube labelled "90". |
| 91                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 92                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 97                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 98                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 99                  | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 100                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 107                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 108                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 109                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 110                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 117                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 118                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 119                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 120                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 121                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 127                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 128                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 129                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 131                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 137                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 138                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 139                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 140                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 147                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 148                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 149                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 150                 | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | liver                                                                             |
| 19-B                | Cells in RNALater   | Gadus macrocephalus | NA             | 10^8 cells         | 0           | 0            | NA                   |                       |                              |                                   |                                 | blood                                                                             |
| 20-B                | Cells in RNALater   | Gadus macrocephalus | NA             | 10^8 cells         | 0           | 0            | NA                   |                       |                              |                                   |                                 | blood                                                                             |
| 57-B                | Cells in RNALater   | Gadus macrocephalus | NA             | 10^8 cells         | 0           | 0            | NA                   |                       |                              |                                   |                                 | blood                                                                             |
| 58-B                | Cells in RNALater   | Gadus macrocephalus | NA             | 10^8 cells         | 0           | 0            | NA                   |                       |                              |                                   |                                 | blood                                                                             |
| 19-G                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | gill                                                                              |
| 20-G                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | gill                                                                              |
| 57-G                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | gill                                                                              |
| 58-G                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | gill                                                                              |
| 19-S                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | spleen                                                                            |
| 20-S                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | spleen                                                                            |
| 57-S                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | spleen                                                                            |
| 58-S                | Fresh Frozen Tissue | Gadus macrocephalus | NA             | 30mg               | 0           | 0            | NA                   |                       |                              |                                   |                                 | spleen                                                                            |