---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Daily Bits - March 2024
date: '2024-03-01'
draft: false
engine: knitr
categories: 
  - 2024
  - Daily Bits
---
## 20240326

### [`project-gigas-carryover`](../../../../project-gigas-carryover/lifestage_carryover/) (GitHub Repo)

- Organized repo.
- Added READMEs.
- Finished [qPCR notebook entry](../2024-03-01-Daily-Bits---March-2024/index.qmd).

## 20240325

### In lab

- [Ran qPCRs](../2024-03-01-Daily-Bits---March-2024/index.qmd) (Notebook) for [`project-gigas-carryover`](../../../../project-gigas-carryover/lifestage_carryover/) (GitHub Repo).

## 20240320

### Miscellaneous

- Made notebook posts for lab work from yesterday:
  - [Isolated RNA for gigas carryover project](../2024-03-19-RNA-Isolation---C.gigas-Lifestage-Carryover-Seed-and-Spat/index.qmd) (Notebook)
  - [Reverse transcribed RNA for gigas carryover project](../2024-03-19-Reverse-Transcription---C.gigas-Lifestage-Carryover-Seed-and-Spat/index.qmd) (Notebook)
  
## 20240319

### In lab

- [Isolated RNA for gigas carryover project](../2024-03-19-RNA-Isolation---C.gigas-Lifestage-Carryover-Seed-and-Spat/index.qmd) (Notebook)

- [Reverse transcribed RNA for gigas carryover project](../2024-03-19-Reverse-Transcription---C.gigas-Lifestage-Carryover-Seed-and-Spat/index.qmd) (Notebook)

## 20240318

### Miscellaneous

- Caught up on a bunch of purchasing issues/tickets.

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- [Submitted sequencing data to NCBI SRA.](../2024-03-18-SRA-Submission---CEABIGR-WGBS-and-RNA-seq/) (Notebook)

## 20240315

### Science Hour

- Chatted with Chris. Discussed approaches for writing manuscripts to try to overcome writer's block and/or motivation.

## 20240314

### Lab Meeting

- Discussed 2nd half of "Tending Sweetgrass" in "Braiding Sweetgrass"

### Miscellaneous

- Finished [notebook entry](../2024-03-12-Resazurin---C.gigas-Second-Trial/index.qmd) for 2nd resazuring trial (a lot of frustrations with ChatGPT on the computation side of things...).

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Worked on manuscript.


## 20240312

### In Lab

- Conducted 2nd [resazurin trial](../2024-03-12-Resazurin---C.gigas-Second-Trial/index.qmd) (Notebook).

## 20240311

### Miscellaneous

- Directed Azenta to post invoices to UW Workday system.

- Added initial resazurin trial [README.md](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/resazurin_trial_01/REAMDE.md) to the [`project-gigas-carryover` repo](https://github.com/RobertsLab/project-gigas-carryover).

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Began transferring sequencing data to NCBI.

## 20240308

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Reviewed manuscript with Steven.

### Miscellnaeous

- Finished up more ProCard stuff.

## 20240307

### In lab

- Ran initial [resazurin test](../2024-03-08-Resazurin---Preliminary-Respiration-Test-Using-C.gigas/index.qmd) (Notebook) on some small [_Crassostrea gigas_ (Pacific oyster)](http://en.wikipedia.org/wiki/Pacific_oyster) oysters provided by Steven.

- [Lab meeting](https://otter.ai/u/POqgTdepVCnVErcUQoH_vcS82AE?utm_source=copy_url). (Otter AI summary)

- Received chemicals for resazuring assay. Got those entered into MyChem and entered into Workday.

## 20240306

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Lengthy meeting to work extensively on manuscript - primarily documenting where code/data came from and organizing repo.

## 20240305

- Dealt with a bunch of annoying ProCard reconciliation stuff.

## 20240304

### Miscellaneous

- Read the rest of "Tending Sweetgrass" section in "Braiding Sweetgrass".

- Dealt with certificate issues for Eagle and Gannet. Despite "renewing" them, the renewal "broke" `wget` (can no longer download _without_ the use of `--no-check-certificate` flag). Remembered that I'd had this issue before and tracked down a [notebook entry](../../2022/2022-04-02-Server-Maintenance---Fix-Server-Certificate-Authentication-Issues/index.qmd) that dealt with this issue. Needed to install intermediate certificates and that resolved the problem!

## 20240301

### Miscellaneous

- Renewed Eagle server SSL certificate.

- Renewed Gannet server SSL certificate.

- Science Hour

  - Steven out of town, no show by anyone else.

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Updated README files.