#%Module1.0
proc ModulesHelp { } {
        puts stderr "\tAdds MAKER dependencies to environment."
}

module-whatis "Adds MAKER dependencies to environment."

setenv          ZOE             /gscratch/srlab/programs/snap-2013-11-29/Zoe
setenv          AUGUSTUS_CONFIG_PATH             /gscratch/srlab/programs/Augustus-3.3.2/config
prepend-path    PATH            /gscratch/srlab/programs/exonerate-2.2.0-x86_64/bin
prepend-path    PATH            /gscratch/srlab/programs/ncbi-blast-2.10.1+/bin
prepend-path    PATH            /gscratch/srlab/programs/snap-2013-11-29/snap
prepend-path    PATH            /gscratch/srlab/programs/RepeatMasker-4.1.0/RepeatMasker
