---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Resazurin - Preliminary Respiration Test Using C.gigas
date: '2024-03-08'
draft: true
engine: knitr
categories: 
  - resazurin
  - Crassostrea gigas
  - Pacific oyster
  - 2024
bibliography: references.bib
---

# INTRO

We're beginning to gather some preliminary data for a project examining the effects of "stress priming" on \_[*Crassostrea gigas* (Pacific oyster)](http://en.wikipedia.org/wiki/Pacific_oyster). GitHub repo is [here](https://github.com/RobertsLab/project-gigas-carryover). As part of that, Steven recently found out about a protocol to easily evaluate respiration in oysters using [resazurin](https://en.wikipedia.org/wiki/Resazurin) (Wikipedia). According to [@gonzález-pinzón2012], the reduction of resazurin to resorufin is almost perfectly correlated with respiration in aerobic bacteria and, thus, can be used as a proxy to measure respiration. Offhand, I have not looked at literature detailing its use with eukaryotic cells - I just glanced at the literature cited by Wikipedia. :)

Ideally, using this method would provide a quick, cheap, and wasy way for us and hatcheries to monitor respiration in live oysters, with the potential to use the method as a means to detect stress-inducing events.

