---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: qPCR - C.gigas Lifestage Carryover VIPERIN
date: '2024-12-12'
draft: true
engine: knitr
categories: 
  - 2024
  - Crassostrea gigas
  - Pacific oyster
  - SsoFast
  - CFX Connect
  - CFX96
  - project-gigas-carryover
  - VIPERIN
---
# INTRO
Continuing work with [`project-gigas-carryover` lifestage_carryover](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover) (GitHub repo) after [creating cDNA on 20241024](../2024-10-24-Reverse-Transcription---C.gigas-Lifestage-Carryover-RNA/index.qmd) (Notebook entry), it was finally time to run the qPCRs. Three primer sets [were run on 20241210](../2024-12-10-qPCRs---C.gigas-Lifestage-Carryover-GAPDH-ATP_synthase-and-cGAS/index.qmd) (Notebook entry): GAPDH, ATP synthase, and cGAS. Four primer sets were [run yesterday, 20241211](../2024-12-11-qPCRs---C.gigas-Lifestage-Carryover-citrate-synthase-DNMT1-HSP70-and-HSP90/index.qmd) (Notebook entry): citrate synthase, DNMT1, HSP70 and HSP90.

This notebook describes how the qPCRs were run and links to the various output files. It also provides a brief overview of each primer set's amplification profiles. This notebook does _not_ have any analysis. This will be performed later.

::: {.callout-note}
Due to unequal quantities of RNA used to make cDNA, information from Cq values will not provide meaningful information without normalization first.
:::


| SR ID | Primer Name          |
|-------|----------------------|
| 1829  | Cg_VIPERIN_F         |
| 1828  | Cg_VIPERIN_R         |


All samples were run in triplicate, on low-profile, white 96-well plates (USA Scientific) in a CFX Connect (Bio-Rad) or CFX96 (Bio-Rad) real-time thermalcycler. All reactions consisted of the following:

| Component                                          | Stock Concentration | Volume (uL) |
|----------------------------------------------------|---------------------|-------------|
| cDNA                                               | NA                  | 1           |
| SsoAdvanced Universal SYBR Green Supermix (BioRad) | 2x                  | 10          |
| P<sub>F</sub>                                      | 10uM                | 0.5         |
| P<sub>R</sub>                                      | 10uM                | 0.5         |
| H<sub>2</sub>O                                     | NA                  | 8           |
| TOTAL                                              |                     | 20          |

Master mixes were distributed across 2.5 plates for each primer set. No template controls (NTC) were loaded on on just one of the three plates (plate #3 in all instances).

For cycling parameters, plate layouts, etc. see the [RESULTS](#results) section below.


# RESULTS


## Summary

- `VIPERIN`: Amplification and melt plots look good. No amplification in NTCs.

## Files

::: {.callout-tip}

- `*.pdf`: qPCR Reports. Contains plate layouts, cycling params, amp/melt plots, etc.

- `*Amplification-Results_SYBR.csv`: Raw fluorescence data.

- `*Cq-Results.csv`: Cycle quantity (Cq) data.

- `*.pcrd`: Source qPCR data file. Requires CFX Maestro (Bio-Rad) software to open.

All files linked below are from commit `e816421`.

:::