---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: SRA Submission - R.philippinarum Egg RNA-seq Data
date: '2025-07-07'
draft: false
engine: knitr
categories: 
  - "2025"
  - "Ruditapes philippinarum"
  - "Manila clam"
  - "RNA-seq"
  - "SRA submission"
  - "NCBI"
  - "PRJNA1289209"
---
[Mac asked me to submit a set of files to NCBI Short Read Archive](https://github.com/RobertsLab/resources/issues/2223) (SRA; GitHub Issue).

Files were released as the following BioProject:

[PRJNA1289209](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1289209)

![Screenshot of the NCBI BioProject page for PRJNA1289209 titled Parental priming for ocean acidification resilience in cultured Manila clams mechanistic insights gained through transcriptome analysis. The page displays project details including accession number PRJNA1289209, data type as raw sequence reads, scope as multispecies, and submission by University of Washington with a registration date of 9-Jul-2025. SRA Data Details table lists data volume as 330 Gbases and 0.11 Tbytes.](./20250707-rphi-sra-bioproject-screencap.png){fig-alt="Screenshot of the NCBI BioProject page for PRJNA1289209 titled Parental priming for ocean acidification resilience in cultured Manila clams mechanistic insights gained through transcriptome analysis. The page displays project details including accession number PRJNA1289209, data type as raw sequence reads, scope as multispecies, and submission by University of Washington with a registration date of 9-Jul-2025. SRA Data Details table lists data volume as 330 Gbases and 0.11 Tbytes."}