---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Homogenization - SORMI June 2026 M.gigas Ctenidia from Families 5 and 7 for Citrate Synthase Assay
date: '2026-08-11'
draft: false
engine: knitr
categories: 
  - "2026"
  - "SORMI"
  - "Magallana gigas"
  - "ctenidia"
  - "Pacific oyster"
  - "Crassostrea gigas"
  - "citrate synthase"
  - "homogenization"
---
# INTRO

Families 5 & 7 from the [June 2026 SORMI experiment](https://github.com/RobertsLab/sormi-assay-development/tree/main/sampling-event-metadata/june-2026) (GitHub repo) were selected for citrate synthase assay (selection by Steven). Ctenidia samples from these families were homogenized in preparation for the Citrate Synthase Assay Kit (ABCAM; cat: ab239712).

# MATERIALS & METHODS

Eight ctenidia samples (1-8) from each treatment (ambient and 36°C) in Families 5 and 7 were selected. Samples were stored on dried ice until homogenization. Pieces of ctenidia were broken off and weighed to the nearest 0.1 mg. Tissue was transferred to 1.5mL Safe-Lock tubes (Eppendorf) containing 350 µL of Assay Buffer 7 and ~100µL of 0.5mm glass beads (Research Products International). Samples were homogenized in a pre-/cooled (dry ice) Bullet Blender 5E Gold+ using the 1.5mL adapters. Homogenization was performed for 10 minutes at Speed 12. After homogenization, samples were stored at -80°C until further processing.


::: {.callout-note}
A homogenization volume of 350 µL (instead of the manufacturer's recommended 100 µL) was used based off of prior work in our lab with this kit, [performed by Matt George](https://doi.org/10.1111/gcb.16880) (link to the paper - requires institutional access).

:::

Below is a list of the samples and the weights of ctenidia used for homogenization:


| Sample         | Weight(mg) |
|----------------|------------|
| F05_01_ambient | 10.1       |
| F05_02_ambient | 17.5       |
| F05_03_ambient | 22.3       |
| F05_04_ambient | 14         |
| F05_05_ambient | 11.5       |
| F05_06_ambient | 30.2       |
| F05_07_ambient | 25.8       |
| F05_08_ambient | 30.6       |
| F05_01_36C     | 12.8       |
| F05_02_36C     | 6.2        |
| F05_03_36C     | 10.3       |
| F05_04_36C     | 12.8       |
| F05_05_36C     | 22.7       |
| F05_06_36C     | 18.4       |
| F05_07_36C     | 11.3       |
| F05_08_36C     | 13.8       |
| F07_01_ambient | 7.3        |
| F07_02_ambient | 19.4       |
| F07_03_ambient | 19.7       |
| F07_04_ambient | 10.7       |
| F07_05_ambient | 8.3        |
| F07_06_ambient | 12.8       |
| F07_07_ambient | 20.6       |
| F07_08_ambient | 10.9       |
| F07_01_36C     | 9          |
| F07_02_36C     | 9.5        |
| F07_03_36C     | 18.3       |
| F07_04_36C     | 16.9       |
| F07_05_36C     | 10.5       |
| F07_06_36C     | 9.7        |
| F07_07_36C     | 12.5       |
| F07_08_36C     | 9.1        |


- [20240811-mgig-Fams5_and_7-citrate_synthase-tissue-weights](https://docs.google.com/spreadsheets/d/1klABW56Tm_VoGIiwarxhgLH82f3gh_SGf8PDxynTArM/edit?usp=sharing) (Google Sheet)