---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Computer Management - Replace Failing HDDs on Gannet Expansion Unit (Synology RX1217)
date: '2023-12-10'
draft: false
engine: knitr
categories: 
  - HDD
  - Synology
  - Gannet
  - Seagate
  - RX1217
  - Computer Management
---
Started receiving alerts from Gannet (Synology RS3618XS) that three drives were failing and in a "critical state" in the expansion unit (Rynology RX1217) in late November 2023. Ordered three replacement drives (Seagate Iron Wolf Pro; 16TB) and they finally arrived. I swapped two of the drives, following the Synology Storage Manager wizard, but had to wait for the drives to go through various checks before I could install the third (will do this this weekend).

However, when trying to investigate the drive failures using Seagate's SeaTools, both drives passed the "generic short test". However, neither drive could complete the "generic long test." No errors were generated, just that the "generic long test" failed. When I registered the drives with Seagate, Seagate indicated that the drives' warranties ended on 11/27/2023! These were brand new drives purchased in July 2023! The warranty should be significantly longer than 5 months.

Will reach out to the vendor via Amazon to see what can be done about this...