---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Daily Bits - December 2023
date: '2023-12-01'
draft: false
engine: knitr
categories: 
  - Daily Bits
---

## 20231219

- Read Ch.3 of "Race After Technology: The New Jim Code"

- Helped get Lindasy Alma set up for qPCRs and usage of the PCR Workstation in FTR 213.

## 20231218

### In lab

- [Shipped Pacific cod tissues to Azenta for RNA-seq](https://robertslab.github.io/sams-notebook/posts/2023/2023-12-18-Samples-Submitted---Gadus-macrocephalus-liver-tissues-to-Azenta-for-RNA-seq/) (notebook).

- Tested out some broken URL GitHub action modifications to deal with my notebook.

## 20231215

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Worked on manuscript

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Spent a bit more time looking into Ballgown exon counts and comparing with GFF.

## 20231214

### Hackweek

- Helped with Hisat2/Stringtie stuff.

## 20231213

### Hackweek

- Worked on broken URLs in notebook and lab website.

- Helped with Grace Kallisto stuff.

## 20231211

### Hackweek

- Worked on broken URLs in notebook and lab website.

## 20231206

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Completed most of invstigation into exon count issues.

### DEI

- Read Ch.2 of "Race After Technology"


## 20231205

[CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

  - Started to investigate weird exon count issues identified last week.

[DuMOAR](https://github.com/laurahspencer/DuMOAR) (GitHub repo)

- It was decided to have everyone begin writing their methods in the manuscript.

## 20231204

[Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

 - Updated multiple README files

## 20231201

-[Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo) Meeting

  - Revisit trimming.
  
    - Contact Azenta about trimming params.

- Science Hour

  - Chatted with Kathleen about basics of NGS trimming.