---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Genome Assembly - S.namaycush Lean Ecotype with PacBio HiFi Reads Using Flye
date: '2026-03-26'
draft: false
engine: knitr
categories: 
  - "2026"
  - "Genome Assembly"
  - "PacBio"
  - "HiFi Reads"
  - "Flye"
  - "Salvelinus namaycush"
  - "Lake Trout"
  - "Lean"
---
# INTRO

As part of [`project-lake-trout`](https://github.com/RobertsLab/project-lake-trout) (GitHub repo), Steven [asked that I assemble the genome of a lean ecotype of lake trout](https://github.com/RobertsLab/resources/issues/2409) (GitHub Issue), *Salvelinus namaycush*, using PacBio HiFi reads. I opted to use Flye for the assembly, as we'd previously used it for [_Chionoecetes bairdi_ (Tanner crab)](http://en.wikipedia.org/wiki/Chionoecetes_bairdi) (Wikipedia), and it performed well. The assembly process was straightforward and quick.

I performed the assembly on Hyak (Klone), UW's high-performance computing cluster. I used our Apptainer (Singularity) container to run the job (`srlab-R4.4-bioinformatics-container-fca8ae6.sif`), which includes Flye version 2.9.6.

Below is the rendered markdown from `13.1-genome-assembly-lean.Rmd`. The run took ~7 days.

# PRIMARY OUTPUTS

- FastA (3.9GB): https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-genome-assembly-lean/snam-lean-pb-flye-assembly.fasta

- MD5: https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-genome-assembly-lean/snam-lean-pb-flye-assembly.fasta.md5

- FastA index: https://gannet.fish.washington.edu/gitrepos/project-lake-trout/output/13.1-genome-assembly-lean/snam-lean-pb-flye-assembly.fasta.fai

Once I've also assembled this genome using [hifiasm](https://github.com/CHPGenetics/hifiasm), I'll compare the two assemblies using [QUAST](https://github.com/ablab/quast), which will provide a more comprehensive set of assembly statistics and metrics.


---

13.1-genome-assembly-lean
================
Sam White
2026-03-26

# 1 BACKGROUND

Use [Flye](https://github.com/mikolmogorov/Flye)(GitHub) (Kolmogorov et
al. 2019) to assemble PacBio reads for *S.namaycush* `lean` ecotype.

# 2 SETUP

## 2.1 Libraries

``` r
library(knitr)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.4     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(reticulate)

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
    eval = FALSE,        # Evaluate code chunks
    results = "hold",   # Hold outputs and show them after the full code chunk
  warning = FALSE,     # Hide warnings
        collapse = FALSE,    # Keep code and output in separate blocks
        warning = FALSE,     # Hide warnings
        message = FALSE,     # Hide messages
        comment = "##"      # Prefix output lines with '##' so output is visually distinct
)
```

## 2.2 Set R variables

``` r
# OUTPUT DIRECTORY
data_dir <- "../data/pacbio-lean"
output_dir <- "../output/13.1-genome-assembly-lean"

#OUTPUT FILE(S)
prefix <- "snam-lean-pb-flye"


# CONDA
conda_env_name <- c("/srlab/programs/miniforge3-24.7.1-0/envs/flye-2.9.6-env")
conda_path <- c("/srlab/programs/miniforge3-24.7.1-0/bin/conda")

# SETTINGS
genome_size <- "2.3g"
threads <- "32"


# Export these as environment variables for bash chunks.
Sys.setenv(
  data_dir = data_dir,
  genome_size = genome_size,
  output_dir = output_dir,
  prefix = prefix,
  threads = threads
)
```

## 2.3 Load [Flye](https://github.com/mikolmogorov/Flye) conda environment

If this is successful, the first line of output should show that the
Python being used is the one in your
[Flye](https://github.com/mikolmogorov/Flye) conda environment path.

E.g.

`python:         /srlab/programs/miniforge3-24.7.1-0/envs/flye-2.9.6-env/bin/python`

``` r
use_condaenv(condaenv = conda_env_name, conda = conda_path)
py_config()
```

    ## python:         /srlab/programs/miniforge3-24.7.1-0/envs/flye-2.9.6-env/bin/python
    ## libpython:      /srlab/programs/miniforge3-24.7.1-0/envs/flye-2.9.6-env/lib/libpython3.12.so
    ## pythonhome:     /srlab/programs/miniforge3-24.7.1-0/envs/flye-2.9.6-env:/srlab/programs/miniforge3-24.7.1-0/envs/flye-2.9.6-env
    ## version:        3.12.13 | packaged by conda-forge | (main, Mar  5 2026, 16:50:00) [GCC 14.3.0]
    ## numpy:           [NOT FOUND]
    ## 
    ## NOTE: Python version was forced by use_python() function

``` bash
# Make output directory, if it doesn't exist
mkdir --parents "${output_dir}"

# Create an array of .fastq.gz files
fastqs=(${data_dir}/*.fastq.gz)

# Print the result (optional, for verification)
## newline-delimited format
echo "List of FastQs used for assembly:"

printf "%s\n" "${fastqs[@]}" \
| tee "${output_dir}/input_fastqs.txt"

# Run Flye assembly
flye \
--pacbio-hifi "${fastqs[@]}" \
--genome-size "${genome_size}" \
--out-dir "${output_dir}" \
--threads "${threads}" \
> "${output_dir}"/pb-lean-assembly.log 2>&1
```

# 3 OUTPUTS

## 3.1 List files

``` bash
ls -ltrh "${output_dir}"
```

    ## total 8.2G
    ## -rw-r--r-- 1 samwhite all  326 Mar 26 11:02 input_fastqs.txt
    ## drwxr-xr-x 2 samwhite all  512 Mar 30 07:44 00-assembly
    ## drwxr-xr-x 2 samwhite all 8.0K Mar 30 12:12 10-consensus
    ## drwxr-xr-x 2 samwhite all  512 Mar 31 08:22 20-repeat
    ## drwxr-xr-x 2 samwhite all  512 Mar 31 08:33 30-contigger
    ## drwxr-xr-x 2 samwhite all 8.0K Mar 31 17:25 40-polishing
    ## -rw-r--r-- 1 samwhite all   92 Mar 31 17:25 params.json
    ## -rw-r--r-- 1 samwhite all  53M Mar 31 17:25 assembly_graph.gv
    ## -rw-r--r-- 1 samwhite all 4.0G Mar 31 17:25 assembly_graph.gfa
    ## -rw-r--r-- 1 samwhite all 3.9G Mar 31 17:25 assembly.fasta
    ## -rw-r--r-- 1 samwhite all 4.8M Mar 31 17:25 assembly_info.txt
    ## -rw-r--r-- 1 samwhite all 3.2K Mar 31 17:25 pb-lean-assembly.log
    ## -rw-r--r-- 1 samwhite all 338M Mar 31 17:25 flye.log
    ## -rw-r--r-- 1 samwhite all 3.9M Apr  2 10:05 assembly.fasta.fai

## 3.2 Rename files

Files have generic “assembly\_\*” naming.

Renaming to reflect specific species-ecotype-data-assembly_method.

``` bash
cd "${output_dir}"

for file in assembly*
do
  mv "${file}" ${prefix}-${file}
done
```

## 3.3 Create FastA Index

``` bash
cd "${output_dir}"

samtools faidx ${prefix}-assembly.fasta
```

## 3.4 Create checksums

``` bash
cd "${output_dir}"

for file in ${prefix}*
do
  md5sum "${file}" \
  | tee "${file}".md5
done
```

    ## ac7c2af6c32834f86954cfb9893c4c50  snam-lean-pb-flye-assembly.fasta
    ## 242ea029692207d1c7df0b7e842fd58f  snam-lean-pb-flye-assembly.fasta.fai
    ## 35f1973b873fd7498ebeeecdb7eecd2e  snam-lean-pb-flye-assembly_graph.gfa
    ## d4f6a3a41846f6285d0290c7a41ed1f7  snam-lean-pb-flye-assembly_graph.gv
    ## e1224b9a628253fd8cee1d39517343ef  snam-lean-pb-flye-assembly_info.txt

## 3.5 Assembly stats

``` bash
cd "${output_dir}"

tail flye.log
```

    ## [2026-03-31 17:25:45] root: INFO: Assembly statistics:
    ## 
    ##  Total length:   4046369763
    ##  Fragments:  112562
    ##  Fragments N50:  74514
    ##  Largest frg:    2170611
    ##  Scaffolds:  0
    ##  Mean coverage:  15
    ## 
    ## [2026-03-31 17:25:45] root: INFO: Final assembly: /mmfs1/gscratch/scrubbed/samwhite/gitrepos/RobertsLab/project-lake-trout/output/13.1-genome-assembly-lean/assembly.fasta

<div id="refs" class="references csl-bib-body hanging-indent">

<div id="ref-kolmogorov2019" class="csl-entry">

Kolmogorov, Mikhail, Jeffrey Yuan, Yu Lin, and Pavel A. Pevzner. 2019.
“Assembly of Long, Error-Prone Reads Using Repeat Graphs.” *Nature
Biotechnology* 37 (5): 540–46.
<https://doi.org/10.1038/s41587-019-0072-8>.

</div>

</div>