---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: DNA Isolation and Quantification - Pacific Cod Blood
date: '2024-07-18'
draft: false
engine: knitr
categories: 
  - "2024"
  - "Pacific cod"
  - "Gadus macrocephalus"
  - "blood"
  - "DNA isolation"
  - "DNA quantification"
  - "Qubit"
  - "DNA BR assay"
---
# INTRO

Steven asked that I [isolate gDNA from a Pacific cod blood samples](https://github.com/RobertsLab/resources/issues/1922) (GitHub Issue). Laura Spencer [identified a set of samples](https://github.com/RobertsLab/resources/issues/1922#issuecomment-2189879056) (GitHub Issue). Below is the list of samples I isolated DNA from:

- `4B`
- `11B`
- `30B`
- `39`
- `47`
- `70`

::: {.callout-important}
The following blood samples were _not_ located in the freezer boxes:

- `12B`
- `18B`
- `50B`
- `59B`

:::

# METHODS

## DNA Isolations

DNA was isolated using the Quick-DNA Miniprep Kit (ZymoResearch), according to the manufacturer's protocol - including the recommended addition of beta-mercaptoethanol to the buffer. Pacific cod blood had been collected and frozen/stored at -80<sup>o</sup>C, with no preservatives/anticoagulants (e.g. heparin). Blood was thawed on ice and briefly centrifuged (20s @ 10,000g) to collect blood at bottom of tubes. Since the volumes of all blood samples was < 50uL, I added 200uL of g-DNA Lysis Buffer to each tube (per the manufacturer's protocol for blood isolations). DNA was eventually eluted with 50uL of Elution Buffer.

## DNA Quantification

Subsequently, DNA was quantified using the 1x dsDNA Broad Range Qubit Assay (ThermoFisher). One microliter of sample was combined with 199uL of the dye/buffer mix and measured on a Qubit 3.0.


DNA was stored in the same boxes and positions in which the blood had been stored in the -80<sup>o</sup>C freezer.


# RESULTS

## Qubit data

- [20240718-gmac-qubit-DNA.br-blood.csv](./20240718-gmac-qubit-DNA.br-blood.csv)

| sample_ID | Original sample conc.(ng/uL) |
|-----------|------------------------------|
| 4B        | 9.36                         |
| 11B       | 212                          |
| 30B       | 1100                         |
| 39B       | 506                          |
| 47B       | 3.3                          |
| 70B       | 830                          |
