---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Software Installation - Shiny App Server on Raven
date: '2025-11-06'
draft: false
engine: knitr
categories: 
  - "2025"
  - "shiny"
  - "raven"
---
# INTRO

Steven [asked that I setup a Shiny App server on Raven](https://github.com/RobertsLab/resources/issues/2371) (GitHub Issue).

# MATERIALS & METHODS

Followed this guide:

https://fortune9.netlify.app/2023/06/30/tutorial-how-to-install-shiny-server-on-ubuntu-22-04/

Made some deviations, as that guide is for an older version of Ubuntu than what we have currently have installed on Raven (Ubuntu 24.04.3 LTS).

## Install system dependencies
```bash
sudo apt -y install libssl-dev libxml2-dev libmariadb-dev-compat libmariadb-dev build-essential libcurl4-gnutls-dev
```
## Install Shiny
```r
sudo su - -c "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""
```

## Get and install current version of Shiny Server for Ubuntu

```bash
wget https://download3.rstudio.org/ubuntu-20.04/x86_64/shiny-server-1.5.23.1030-amd64.deb
sudo gdebi shiny-server-1.5.23.1030-amd64.deb
```

# RESULTS

Server is currently set up and running. Can be accessed here:

http://raven.fish.washington.edu:3838/

::: {.callout-important}
To access off-campus, you'll need to have the Husky OnNet VPN active.
:::


Then, you'd want to make a directory for your shiny apps here:

`/srv/shiny-server/`

E.g. `/srv/shiny-server/sr320-amazing-shiny-apps/`

Then, put your shiny app stuff in there and access at:

http://raven.fish.washington.edu:3838/sr320-amazing-shiny-apps

That address would provide a directory listing of your different shiny apps.

Alternatively, you could create single, dedicated directories for each different app you want.

- `/srv/shiny-server/sr320-shiny_app-01`
- `/srv/shiny-server/sr320-shiny_app-02`
- `/srv/shiny-server/sr320-shiny_app-03`

Each would be accessed like so:

- http://raven.fish.washington.edu:3838/sr320-shiny_app-01
- http://raven.fish.washington.edu:3838/sr320-shiny_app-02
- http://raven.fish.washington.edu:3838/sr320-shiny_app-03