---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
date: 2017-11-14 19:05:37+00:00
layout: post
slug: genome-assembly-olympia-oyster-illumina-pacbio-using-pb-jelly-wbgi-scaffold-assembly
title: Genome Assembly -  Olympia Oyster Illumina & PacBio Using PB Jelly w/BGI Scaffold
  Assembly
categories:
  - "2017"
  - "Olympia Oyster Genome Sequencing"
  - "assembly"
  - "BGI"
  - "Illumina"
  - "jupyter notebook"
  - "olympia oyster"
  - "Ostrea lurida"
  - "PacBio"
  - "PB Jelly"
---

[Yesterday, I ran PB Jelly using Sean's Platanus assembly](../2017-11-14-genome-assembly-olympia-oyster-illumina-pacbio-using-pb-jelly-wplatanus-assembly/index.qmd), but that didn't produce an assembly because [PB Jelly](https://sourceforge.net/p/pb-jelly/wiki/Home/) was expecting gaps in the Illumina reference assembly (i.e. scaffolds, not contigs).

Re-ran this using the [BGI Illumina scaffolds FASTA](https://owl.fish.washington.edu/O_lurida_genome_assemblies_BGI/20161201/cdts-hk.genomics.cn/Ostrea_lurida/Ostrea_lurida.fa).





  * [PB Jelly Documentation](https://sourceforge.net/p/pb-jelly/wiki/Home/)



Here's a brief rundown of how this was run:



  * Default PB Jelly settings (including default settings for blasr).


  * Illumina reference FASTA: [BGI Illumina scaffolds FASTA](https://owl.fish.washington.edu/O_lurida_genome_assemblies_BGI/20161201/cdts-hk.genomics.cn/Ostrea_lurida/Ostrea_lurida.fa)


  * PacBio reads for mapping


  * [Protocol.xml file needed for PB Jelly to run](https://owl.fish.washington.edu/Athaliana/20171114_oly_pbjelly/Protocol.xml)



See the Jupyter Notebook for full details of run (see Results section below).



#### Results:



Output folder: [https://owl.fish.washington.edu/Athaliana/20171114_oly_pbjelly/](http://owl.fish.washington.edu/Athaliana/20171114_oly_pbjelly/)

Output FASTA file: [https://owl.fish.washington.edu/Athaliana/20171114_oly_pbjelly/jelly.out.fasta](http://owl.fish.washington.edu/Athaliana/20171114_oly_pbjelly/jelly.out.fasta)

OK! This seems to have worked (and it was quick, like less than an hour!), as it actually produced a FASTA file! Will run QUAST with this and some assemblies to compare assembly stats. Have added this assembly to our [Olympia oyster genome assemblies table](https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/Genome-Assemblies).

Jupyter Notebook (GitHub): [20171114_emu_pbjelly_BGI_scaffold.ipynb](https://github.com/sr320/LabDocs/blob/master/jupyter_nbs/sam/20171114_emu_pbjelly_BGI_scaffold.ipynb)
