---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: RNA Quantification - C.gigas Lifestage Carryover RNA Samples Using Qubit High Sensitivity RNA Assay
date: '2025-05-13'
draft: false
engine: knitr
categories: 
  - "2025"
  - "Crassostrea gigas"
  - "Pacific oyster"
  - "RNA quantification"
  - "Qubit"
  - "Magallana gigas"
---
# INTRO

I was [asked to isolate RNA from a list of 60 samples](https://github.com/RobertsLab/resources/issues/2062) (GitHub Issue) from a number of [_Crassostrea gigas_ (Pacific oyster)](http://en.wikipedia.org/wiki/Pacific_oyster) spat and seed that had been collected as part of the [`project-gigas-carryover`](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover) (GitHub repo). Yesterday, I [homogenized samples in TriZol](../2025-05-12-Sample-Homogenization---C.gigas-Lifestage-Carryover-Samples-Using-TriZol-and-Bullet-Blender/index.qmd) (Notebook entry), as well as [isolated RNA from most of them](../2025-05-12-RNA-Isolation---C.gigas-Lifestage-Carryover-Samples-Using-Direct-zol-RNA-MiniPrep-Plus-Kit/index.qmd) (Notebook entry). I isolated RNA [from the remaining 12 samples earlier today](../2025-05-13-RNA-Isolation---C.gigas-Lifestage-Carryover-Samples-Using-Direct-zol-RNA-MiniPrep-Plus-Kit/index.qmd) (Notebook entry).

Next on deck - quantification!

# MATERIALS & METHODS

RNA was quantified with the Roberts Lab Qubit 3.0 fluorometer (Invitrogen). Samples were quantified with the Qubit RNA High Sensitivity (HS) assay (Invitrogen). 1uL of sample was used for the assay(s).

All RNA samples were stored in the -80<sup>o</sup>C boxes from where the original tissues came from.

# RESULTS

## Raw Qubit Data

Qubit (Google Sheets):

- [20250513-cgig-qubit-RNA.hs-carryover-spat-seed](https://docs.google.com/spreadsheets/d/1geAGuu2BAXwgg3-t6sxBMMITBC9yYlK3OFRfqnjzE2w/edit?usp=sharing)

This info has been entered into the canonical CSV for these samples:

- [`20241230_rna_extractions.csv`](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/sampling_metadata/20241230_rna_extractions.csv) (GitHub)


## RNA Yields

| sample_ID | qubit_concentration (ng/uL) | dilution_factor | final_concentration | volume (uL) | total (ng) |
|-----------|-----------------------------|-----------------|---------------------|-------------|------------|
| 1         | 0                           | 1               | 0                   | 40          | 0          |
| 6         | 0                           | 1               | 0                   | 40          | 0          |
| 9         | 0                           | 1               | 0                   | 40          | 0          |
| 11        | 0                           | 1               | 0                   | 40          | 0          |
| 12        | 6.6                         | 1               | 6.6                 | 40          | 264        |
| 13*       | 0                           | 1               | 0                   | 40          | 0          |
| 14        | 5                           | 1               | 5                   | 40          | 200        |
| 15        | 55.4                        | 10              | 554                 | 40          | 22160      |
| 18        | 38.4                        | 10              | 384                 | 40          | 15360      |
| 19        | 23.6                        | 1               | 23.6                | 40          | 944        |
| 24        | 20.4                        | 1               | 20.4                | 40          | 816        |
| 25        | 6.72                        | 1               | 6.72                | 40          | 268.8      |
| 27        | 0                           | 1               | 0                   | 40          | 0          |
| 28        | 0                           | 1               | 0                   | 40          | 0          |
| 29        | 4.6                         | 1               | 4.6                 | 40          | 184        |
| 30        | 0                           | 1               | 0                   | 40          | 0          |
| 34        | 0                           | 1               | 0                   | 40          | 0          |
| 36        | 0                           | 1               | 0                   | 40          | 0          |
| 38        | 0                           | 1               | 0                   | 40          | 0          |
| 39        | 16.1                        | 1               | 16.1                | 40          | 644        |
| 40        | 8.64                        | 1               | 8.64                | 40          | 345.6      |
| 42        | 0                           | 1               | 0                   | 40          | 0          |
| 43        | 85.2                        | 1               | 85.2                | 40          | 3408       |
| 46        | 0                           | 1               | 0                   | 40          | 0          |
| 47        | 0                           | 1               | 0                   | 40          | 0          |
| 48        | 0                           | 1               | 0                   | 40          | 0          |
| 49        | 172                         | 1               | 172                 | 40          | 6880       |
| 50        | 0                           | 1               | 0                   | 40          | 0          |
| 52        | 0                           | 1               | 0                   | 40          | 0          |
| 53        | 200                         | 1               | 200                 | 40          | 8000       |
| 55        | 0                           | 1               | 0                   | 40          | 0          |
| 57        | 0                           | 1               | 0                   | 40          | 0          |
| 59        | 60                          | 1               | 60                  | 40          | 2400       |
| 60        | 162                         | 1               | 162                 | 40          | 6480       |
| 61        | 0                           | 1               | 0                   | 40          | 0          |
| 62        | 82.4                        | 1               | 82.4                | 40          | 3296       |
| 63        | 5.36                        | 1               | 5.36                | 40          | 214.4      |
| 64        | 0                           | 1               | 0                   | 40          | 0          |
| 65        | 0                           | 1               | 0                   | 40          | 0          |
| 66        | 27.2                        | 10              | 272                 | 40          | 10880      |
| 69        | 15.9                        | 1               | 15.9                | 40          | 636        |
| 71        | 77                          | 1               | 77                  | 40          | 3080       |
| 72        | 0                           | 1               | 0                   | 40          | 0          |
| 73        | 32.2                        | 1               | 32.2                | 40          | 1288       |
| 74        | 0                           | 1               | 0                   | 40          | 0          |
| 75        | 31.4                        | 10              | 314                 | 40          | 12560      |
| 76        | 0                           | 1               | 0                   | 40          | 0          |
| 77        | 0                           | 1               | 0                   | 40          | 0          |
| 78        | 0                           | 1               | 0                   | 40          | 0          |
| 79        | 14.9                        | 1               | 14.9                | 40          | 596        |
| 81        | 112                         | 1               | 112                 | 40          | 4480       |
| 83        | 0                           | 1               | 0                   | 40          | 0          |
| 86        | 0                           | 1               | 0                   | 40          | 0          |
| 88        | 0                           | 1               | 0                   | 40          | 0          |
| 89        | 6.42                        | 1               | 6.42                | 40          | 256.8      |
| 92        | 0                           | 1               | 0                   | 40          | 0          |
| 93        | 0                           | 1               | 0                   | 40          | 0          |
| 96        | 0                           | 1               | 0                   | 40          | 0          |
| 97        | 0                           | 1               | 0                   | 40          | 0          |
| 98        | 0                           | 1               | 0                   | 40          | 0          |

: RNA yields taking into account samples which needed to be diluted and re-measured. {#tbl-RNA_yields .striped .hover}

## Lifestage RNA Concentrations

| tube_ID | tag_tank       | lifestage | conditioning_treatment | acute_treatment | rna-concentration(ng/uL) |
|---------|----------------|-----------|------------------------|-----------------|--------------------------|
| 1       | left-juvenile  | juvenile  | treated                | ambient         | 0                        |
| 12      | right-juvenile | juvenile  | control                | high            | 6.6                      |
| 18      | right-juvenile | juvenile  | control                | ambient         | 38.4                     |
| 28      | left-juvenile  | juvenile  | treated                | high            | 0                        |
| 34      | left-juvenile  | juvenile  | treated                | ambient         | 0                        |
| 39      | right-juvenile | juvenile  | control                | high            | 16.1                     |
| 43      | right-juvenile | juvenile  | control                | high            | 85.2                     |
| 49      | right-juvenile | juvenile  | control                | high            | 172                      |
| 53      | left-juvenile  | juvenile  | treated                | high            | 200                      |
| 57      | right-juvenile | juvenile  | control                | ambient         | 0                        |
| 61      | left-juvenile  | juvenile  | treated                | high            | 0                        |
| 64      | left-juvenile  | juvenile  | treated                | ambient         | 0                        |
| 65      | right-juvenile | juvenile  | control                | ambient         | 0                        |
| 71      | right-juvenile | juvenile  | control                | high            | 77                       |
| 73      | left-juvenile  | juvenile  | treated                | high            | 32.2                     |
| 75      | right-juvenile | juvenile  | control                | ambient         | 31.4                     |
| 79      | right-juvenile | juvenile  | control                | ambient         | 14.9                     |
| 81      | left-juvenile  | juvenile  | treated                | high            | 112                      |
| 83      | left-juvenile  | juvenile  | treated                | ambient         | 0                        |
| 98      | left-juvenile  | juvenile  | treated                | ambient         | 0                        |
| 14      | left-seed      | seed      | treated                | ambient         | 5                        |
| 15      | left-seed      | seed      | treated                | high            | 55.4                     |
| 19      | left-seed      | seed      | treated                | high            | 23.6                     |
| 24      | left-seed      | seed      | treated                | high            | 20.4                     |
| 29      | right-seed     | seed      | control                | ambient         | 4.6                      |
| 40      | right-seed     | seed      | control                | ambient         | 8.64                     |
| 42      | right-seed     | seed      | control                | high            | 0                        |
| 48      | left-seed      | seed      | treated                | ambient         | 0                        |
| 55      | right-seed     | seed      | control                | ambient         | 0                        |
| 59      | right-seed     | seed      | control                | high            | 60                       |
| 60      | right-seed     | seed      | control                | high            | 162                      |
| 62      | right-seed     | seed      | control                | high            | 82.4                     |
| 63      | right-seed     | seed      | control                | ambient         | 5.36                     |
| 66      | left-seed      | seed      | treated                | ambient         | 27.2                     |
| 69      | right-seed     | seed      | control                | ambient         | 15.9                     |
| 72      | left-seed      | seed      | treated                | ambient         | 0                        |
| 86      | right-seed     | seed      | control                | high            | 0                        |
| 88      | left-seed      | seed      | treated                | high            | 0                        |
| 89      | left-seed      | seed      | treated                | ambient         | 6.42                     |
| 92      | left-seed      | seed      | treated                | high            | 0                        |
| 6       | left-spat      | spat      | treated                | high            | 0                        |
| 9       | left-spat      | spat      | treated                | ambient         | 0                        |
| 11      | right-spat     | spat      | control                | ambient         | 0                        |
| 25      | left-spat      | spat      | treated                | high            | 6.72                     |
| 27      | right-spat     | spat      | control                | high            | 0                        |
| 30      | right-spat     | spat      | control                | ambient         | 0                        |
| 36      | right-spat     | spat      | control                | ambient         | 0                        |
| 38      | left-spat      | spat      | treated                | ambient         | 0                        |
| 46      | left-spat      | spat      | treated                | ambient         | 0                        |
| 47      | left-spat      | spat      | treated                | ambient         | 0                        |
| 50      | left-spat      | spat      | treated                | high            | 0                        |
| 52      | right-spat     | spat      | control                | ambient         | 0                        |
| 74      | right-spat     | spat      | control                | high            | 0                        |
| 76      | left-spat      | spat      | treated                | high            | 0                        |
| 77      | right-spat     | spat      | control                | ambient         | 0                        |
| 78      | left-spat      | spat      | treated                | high            | 0                        |
| 93      | right-spat     | spat      | control                | high            | 0                        |
| 96      | right-spat     | spat      | control                | high            | 0                        |
| 97      | right-spat     | spat      | control                | high            | 0                        |
| 13*     | left-spat      | spat      | treated                | ambient         | 0                        |

: RNA concentrations sorted by lifestage {#tbl-lifestage_RNA .striped .hover}


# SUMMARY

Well, overall, these results are not good. A surprisingly large number of samples failed to yield _any_ RNA. And, to make matters worse, when we [look at the results by lifestage](#lifestage-rna-concentrations), we see only a _single_ spat sample yielded any RNA!

I'm having a difficult time coming up with any explanations for the overall poor results. There was nothing during the RNA isolation process to suggest that there might be any issues with any of the samples (e.g. no clogged columns). Although, reviewing[previous isolations also did not work particularly well](../../2024/2024-03-19-RNA-Isolation---C.gigas-Lifestage-Carryover-Seed-and-Spat/index.qmd) (Notebook entry), as well as others [which performed perfectly](../../2024/2024-06-24-RNA-Isolation-and-Quantification---C.gigas-Lifestage-Carryover-Seed-Juvenile-and-Adult/index.qmd) (Notebook entry), I suspect I fell into the trap of not diluting the homogenized samples with sufficient TriZol afterwards - which is the primary difference between the [20240319 isolations](../../2024/2024-03-19-RNA-Isolation---C.gigas-Lifestage-Carryover-Seed-and-Spat/index.qmd) and the [20240624 isolations](../../2024/2024-06-24-RNA-Isolation-and-Quantification---C.gigas-Lifestage-Carryover-Seed-Juvenile-and-Adult/index.qmd) (Notebook entry).