---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Reverse Transcription - C.gigas Lifestage Carryover RNA
date: '2025-05-16'
draft: false
engine: knitr
categories: 
  - "2025"
  - "reverse transcription"
  - "cDNA"
  - "GoScript"
  - "Crassostrea gigas"
  - "Pacific oyster"
  - "RNA"
  - "project-gigas-carryover"
  - "lifestage_carryover"
---
# INTRO
Continuing with [Ariana's request to extract RNA and run qPCRs](https://github.com/RobertsLab/resources/issues/1891) (GitHub Issue) for the [`lifestage_carryover` project](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover) (GitHub repo), I performed reverse transcription on RNA I previously isolated:

- [20250512 RNA Isolations](../2025-05-12-RNA-Isolation---C.gigas-Lifestage-Carryover-Samples-Using-Direct-zol-RNA-MiniPrep-Plus-Kit/index.qmd) (Notebook entry)

- [20250513 RNA Isolations](../2025-05-13-RNA-Isolation---C.gigas-Lifestage-Carryover-Samples-Using-Direct-zol-RNA-MiniPrep-Plus-Kit/index.qmd) (Notebook entry)

- [20250513 RNA Quantification](../2025-05-13-RNA-Quantification---C.gigas-Lifestage-Carryover-RNA-Samples-Using-Qubit-High-Sensitivity-RNA-Assay/index.qmd) (Notebook entry)


# MATERIALS & METHODS

Reverse transcription was performed using the [GoScript Reverse Transcription System (Promega)](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/Promega-goscript-reverse-transcription-system-protocol.pdf) (PDF), using oligo dT primers and 1.5mM MgCl<sub>2</sub>. The reaction size was doubled, from 20uL to 40uL, to allow for sufficient cDNA for all the downstream qPCRs we plan to perform. The optional RNasin was also used. Reactions were set up in a 96-well, low profile qPCR plate. Plate was sealed with strip caps. The reverse transcriptase components were prepared as a master mix and then distributed to RNA/oligo dT mixtures.

I targeted 200ng of RNA in the reactions, but there were a number of samples which had insufficient RNA to accommodate that amount. In those instances, the maximum _volume_ of RNA which fit into the reaction volume was used (i.e. 9uL of RNA). See the [cDNA calcs for a list of samples](#cdna-calcs-and-plate-layout).



Briefly, here is how the reactions were setup:

1. Combined RNA (200ng), oligo dT primers, and H<sub>2</sub>O to a final volume of 10uL.
2. Incubated plate at 70<sup>o</sup>C for 5mins and immediately chilled plate in ice water for 5mins.
3. Added 30uL of RT reaction master mix to each sample.
4. Incubated plate at 25<sup>o</sup>C for 5mins.
5. Incubated plate at 42<sup>o</sup>C for 60mins.
6. Incubated plate at 70<sup>o</sup>C for 15mins to deactivate reverse transcriptase.

All incubations were conducted in a 96-well PTC-200 (MJ Research) thermalcycler using a heated lid.

::: {.callout-important}
Step 6 is _required_ if using cDNA for downstream qPCR analyses.
:::

## cDNA calcs and plate layout:

- [20250516-cgig-lifestage-carryover-cDNA-calcs](https://docs.google.com/spreadsheets/d/1KGMRl30Thd8R28TIUFaMwGCdH1JmtSKKssUYgVxgoqI/edit?usp=sharing) (Google Sheet)

Plate was stored at -20<sup>o</sup>C.