---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Resazurin Assays - Selected Juvenile Ruditapes philippinarum Exposed to 36C Acute Heat Stress Day 1
date: '2026-04-01'
draft: false
engine: knitr
categories: 
  - "2026"
  - "resazurin"
  - "Ruditapes philippinarum"
  - "Manila clam"
  - "Synergy HTX"
---
# INTRO

This is the second day of a two day experiment. Day 0 corresponds to the first day of measurements, and Day 1 corresponds to the second day of measurements. The same clams were measured on both days. Day 0 notebook entry is available here:

- [Day 0 Notebook Entry](../2026-03-31-Resazurin-Assays---Selected-Juvenile-Ruditapes-philippinarum-Exposed-to-36C-Acute-Heat-Stress-Day-0/index.qmd)

# MATERIALS & METHODS

Control clams (`C`) compared with selected clams (`S`) at 36<sup>o</sup>C.

Clams were processed in 12-well plates and submerged in `5.0mL` of resazurin working solution prepared today.

- 986.66 mL filtered seawater (4<sup>o</sup>C filtered sea water from 11/19/2025 by AH)
- 2.22 mL resazurin stock solution (from step 1 above)
- 1.00 mL DMSO
- 10.00 mL antibiotic solution (100x Penn/Strep & 100x Fungizone)

Plates were measured every 30mins on a Synergy HTX (Agilent) plate reader over the course of 4hrs.

Plate layout was randomized; Steven is currently the only person who knows the treatment assignments.

::: {.callout-important}
Low volumes were noted in the following plates/wells, which may have been due to clam spitting:

DA1
BA3
DB2
EC2
:::



## Plate temps

Wells were spot checked and range noted in table below.

| PLATE | TIME | TEMP  |
|-------|------|-------|
| A     | 0    | 11-12 |
| A     | 1    | 29    |
| A     | 2    | 31    |
| A     | 3    | 32-33 |
| A     | 4    | 33-34 |

# RESULTS


Data are available here:

- [https://github.com/RobertsLab/resazurin-assay-development/tree/main/data/clam/20260401-clam-Day2-36C-C-vs-S](https://github.com/RobertsLab/resazurin-assay-development/tree/main/data/clam/20260401-clam-Day2-36C-C-vs-S)

At the time of this writing, there is no plate layout file available for this experiment, so it's not possible to determine which wells correspond to which clams. Steven is working on creating a plate layout file, which will be added to the GitHub repository when it's available.