---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Resazurin - C.gigas Second Trial
date: '2024-03-12'
draft: true
engine: knitr
categories: 
  - Crassostrea gigas
  - Pacific oyster
  - 2024
  - resazurin
---
# INTRO

[After running the initial resazuring test on 20240308](../2024-03-08-Resazurin---Preliminary-Respiration-Test-Using-C.gigas/index.qmd) (Notebook), Steven/Ariana [asked that I run another trial](https://github.com/RobertsLab/resources/issues/1842) (GitHub Issue). This second trial was designed to get some baseline respiration from a set of oysters, followed by a heat stress at 35<sup>o</sup>C.

For this initial test, I followed the [resazurin assay](https://github.com/RobertsLab/project-gigas-carryover/blob/27441a713dfe68578758103bb82dd4dca4b4c091/protocols/Resazurin-assay.md) (commit 27441a7) shared by Steven, with the following modifications:

- Non-sterile water/sea water was used.

- No penn/strep/Fungizone used.

## Procedure

### Pre-stress

A total of nine small oysters were weighed, measured (using analog calipers). Two larger oyters were also weighed/measured and placed in their own glass Petri dishes. Fresh resazuring assay media was prepared. Two milliliters was added to 11 wells of the 12-well plate - the final position (`C04`) was left empty. Twenty milliliters was added to each Petri dish. These volumes ensured that the oysters would be submerged when added.

Fluorescence was measured on a Victor<sup>3</sup> plate reader immediatley after adding resazurin assay media to the plate and dishes. The oysters were then distributed/added to the 12-well plate and dishes. Fluorescence was measured again after 0.5 and 1.0hrs. To measure the dishes, 2mL of assay media was transferred to wells `A01` and `A02` of a clean 12-well plate (the smaller of the two oysters in `A01`).

### Heat stress @ 35<sup>o</sup>C.

As before, a fresh batch of resazurin assay media was made and distributed in a 12-well plate and two glass Petri dishes. The plate and the dishes were warmed at 35<sup>o</sup>C in a warm air incubator (Barnstead) for 45mins. The 12-well plate was covered; the Petri dishes were not. Fluorescence was measured on a Victor<sup>3</sup> plate reader immediately before  transferring oysters to the plate and dishes.

Oysters were transferred from the pre-stress plate/dishes to the pre-warmed plate/dishes. Fluorescence was measured again after 0.5 and 1.0hrs. To measure the dishes, 2mL of assay media was transferred to wells `A01` and `A02` of a clean 12-well plate (the smaller of the two oysters in `A01`).

# RESULTS

