---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Daily Bits - January 2024
date: '2024-01-02'
draft: false
engine: knitr
categories: 
  - 2024
  - Daily Bits
---

## 20240129

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Did mor ework on exon stuff.

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Read through a few papers about sRNA-seq trimming/analyses.

## 20240126

### Science Hour

- Worked on more [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo) exon stuff with Steven.

## 20240125

### Lab Meeting

- Read Ch.5 of "Race After Technology"

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Weekly meeting.

- Explored exon coverage with Steven.

## 20240124

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Implemented exon sum threshold [to update ln(fold change vs Exon 1) determinations](../2024-01-24-Figure-Updates---CEABIGR-Spurious-Transcription-Calcs-and-Plotting-Using-Exon-Sum-Threshold/index.qmd) (Notebook).

## 20240123

### Miscellaneous lab stuff

- Helped answer some questions Eric had regarding RNA isolation.

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Worked extensively on [exon sum threshold](https://github.com/sr320/ceabigr/blob/6b4bf89801a50180993331a927830d820b42e5e3/code/65-exon-coverage.qmd#L437-L486).

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Answered some questions Danielle Becker had regarding Zymo's RiboFree rRNA depletion and whether or not it works for marine organisms (does not work for marine molluscs...).

## 20240122

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- [Steven decided on exon coverage threshold of 100 reads](https://github.com/sr320/ceabigr/issues/88#issuecomment-1904556525) (GitHub Issue).

- Fleshed out more of the exon coverage threshold code.

### Miscellaneous lab stuff

- Got [updated quote for Cod WGBS](https://github.com/RobertsLab/resources/issues/1732#issuecomment-1904854424) (GitHub Issue).

## 20240119

- Science Hour

- Helped walk Eric (virtually) through lab to get ready for RNA isolations.

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Continued work I started on setting exon coverage threshold.

## 20240111

- Started getting students Raven access for Steven's course in Chile.

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Need to test out Azenta recommended trimming parameters.

- Worked briefly on manuscript.

## 2024010

### Lab meeting

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Yaamini and I reviewed spurious transcription data and determined some next steps:

  - Spurious transcription calcs associated with different levels of gene methylation.

  - Determine the slope of the ln(fold-change exon expression) per gene.

## 20240109

- Power outage all day...

## 20240108

In lab:

- Sent [replacement liver samples for Cod RNA-seq project](https://github.com/RobertsLab/resources/issues/1764) (GitHub Issue).

- Helped Noah get mercuric chloride waste transferred to EH&S carboys in FTR 228.

- Had to do a fresh install of R on `swoose`. Took awhile...

## 20240105

- Science Hour

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Started to look into where (if?) we have methylation data on a per gene basis to plot vs. exon fold-change data from [20240103](#)

## 20240104

- Disabled Sensaphone input #3 due to frequent calls. This is the sensor for the "middle" -80<sup>o</sup>C freezer. This is an older freezer from a former professor, so I'm not sure we have any info on how to set it up, but I will see if I can figure out how to change the freezer temp limits, instead of disabling the Sensaphone.

- Investigated [a budget spending discrepancy issue]() (GitHub Issue).

- Added a [page about RStudio Server access on Raven](https://github.com/RobertsLab/tusk/blob/main/modules/05-computers.qmd) on the [tusk](https://robertslab.github.io/tusk/) website, per [this GitHub Issue.](https://github.com/RobertsLab/resources/issues/1776)

## 20240103

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

 - Worked extensively on [calculating mean, natural log fold change of Exons 2 - 6, relative to Exon 1 expression across all genes, in all samples](https://github.com/sr320/ceabigr/blob/main/code/65-exon-coverage.qmd).

 - Generated line plots of the various possible comparisons.

## 20240102