---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Resazurin Assays - Selected Juvenile Ruditapes philippinarum Exposed to 36C Acute Heat Stress Day 0
date: '2026-03-31'
draft: false
engine: knitr
categories: 
  - "2026"
  - "resazurin"
  - "Ruditapes philippinarum"
  - "Manila clam"
  - "Synergy HTX"
---
# INTRO

Steven asked me to perform resazurin assays on "selected" juvenile _Ruditapes philippinarum_ (Manila clam) exposed to 36<sup>o</sup>C acute heat stress. The goal of the experiment is to compare metabolic activity between the "selected" clams and control clams when exposed to heat stress.

This is the first day of a two day experiment. Day 0 corresponds to the first day of measurements, and Day 1 corresponds to the second day of measurements. The same clams were measured on both days. Day 1 notebook entry is available here:

- [Day 1 Notebook Entry](../2026-04-01-Resazurin-Assays---Selected-Juvenile-Ruditapes-philippinarum-Exposed-to-36C-Acute-Heat-Stress-Day-1/index.qmd)

# MATERIALS & METHODS

Control clams (`C`) compared with selected clams (`S`) at 36<sup>o</sup>C.

Clams were processed in 12-well plates and submerged in `5.0mL` of resazurin working solution stored at 4<sup>o</sup>C,prepared on [20260330](../2026-03-30-Resazurin-Assays---Selected-Juvenile-Ruditapes-philippinarum-Exposed-to-40C-Acute-Heat-Stress/index.qmd) (notebook entry).

Plates were measured every 30mins on a Synergy HTX (Agilent) plate reader.

Plate layout was randomized; Steven is currently the only person who knows the treatment assignments.


::: {.callout-important}
- Seemed to be inconsistent heating, with interior wells usually ~1.5<sup>o</sup>C lower than rest of wells.

The following wells lost volume - possibly due to clam spitting?

- Plate A, C3
- Plate C, C4
- Plate B, A3
- Plate D, B2
:::



# RESULTS

Data are available here:

- [https://github.com/RobertsLab/resazurin-assay-development/tree/main/data/clam/20260331-clam-36C-C-vs-S](https://github.com/RobertsLab/resazurin-assay-development/tree/main/data/clam/20260331-clam-36C-C-vs-S)

At the time of this writing, there is no plate layout file available for this experiment, so it's not possible to determine which wells correspond to which clams. Steven is working on creating a plate layout file, which will be added to the GitHub repository when it's available.