---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Daily Bits - February 2024
date: '2024-02-01'
draft: true
engine: knitr
categories: 
  - 2024
  - Daily Bits
bibliography: references.bib
---

## 20240206

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Continued to explore trimming and merging strategies for sRNA-seq data, using [`fastp`](https://github.com/OpenGene/fastp) alone, BBMerge alone, and/or combining the two approaches.

### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Spent a few hours on a video chat with Steven and Yaamini going through exon fold-change code/analysis.

## 20240205

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Continued to explore trimming and merging strategies for sRNA-seq data, using [`fastp`](https://github.com/OpenGene/fastp) alone, BBMerge alone, and/or combining the two approaches.

## 20240202

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

### Science Hour

- Steven and I played around with exon fold-change data.

## 20240201

### In Lab

-   Lab meeting.

-   Helped Eric get started with RNA quantification using Qubit.

### [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Tested out more R1/R2 merging/trimming using [`fastp`](https://github.com/OpenGene/fastp).

  - Merging is similar to BBMerge results - i.e. a (relatively) small number of reads are actually merging, despite the fact that these should be short insert sizes and R1/R2 reads should overlap...

-   Installed [XICRA](https://github.com/HCGB-IGTP/XICRA) [@sanchezherrero2021] on Raven to identify isomiRs in sRNA-seq data. Possibly to get around the merging "issues" experienced with BBMerge and [`fastp`](https://github.com/OpenGene/fastp).

    -   Installation was a bit bumpy, due to some weird Conda/Mamba "flexible solve" problem, but got that straightened out with `conda config --set channel_priority flexible`.

    -   Installation test(s) had issues. I created the following GitHub Issues on the developer's site in hopes of getting help:

      - [`installer.sh error`](https://github.com/HCGB-IGTP/XICRA/issues/47)

      - ["No samples were retrieved" in test data](https://github.com/HCGB-IGTP/XICRA/issues/42)


### [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

- Need to generate R<sup>2</sup> values and slope of exon expression for all genes, Exons 1 - 6.