---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Resazurin Assays - Selected Juvenile Ruditapes philippinarum Exposed to 36C Acute Heat Stress
date: '2026-04-01'
draft: false
engine: knitr
categories: 
  - "2026"
  - "resazurin"
  - "Ruditapes philippinarum"
  - "Manila clam"
  - "Synergy HTX"
---
# INTRO

Steven asked me to perform resazurin assays on "selected" juvenile _Ruditapes philippinarum_ (Manila clam) exposed to 36<sup>o</sup>C acute heat stress. The goal of the experiment is to compare metabolic activity between the "selected" clams and control clams when exposed to heat stress. This is similar to the previous experiment at 36<sup>o</sup>C [Day 0 Notebook Entry](../2026-03-31-Resazurin-Assays---Selected-Juvenile-Ruditapes-philippinarum-Exposed-to-36C-Acute-Heat-Stress-Day-0/index.qmd) and [Day 1 Notebook Entry](../2026-04-01-Resazurin-Assays---Selected-Juvenile-Ruditapes-philippinarum-Exposed-to-36C-Acute-Heat-Stress-Day-1/index.qmd), but with a set of larger clams.

# MATERIALS & METHODS

Clams were processed in 12-well plates and submerged in `5.0mL` of resazurin working solution stored at 4<sup>o</sup>C,prepared on [20260330](../2026-03-30-Resazurin-Assays---Selected-Juvenile-Ruditapes-philippinarum-Exposed-to-40C-Acute-Heat-Stress/index.qmd) (notebook entry).

Plates were measured every 30mins on a Synergy HTX (Agilent) plate reader.

Plate layout was randomized; Steven is currently the only person who knows the treatment assignments.


::: {.callout-important}
The following wells lost volume - possibly due to clam spitting?

- GA3
- JB1
- KA2
- LA4
:::


## Plate Temps

Wells were spot checked and range noted in table below.

| PLATE | TIME | TEMP  |
|-------|------|-------|
| G     | 0    | 11-12 |
| G     | 0.5  | 14-16 |
| G     | 1    | 24-30 |
| G     | 1.5  | 27-30 |
| G     | 2    | 31-32 |
| G     | 2.5  | 31-32 |
| G     | 3    | 31-32 |
| G     | 3.5  | 31-32 |
| G     | 4    | 33    |

# RESULTS

Data are available here:

- [https://github.com/RobertsLab/resazurin-assay-development/tree/main/data/clam/20260401-clam-36C-C-vs-S](https://github.com/RobertsLab/resazurin-assay-development/tree/main/data/clam/20260401-clam-36C-C-vs-S)

At the time of this writing, there is no plate layout file available for this experiment, so it's not possible to determine which wells correspond to which clams. Steven is working on creating a plate layout file, which will be added to the GitHub repository when it's available.