---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Daily Bits - November 2023
date: '2023-11-05'
draft: false
engine: knitr
categories: 
  - Daily Bits
  - 2023
---

## 20231130

- Lab meeting.

  - Finished [plotting task](https://robertslab.github.io/sams-notebook/posts/2023/2023-11-30-Plotting-Fun---Lab-Meeting-Task/) from yesterday.

- [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo) meeting.

  - Identified definition of spurious transcription and how to calculate.


## 20231129

- ProCard reconciliation.

- Worked on task for tomorrow's lab meeting.

- Meeting with Daniell. Made a couple of suggestsions for her to work on:

  - Develop/teach Apptainers (Singularity).

  - Develop BLAST/UniProt/GO annotation pipeline.

## 20231117

[Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo)

- Finished adding numbers to presentation.

- E5 molecular meeting

  - Decided to re-evaluate trimming, due to lack of matches in R2 reads.

## 20231116

- [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo):

  - Continued _P.evermanni_ sRNAseq analysis.

  - Work on presentation for tomorrow.

- [CEABIGR](https://github.com/sr320/ceabigr) (GitHub repo)

  - Discussed spurious transcription:

    - [Decided to calculate exon expression regression](https://github.com/sr320/ceabigr/issues/86) (GitHub Issue)

- Helped Grace L. with a git/GitHub issue on Raven (committed files which were too big for GitHub).

## 20231115

- [Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo):

  - Started _P.evermanni_ sRNAseq analysis.

## 20231114

-[Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo):

  - Knitted [`miRDeep2`](https://github.com/rajewsky-lab/mirdeep2) analysis to markdown and HTML.

## 20231113

-[Coral E5](https://github.com/urol-e5/deep-dive) (GitHub repo):

  - [`miRDeep2`](https://github.com/rajewsky-lab/mirdeep2) analysis finally completed after 72hrs (!).

  - Started teasing out some of the results from the MiRDeep2 analysis.

## 20231109

- [DuMOAR](https://github.com/laurahspencer/DuMOAR)

  - Ran [DIAMOND BLASTx](https://github.com/bbuchfink/diamond) to use for [Trinotate](https://github.com/Trinotate/Trinotate/wiki).

  - Ran [Trinotate](https://github.com/Trinotate/Trinotate/wiki).

## 20231108

- Coral E5

  - Dealt with the trials and tribulations of getting [miRDeep2](https://github.com/rajewsky-lab/mirdeep2) to run. There are a lot of "hidden" file formatting requirements which aren't documented until a job fails. Even then, the error messages don't provide any advice. However, finally got it running!

- Read Ch. 1 of "Race After Technology: The New Jim Code" by Ruha Benjamin for DEI bookclub discussion at tomorrow's lab meeting.

## 20231107

- Coral E5

  - Ran NCBI BLASTn on _A.pulcha_ sRNAseq.

- [DuMOAR](https://github.com/laurahspencer/DuMOAR)

  - Began [transcriptome annotation](https://github.com/laurahspencer/DuMOAR/issues/44) (GitHub) issue with [TransDecoder](https://github.com/TransDecoder/TransDecoder/wiki).

## 20231106

- ProCard reconciliation.

- Scan/upload packing slips for purchases to Workday.

- Coral E5

  - non-coding RNA meeting.

  - Begin miRNA BLASTn.

## 20231103

- Coral E5

  - Ran [ShortStack](https://github.com/MikeAxtell/ShortStack) on _A.pulchra_ (uses _A.millepora_ genome though, since no _A.pulchra_ genome exists) sRNAseq reads to identify potential miRNAs.

    - [13-Apul-sRNAseq-ShortStack.Rmd](https://github.com/urol-e5/deep-dive/blob/main/D-Apul/code/13-Apul-sRNAseq-ShortStack.Rmd)

    - Wasted a _lot_ time messing around/learning how to Knit documements in R Markdown.

## 20231102

- In lab.

- E5 lncRNA meeting.

- Lab meeting.

- CEABIGR meeting.

- Coral E5

  - Ran [MirMachine](https://github.com/sinanugur/MirMachine) to identify miRNAs in _A.pulchra_.

    - [12-Apul-sRNAseq-MirMachine.Rmd](https://github.com/urol-e5/deep-dive/blob/main/D-Apul/code/12-Apul-sRNAseq-MirMachine.Rmd)



## 20231101

- Read intro to "Race After Technology: Abolisitionist for the new Jim Code".

- Coral E5

  - Ran [miRTrace](https://github.com/friedlanderlab/mirtrace) on _A.pulcrha_ sRNAseq data to identify potential taxonomic origins of miRNAs.

    - [09-Apul-sRNAseq-miRTrace.Rmd](https://github.com/urol-e5/deep-dive/blob/main/D-Apul/code/09-Apul-sRNAseq-miRTrace.Rmd)