---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: DNA Isolation and Quantification - S.namaycush Liver
date: '2025-02-20'
draft: false
engine: knitr
categories: 
  - "2025"
  - "lake trout"
  - "Salvelinus namaycush"
  - "DNA isolation"
  - "Qubit"
  - "DNA quantification"
---
# INTRO
Per this [GitHub Issue](https://github.com/RobertsLab/resources/issues/2079), Steven asked that I select [_Salvelinus namaycush_](https://en.wikipedia.org/wiki/Lake_trout) liver samples from Lean and Siscowet ecotypes for DNA isolation. As part of this project, DNA is being subjected to long read sequencing. A subset of the samples previously sent did not perform well, so need to be replaced.

# MATERIALS & METHODS

## DNA Isolations

DNA was isolated from five Lean and five Siscowet ecotypes using the Quick-DNA Microprep Kit (ZymoResearch; Cat: D3024), according to the manufacturer's protocol, with the inclusion of beta-mercaptoethanol in the DNA Lysis Buffer.

Briefly, the liver tissue had been stored @ -20<sup>o</sup>C in RNAlater. Samples were thawed and the entirety of the sample was transferred to a 1.5mL snap cap tubed. Samples were homogenized using disposable plastic pestles (Fisher Scientific; Cat; K749520-0090). Insolbule debris was pelleted and supernatant was transferred to spin columns. Samples were processed per the manufacturer's protocol.

DNA was eluted with 50uL of Elution Buffer.

DNA was stored @ -20<sup>o</sup>C in my "Lake Trout Liver gDNA" box in FTR 209.

## DNA Quantification

DNA was quantified using the Qubit 1x dsDNA HS Assay (Invitrogen; Q33231) on the Roberts Lab Qubit 3.0 fluorometer. 1uL of each sample was used.


# RESULTS

Qubit data (Google Sheet):

- [20250220-snam-qubit-DNA.hs-liver](https://docs.google.com/spreadsheets/d/1QTeE37cF-0oe1bgWQrgKs_ebgQi1LCFjtOq5WeUCS4I/edit?usp=sharing)

| Sample | Ecoytpe | Concentration(ng/uL) | Volume(uL) | Total(ng) |
|--------|---------|----------------------|------------|-----------|
| FA091  | Lean    | 146                  | 40         | 5840      |
| FA092  | Lean    | 540                  | 40         | 21600     |
| FA093  | Lean    | 36.8                 | 25         | 920       |
| FA094  | Lean    | 214                  | 40         | 8560      |
| FA095  | Lean    | 253                  | 40         | 10120     |
| FA096  | Sisco   | 38.8                 | 40         | 1552      |
| FA097  | Sisco   | 258                  | 40         | 10320     |
| FA098  | Sisco   | 22.5                 | 40         | 900       |
| FA099  | Sisco   | 238                  | 40         | 9520      |
| FA100  | Sisco   | 205                  | 40         | 8200      |

::: {.callout-note}
Sample FA093 experienced clogging in the column, resulting in low yield.
:::