---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
date: 2015-02-09 21:19:28+00:00
layout: post
slug: sequencing-data-lsu-c-virginica-mbd-bs-seq
title: Sequencing Data - LSU C.virginica MBD BS-Seq
categories:
  - 2015
  - LSU C.virginica Oil Spill MBD BS Sequencing
  - BS-seq
  - checksum
  - code
  - Crassostrea virginica
  - curl
  - Eastern oyster
  - HiSeq2500
  - LSU
  - MBD
  - md5
  - oil
---

Our sequencing data (Illumina HiSeq2500, 100SE) for this project has completed by Univ. of Oregon Genomics Core Facility (order number 2112).

Samples sequenced/pooled for this run:

<table >
<tbody >
<tr >

<td >**Sample**
</td>

<td >**Treatment**
</td>

<td >**Barcode**
</td>
</tr>
<tr >

<td >HB2
</td>

<td >25,000ppm oil
</td>

<td >ATCACG
</td>
</tr>
<tr >

<td >HB16
</td>

<td >25,000ppm oil
</td>

<td >TTAGGC
</td>
</tr>
<tr >

<td >HB30
</td>

<td >25,000ppm oil
</td>

<td >TGACCA
</td>
</tr>
<tr >

<td >NB3
</td>

<td >No oil
</td>

<td >ACAGTG
</td>
</tr>
<tr >

<td >NB6
</td>

<td >No oil
</td>

<td >GCCAAT
</td>
</tr>
<tr >

<td >NB11
</td>

<td >No oil
</td>

<td >CAGATC
</td>
</tr>
</tbody>
</table>

All code listed below was run on OS X 10.9.5

Downloaded all 15 fastq.gz files to [Owl/web/nightingales/C_virginica](https://owl.fish.washington.edu/nightingales/C_virginica/).


Renamed all files by removing the beginning of each file name (2112?fileName=) and replacing that with 2112_:

`$for file in 2112*lane1_NoIndex_L001_R1_0*; do mv "$file" "${file/#2112?fileName=/2112_}"; done`



Created a directory readme.md (markdown) file to list & describe directory contents: [readme.md](https://owl.fish.washington.edu/nightingales/C_virginica/readme.md)

`$ls *.gz >> readme.md`

Note: In order for the readme file to appear in the web directory listing, the file cannot be all upper-case.



Created MD5 checksums for each fastq.gz file: [checksums.md5](https://owl.fish.washington.edu/nightingales/C_virginica/checksums.md5)

`$md5 *.gz >> checksums.md5`
