---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: RNA Isolation and Quantification - C.gigas PolyIC Mechanical Trials for Valentina Using Quick-DNA RNA MiniPrep Plus Kit
date: '2025-08-04'
draft: false
engine: knitr
categories: 
  - "2025"
  - "PolyIC"
  - "RNA Isolation"
  - "RNA quantification"
  - "Qubit"
  - "Magallana gigas"
  - "Pacific oyster"
---
# INTRO

[Steven tasked me with helping and/or isolating RNA](https://github.com/RobertsLab/resources/issues/2256) (GitHub Issue) for Valentina (visiting scientist from Cristian's lab in Chile). Samples were whole body (no shells) of small juvenile oysters exposed to [poly I:C](https://en.wikipedia.org/wiki/Polyinosinic:polycytidylic_acid) (Wikipedia) and then subjected to mechanical stress, or no mechanical stress.

# MATERIALS & METHODS

Whole body tissue had been snap frozen and stored at -80<sup>o</sup>C.


## Homogenization

300uL of DNA/RNA Shield (ZymoResearch) were added to the frozen tissue. Samples and DNA/RNA Shield were transferred to 1.5mL SafeLock (Eppendorf) microcentrifuge tubes containig ~50uL of 0.5mm zirconium oxide beads and ~50uL of 0.15mm zirconium oxide beads. Samples were homogenized using the Roberts Lab Bullet Blender 5E Gold + (NextAdvance) with 1.5mL tube adapters for 3mins at speed 12. The Bullet Blender was pre-cooled, and cooled, using dry ice.

## RNA Isolation

RNA was isolated using the Quick-DNA/RNA MiniPrep Plus Kit, according to the manufacturer's protocol with the following changes/notes:

:::: {.callout-note}
- Treated with optional DNase step.

- Eluted with 50uL of H<sub>2</sub>O.
:::

## RNA Quantificaiton

RNA was quantified using the Qubit High Sensitivity RNA Assay (hsRNA), using 1uL of each sample.

The initial round of quantification revealed that most samples were _too_ concentrated, so a 1:10 dilution of those samples were prepared and quantified.

# RESULTS

## Qubit data

- [20250804-cgig-hsRNA-polyIC](https://docs.google.com/spreadsheets/d/1-L80n-eN18ZJX0NVqU89cRqPnDpUYI5tzt4KrVW9wUo/edit?usp=sharing) (Google Sheet)



| Sample | Concentration(ng/uL) | Dilution Factor | Actual Concentration (ng/uL) | Volume (uL) | Yield (ng) |
|--------|----------------------|-----------------|------------------------------|-------------|------------|
| A1 P C | 26.4                 | 10              | 264                          | 40          | 10560      |
| A2 P C | 142                  | 1               | 142                          | 40          | 5680       |
| A3 P C | 112                  | 1               | 112                          | 40          | 4480       |
| A4 P C | 26.8                 | 10              | 268                          | 40          | 10720      |
| A5 P C | 150                  | 1               | 150                          | 40          | 6000       |
| B1 P C | 31.4                 | 10              | 314                          | 40          | 12560      |
| B2 P C | 34.8                 | 10              | 348                          | 40          | 13920      |
| B3 P C | 196                  | 1               | 196                          | 40          | 7840       |
| B4 P C | 190                  | 1               | 190                          | 40          | 7600       |
| B5 P C | 84.6                 | 1               | 84.6                         | 40          | 3384       |
| A1 P M | 23.4                 | 10              | 234                          | 40          | 9360       |
| A2 P M | 52.8                 | 10              | 528                          | 40          | 21120      |
| A3 P M | 27.4                 | 10              | 274                          | 40          | 10960      |
| A4 P M | 37.2                 | 10              | 372                          | 40          | 14880      |
| A5 P M | 28.8                 | 10              | 288                          | 40          | 11520      |
| B1 P M | 63                   | 1               | 63                           | 40          | 2520       |
| B2 P M | 35.2                 | 10              | 352                          | 40          | 14080      |
| B3 P M | 28.8                 | 10              | 288                          | 40          | 11520      |
| B4 P M | 200                  | 1               | 200                          | 40          | 8000       |
| B5 P M | 42.4                 | 10              | 424                          | 40          | 16960      |