---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: RNA Isolation and Quantification - C.gigas Lifestage Carryover Seed Juvenile and Adult
date: '2024-06-18'
draft: false
engine: knitr
categories: 
  - "2024"
  - "project-gigas-carryover"
  - "Crassostrea gigas"
  - "Pacific oyster"
  - "adult"
  - "seed"
  - "spat"
  - "Directzol RNA Miniprep"
  - "Qubit"
  - "RNA HS assay"
---
# INTRO

I was [asked to isolate RNA from a list of samples](https://github.com/RobertsLab/resources/issues/1891) (GitHub Issue) from a number of [_Crassostrea gigas_ (Pacific oyster)](http://en.wikipedia.org/wiki/Pacific_oyster) spat, seed, and adults that had been collected as part of the [`project-gigas-carryover`](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover) (GitHub repo). The full list of all samples needing processing is here:

- [`20240508_rna_extractions.csv`](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/sampling_metadata/20240508_rna_extractions.csv)

I processed the following eight samples:

- 232
- 233
- 235
- 236
- 237
- 238
- 239
- 240

::: {.callout-note}
Couldn't find sample `197`.
:::

# MATERIALS & METHODS
Oysters had been previously preserved in RNAlater (Ambion), supernatant removed, and then frozen @ -80<sup>o</sup>C. All samples were treated in the following fashion:

## RNA Isolation
Samples were thawed and residual RNAlater (Ambion) was removed.

RNA isolations were conducted using the Directzol RNA Miniprep Kit (ZymoResearch). All centrifugation steps were performed at 16,000g in an Eppendorf 5425 microfuge at room temperature, unless noted otherwise.

- Added 500uL of TriReagent (ZymoResearch) to existing 1.5mL tubes containing the sample.
- Homogenized using disposble pestles.
- Transferred to a 15mL conical.
- Adjusted volume in 0.5mL incremements until TrReagent was no longer cloudy.
- Pellted insoluble material 10,000g for 5mins in SL50T rotor (Sorval) in Super T21 table top centrifuge (Sorval) at room temp.
- Transferred supe to new 15mL conical containing equal volume of 100% ethanol and vortexed.
- Transferred mixture to spin columns in 700uL volumes.
- Followed kit protocol, including DNase step.
- Eluted in 50uL of H<sub>2</sub>O.


Samples were temporarily stored on ice for quantification. DNAsed RNA samples were subsequently transferred to the same box in the -80<sup>o</sup>C from which they were taken.

## RNA Quantification
RNA was quantified with the Roberts Lab Qubit 3.0 fluorometer (Invitrogen). Samples were quantified with the Qubit RNA High Sensitivity (HS) assay (Invitrogen). 1uL of sample was used for the assay(s).

# RESULTS

Raw Qubit data is here:

- [`20240618-cgig-qubit-RNA.hs-carryover.csv`](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/qubit/20240618-cgig-qubit-RNA.hs-carryover.csv) (GitHub)


| sample_ID | Original sample conc.(ng/uL) |
|-----------|------------------------------|
| 232       | 106                          |
| 233       | 178                          |
| 235       | 134                          |
| 236       | 55.4                         |
| 237       | 63.8                         |
| 238       | 19                           |
| 239       | 132                          |
| 240       | 47.4                         |

# SUMMARY

All samples yielded RNA.
