---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Homogenization - C.gigas Juvenile Whole Body from polyIC Temp and Mech Stress
date: '2025-08-20'
draft: false
engine: knitr
categories: 
  - "2025"
  - "PolyIC"
  - "RNA Isolation"
  - "RNA quantification"
  - "Qubit"
  - "Magallana gigas"
  - "Pacific oyster"
---
# INTRO

[Steven tasked me with helping and/or isolating RNA](https://github.com/RobertsLab/resources/issues/2256) (GitHub Issue) for Valentina (visiting scientist from Cristian's lab in Chile). Samples were whole body (no shells) of small juvenile oysters exposed to [poly I:C](https://en.wikipedia.org/wiki/Polyinosinic:polycytidylic_acid) (Wikipedia) and then subjected to mechanical stress or temperature stress (or no stress at all).

I [previously helped isolate RNA from a subset of these on 20250804](../2025-08-04-RNA-Isolation-and-Quantification---C.gigas-PolyIC-Mechanical-Trials-for-Valentina-Using-Quick-DNA-RNA-MiniPrep-Plus-Kit/index.qmd) and needed to process the remainder, now that Valentina has returned to Chile.

# MATERIALS & METHODS

Whole body tissue had been snap frozen and stored at -80<sup>o</sup>C.


## Homogenization

300uL of DNA/RNA Shield (ZymoResearch) were added to the frozen tissue. Samples and DNA/RNA Shield were transferred to 1.5mL SafeLock (Eppendorf) microcentrifuge tubes containig ~50uL of 0.5mm zirconium oxide beads and ~50uL of 0.15mm zirconium oxide beads. Samples were homogenized using the Roberts Lab Bullet Blender 5E Gold + (NextAdvance) with 1.5mL tube adapters for 3mins at speed 12. The Bullet Blender was pre-cooled, and cooled, using dry ice.

Homogenized samples were stored @ -20<sup>o</sup>C until RNA isolation can be performed with Quick-DNA/RNA MiniPrep Plus Kit (ZymoResearch) later this week.