---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: Daily Bits - June 2024
date: '2024-06-01'
draft: false
engine: knitr
categories: 
  - daily bits
  - 2024
---
## 20240618

### In lab

- [Isolated and quantified RNA](../2024-06-18-RNA-Isolation-and-Quantification---C.gigas-Lifestage-Carryover-Seed-Juvenile-and-Adult/index.qmd) (Notebook) for `[project-lifestage-carryover project](https://github.com/RobertsLab/project-gigas-carryover/tree/main) (GitHub repo).

- [Submitted littleneck clam histology cassettes for Mac](../2024-06-18-Samples-Submitted---Littleneck-Clam-Histology-Cassettes-to-UW-Pathology-Research-Services-Laboratory/index.qmd) (Notebook).

- Helped get Colby with the resazurin assays.

## 20240617

### In lab

- [Isolated RNA](../2024-06-17-RNA-Isolation---C.gigas-Lifestage-Carryover-Seed-Juvenile-and-Adult/index.qmd) (Notebook) and [quantified RNA](../2024-06-17-RNA-Quantification---C.gigas-RNA-Lifestage-Carryover-from-20240615-and-20240617/index.qmd) (Notebook) for `[project-lifestage-carryover project](https://github.com/RobertsLab/project-gigas-carryover/tree/main) (GitHub repo).

- Helped get Colby started with the resazurin assay protocols/equipment.

- Ran through lab safety with Colby and Madeline.

## 20240615

### In lab

- [Isolated RNA](../2024-06-15-RNA-Isolation---C.gigas-Lifestage-Carryover-Seed-Juvenile-Adult/index.qmd) (Notebook) for `[project-lifestage-carryover project](https://github.com/RobertsLab/project-gigas-carryover/tree/main) (GitHub repo).

- [Replaced dead HDD in Gannet expansion unit](../2024-06-15-Computer-Maintenance---Replace-Bad-HDD-on-Gannet/index.qmd) (Noteobok).




## 20240612

- Finished [edgeR analysis of Pacific cod RNA-seq](../2024-06-12-Differential-Gene-Expression---G.macrocephalus-RNA-seq-9C-vs-16C-Using-edgeR/index.qmd) (Notebook).

## 20240611

- Worked on [edgeR analysis of Pacific cod RNA-seq](../2024-06-12-Differential-Gene-Expression---G.macrocephalus-RNA-seq-9C-vs-16C-Using-edgeR/index.qmd) (Notebook).

## 20240610

### In lab

- Began prepping for [RNA isolations for the _C.gigas_ lifestage carryover project](https://github.com/RobertsLab/resources/issues/1891) (GitHub Issue). Spent majority of time labeling tubes.

### CEABIGR

- CEABIGR manuscript revisions meeting.


## 20240607

### Hack-a-thon

- Miscellaneous stuff. Not too many people in attendance.

## 20240606

### Hack-a-thon

- In lab. Cleaned up boxes and stuff leftover from new Synology NAS install.

- Updated READMEs in a few different repos.

## 20240605

### Hack-a-thon

- Worked on coral E5 manuscript.

- Worked on Pychnopodia BLASTing of unmapped reads.--

- Miscellaneous repo maintenance.


## 20240604

### Hack-a-thon

- In lab. [Got Manilla clam egg samples from Mac](../2024-06-04-Samples-Received---Lajonkairia-lajonkairii-Egg-Samples-from-Mackenzie-Gavery/index.qmd).

- Helped Chris with transferring data from her computer to Raven.


## 20240603

### Hack-a-thon

- Helped Steven get SSH authorization for GitHub.

- Tried to sign up with `.edu` email address for free access to GitHub Copilot (not sure if this worked yet).

- Finished notebook for _G.macrocephalus_ [gDNA gel](../2024-05-31-Agarose-Gel---G.macrocephalus-gDNA-from-20240521/index.qmd).

- Dealt with annoying/weird notebook rendering issue.

- Began downloading NCBI `nt` BLAST database (literally took the entire day).