<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sam White">
<meta name="dcterms.date" content="2026-08-03">

<title>Glycogen Assay - SORMI June 2026 M.gigas USDA Families 1 and 9 Sample Re-runs – Sam’s Notebook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../..//images/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-e518e50a9807db09b51ea894c4c266f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 2,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 100,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7483T61T11"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-7483T61T11', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Sam’s Notebook</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-hdd-network" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-hdd-network" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-hdd-network">    
        <li>
    <a class="dropdown-item" href="http://raven.fish.washington.edu:8787" target="_blank">
 <span class="dropdown-text">Rstudio Server - Raven</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://gannet.fish.washington.edu/Atumefaciens/" target="_blank">
 <span class="dropdown-text">My Gannet Directory</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-journal-code" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-journal-code" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-journal-code">    
        <li>
    <a class="dropdown-item" href="https://sr320.github.io/tumbling-oysters/" target="_blank">
 <span class="dropdown-text">Steven’s Notebook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://shedurkin.github.io/Roberts-LabNotebook/" target="_blank">
 <span class="dropdown-text">Kathleen’s Notebook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://meganewing.github.io/mewing-notebook/" target="_blank">
 <span class="dropdown-text">Megan’s Notebook</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/RobertsLab/sams-notebook" target="_blank">
 <span class="dropdown-text">Notebook repo</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/RobertsLab" target="_blank">
 <span class="dropdown-text">Lab Organization (GitHub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/RobertsLab/lab-website" target="_blank">
 <span class="dropdown-text">Edit Roberts Lab website</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://calendar.google.com/calendar/embed?src=mrc305@gmail.com&amp;ctz=America/Vancouver" target="_blank"> <i class="bi bi-calendar-week" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-right">
      <h1 class="title">Glycogen Assay - SORMI June 2026 M.gigas USDA Families 1 and 9 Sample Re-runs</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">2026</div>
                <div class="quarto-category">glycogen</div>
                <div class="quarto-category">Glycogen-Glo</div>
                <div class="quarto-category">SORMI</div>
                <div class="quarto-category">Pacific oyster</div>
                <div class="quarto-category">Magallana gigas</div>
                <div class="quarto-category">Crassostrea gigas</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-right">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Sam White </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 3, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#intro" id="toc-intro" class="nav-link active" data-scroll-target="#intro">INTRO</a></li>
  <li><a href="#materials-methods" id="toc-materials-methods" class="nav-link" data-scroll-target="#materials-methods">MATERIALS &amp; METHODS</a>
  <ul>
  <li><a href="#dilutions" id="toc-dilutions" class="nav-link" data-scroll-target="#dilutions">Dilutions</a></li>
  <li><a href="#glycogen-assay" id="toc-glycogen-assay" class="nav-link" data-scroll-target="#glycogen-assay">Glycogen Assay</a>
  <ul>
  <li><a href="#master-mix-calcs" id="toc-master-mix-calcs" class="nav-link" data-scroll-target="#master-mix-calcs">Master Mix Calcs</a>
  <ul class="collapse">
  <li><a href="#digestion-master-mix" id="toc-digestion-master-mix" class="nav-link" data-scroll-target="#digestion-master-mix">Digestion Master Mix</a></li>
  <li><a href="#detection-master-mix" id="toc-detection-master-mix" class="nav-link" data-scroll-target="#detection-master-mix">Detection Master Mix</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data Analysis</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">RESULTS</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">1 BACKGROUND</a>
  <ul>
  <li><a href="#sample-naming" id="toc-sample-naming" class="nav-link" data-scroll-target="#sample-naming">1.1 Sample naming</a></li>
  <li><a href="#important-notes" id="toc-important-notes" class="nav-link" data-scroll-target="#important-notes">1.2 Important note(s)</a></li>
  </ul></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">2 SETUP</a>
  <ul>
  <li><a href="#libraries" id="toc-libraries" class="nav-link" data-scroll-target="#libraries">2.1 Libraries</a></li>
  <li><a href="#output-directory" id="toc-output-directory" class="nav-link" data-scroll-target="#output-directory">2.2 Output directory</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">3 DATA</a>
  <ul>
  <li><a href="#reshape-plate-to-long-format" id="toc-reshape-plate-to-long-format" class="nav-link" data-scroll-target="#reshape-plate-to-long-format">3.1 Reshape plate to long format</a></li>
  </ul></li>
  <li><a href="#standard-curve" id="toc-standard-curve" class="nav-link" data-scroll-target="#standard-curve">4 STANDARD CURVE</a>
  <ul>
  <li><a href="#extract-luminescence-data" id="toc-extract-luminescence-data" class="nav-link" data-scroll-target="#extract-luminescence-data">4.1 Extract luminescence data</a></li>
  <li><a href="#glycogen-standard-curve-summary-statistics-and-linear-regression" id="toc-glycogen-standard-curve-summary-statistics-and-linear-regression" class="nav-link" data-scroll-target="#glycogen-standard-curve-summary-statistics-and-linear-regression">4.2 Glycogen standard curve summary statistics and linear regression</a></li>
  <li><a href="#extract-sample-data-and-calculate-glycogen-levels" id="toc-extract-sample-data-and-calculate-glycogen-levels" class="nav-link" data-scroll-target="#extract-sample-data-and-calculate-glycogen-levels">4.3 Extract sample data and calculate glycogen levels</a></li>
  <li><a href="#plot-standard-curve-with-re-assayed-sample-points" id="toc-plot-standard-curve-with-re-assayed-sample-points" class="nav-link" data-scroll-target="#plot-standard-curve-with-re-assayed-sample-points">4.4 Plot standard curve with re-assayed sample points</a></li>
  </ul></li>
  <li><a href="#quality-control" id="toc-quality-control" class="nav-link" data-scroll-target="#quality-control">5 QUALITY CONTROL</a>
  <ul>
  <li><a href="#technical-replicate-variability" id="toc-technical-replicate-variability" class="nav-link" data-scroll-target="#technical-replicate-variability">5.1 Technical replicate variability</a></li>
  <li><a href="#out-of-range-floor-effect-check" id="toc-out-of-range-floor-effect-check" class="nav-link" data-scroll-target="#out-of-range-floor-effect-check">5.2 Out-of-range / floor-effect check</a></li>
  </ul></li>
  <li><a href="#comparison-to-original-run" id="toc-comparison-to-original-run" class="nav-link" data-scroll-target="#comparison-to-original-run">6 COMPARISON TO ORIGINAL RUN</a>
  <ul>
  <li><a href="#plot-original-vs.-re-assayed-normalized-glycogen" id="toc-plot-original-vs.-re-assayed-normalized-glycogen" class="nav-link" data-scroll-target="#plot-original-vs.-re-assayed-normalized-glycogen">6.1 Plot: original vs.&nbsp;re-assayed normalized glycogen</a></li>
  </ul></li>
  <li><a href="#sample-glycogen-table" id="toc-sample-glycogen-table" class="nav-link" data-scroll-target="#sample-glycogen-table">7 SAMPLE GLYCOGEN TABLE</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">8 SUMMARY</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-right" id="quarto-document-content">





<section id="intro" class="level1">
<h1>INTRO</h1>
<p>As part of the June 2026 SORMI project, I conducted a glycogen assay on <em>Magallana gigas</em> (Pacific oyster) ctenidia samples (ambient and 36°C temperatures) from USDA Families 1 and 9 (chosen by Steven). The purpose of this study was to compare the glycogen content between these two families using the Glycogen Glo Kit. Samples had been <a href="../../../posts/2026/2026-07-22-Homogenization---June-2026-SORMI-M.gigas-Ctenidia-from-Families-1-and-9-for-Glycogen-Glo-Assay/index.html">previously homogenized on 20260722</a> (Notebook entry) as well as <a href="../../../posts/2026/2026-07-30-Glycogen-Assay---SORMI-June-2026-M.gigas-USDA-Families-1-and-9-Comparisons-Using-Glycogen-Glo-Kit/index.html">assayed for glycogen on 20260730</a> (Notebook entry). However, four samples were outside of the standard curve and one had poor coefficient of variation (CV) between replicates, so a re-run of those samples was necessary.</p>
<ul>
<li><p><code>1_06_ambient</code></p></li>
<li><p><code>1_08_ambient</code></p></li>
<li><p><code>1_04_36C</code></p></li>
<li><p><code>1_05_36C</code></p></li>
<li><p><code>9_05_ambient</code></p></li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sample <code>1_04_36C</code> was re-run due to poor CV between replicates in the previous assay attempt. It should have been processed with the previous 1:25 dilution, but was accidentally processed with a 1:200 dilution which resulted in a low signal.</p>
</div>
</div>
<p>All data/code/analysis is available here:</p>
<ul>
<li><a href="https://github.com/RobertsLab/sormi-assay-development/tree/main/Glycogen">https://github.com/RobertsLab/sormi-assay-development/tree/main/Glycogen</a></li>
</ul>
</section>
<section id="materials-methods" class="level1">
<h1>MATERIALS &amp; METHODS</h1>
<p>Homogenized ctenidia samples were thawed, vortexed, and spun at 16,000g for 1min to pellet debris. Based on <a href="../../../posts/2026/2026-07-30-Glycogen-Assay---SORMI-June-2026-M.gigas-USDA-Families-1-and-9-Comparisons-Using-Glycogen-Glo-Kit/index.html">the previous attempt at assaying these samples on 20260730</a> (Notebook) the following was decided upon:</p>
<ul>
<li><p>dilution of 1:200 should be appropriate for samples to fall within standard curve range</p></li>
<li><p>glucose analysis is unnecessary for <em>M.gigas</em> ctenidia samples, as glucose has been shown to be negligible</p></li>
</ul>
<section id="dilutions" class="level2">
<h2 class="anchored" data-anchor-id="dilutions">Dilutions</h2>
<p>All samples were diluted 1:200 in dilution buffer (2:1:1 ratio of PBS:0.3N HCl:TRIS). E.g. 1uL of sample + 199uL of dilution buffer. The diluted samples were then used for the glycogen assay.</p>
</section>
<section id="glycogen-assay" class="level2">
<h2 class="anchored" data-anchor-id="glycogen-assay">Glycogen Assay</h2>
<p>A standard curve of glycogen (20ug, 10ug, 2ug, 0.2ug, 0.02ug, 0ug) in PBS was prepared. The assay was performed in triplicate for each sample in a separate 96-well, white Costar plate, and luminescence readings were taken using a HTX Synergy plate reader (Agilent). A negative control (dilution buffer only), in triplicate, was included in the assay to account for background luminescence.</p>
<p>The assay was performed in triplicate for each sample in a 96-well, white Costar plate, and luminescence readings were taken using a HTX Synergy plate reader (Agilent).</p>
<p>The Glycogen Glo Kit protocol was followed according to the manufacturer’s instructions, with appropriate incubation times and reagent additions.</p>
<section id="master-mix-calcs" class="level3">
<h3 class="anchored" data-anchor-id="master-mix-calcs">Master Mix Calcs</h3>
<section id="digestion-master-mix" class="level4">
<h4 class="anchored" data-anchor-id="digestion-master-mix">Digestion Master Mix</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>COMPONENT</th>
<th>vol.per.rxn(uL)</th>
<th>no.rxns</th>
<th>total(uL)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>glucoamylase buffer</td>
<td>25</td>
<td>36</td>
<td>900</td>
</tr>
<tr class="even">
<td>glucoamylase</td>
<td>0.125</td>
<td>36</td>
<td>4.5</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>TOTAL</td>
<td>904.5</td>
</tr>
</tbody>
</table>
</section>
<section id="detection-master-mix" class="level4">
<h4 class="anchored" data-anchor-id="detection-master-mix">Detection Master Mix</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>COMPONENT</th>
<th>vol.per.rxn(uL)</th>
<th>no.rxns</th>
<th>total(uL)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>luciferin detection solution</td>
<td>50</td>
<td>36</td>
<td>1800</td>
</tr>
<tr class="even">
<td>reductase substrate</td>
<td>0.25</td>
<td>36</td>
<td>9</td>
</tr>
<tr class="odd">
<td>reductase</td>
<td>0.25</td>
<td>36</td>
<td>9</td>
</tr>
<tr class="even">
<td>NAD</td>
<td>0.25</td>
<td>36</td>
<td>9</td>
</tr>
<tr class="odd">
<td>glucose dehydrogenase</td>
<td>2</td>
<td>36</td>
<td>72</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>TOTAL</td>
<td>1899</td>
</tr>
</tbody>
</table>
</section>
</section>
</section>
<section id="data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis">Data Analysis</h2>
<p>Data was analyzed in the following R Markdown file:</p>
<ul>
<li><a href="https://github.com/RobertsLab/sormi-assay-development/blob/main/Glycogen/code/Gen5-20260803-mgig-fams1_9-glycogen-glo.Rmd">Gen5-20260803-mgig-fams1_9-glycogen-glo.Rmd</a> (GitHub)</li>
</ul>
<p>Analysis assessed the success of the new dilution factor (1:200).</p>
</section>
</section>
<section id="results" class="level1">
<h1>RESULTS</h1>
<p>A dilution factor of 1:200 was successful in bringing all samples within the standard curve range. Since I spaced out and also diluted the <code>1_04_36C</code> sample (which should have been kept at the original 1:25 dilution), the signal was low and the sample was below the standard curve. However, the other four samples were all within the standard curve range and had good CVs between replicates. I should re-assay <code>1_04_36C</code> <em>again</em>…</p>
<p><a href="https://robertslab.github.io/resources/Agentic-Coding-Tools/#five-level-rubric"><img alt="AI Use Level 4: Substantial AI contribution" src="https://img.shields.io/badge/AI%20Use-Level%204%20Substantial%20AI%20Contribution-red"></a></p>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This section was knitted from <a href="https://github.com/RobertsLab/sormi-assay-development/blob/main/Glycogen/code/Gen5-20260803-mgig-fams1_9-glycogen-glo.Rmd">Gen5-20260803-mgig-fams1_9-glycogen-glo.Rmd</a> (GitHub).</p>
</div>
</div>
</section>
<section id="background" class="level1">
<h1>1 BACKGROUND</h1>
<p>Targeted re-assay of five <em>Magallana gigas</em> (Pacific oyster) ctenidia samples from the 2026-07-30 glycogen run (<a href="../code/Gen5-20260730-mgig-fams1_9-glycogen-glo.md"><code>Gen5-20260730-mgig-fams1_9-glycogen-glo</code></a>) using the <a href="https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/Promega_Glycogen_Glo_Assay.pdf">Glycogen-Glo Assay (Promega)</a> (GitHub; PDF), read on 2026-08-03.</p>
<p>Four of these five samples read above the top standard (20 µg/mL) in the original run and required extrapolation: <code>1_08_ambient</code>, <code>1_06_ambient</code>, <code>1_05_36C</code>, <code>9_05_ambient</code>. The fifth, <code>1_04_36C</code>, was within range but had a technical-triplicate CV of 30.1%, above the 15% QC threshold used in the original analysis. All five were re-assayed here at a <strong>1:200 dilution</strong> (vs.&nbsp;1:25 originally, ~8× higher), using the same homogenate as the original run (tissue weights match exactly between runs).</p>
<p>This is a small, targeted follow-up analysis, not a full re-run of the 32-sample experiment. Results here are intended to supersede the corresponding five rows of the original run’s results table where the values differ meaningfully; see the Summary for a direct comparison and recommendation.</p>
<section id="sample-naming" class="level2">
<h2 class="anchored" data-anchor-id="sample-naming">1.1 Sample naming</h2>
<p>Per <a href="../data/raw_luminescence/README.md"><code>../data/raw_luminescence/README.md</code></a>, plate layout entries follow:</p>
<ul>
<li><code>&lt;sample&gt;-&lt;assay_type&gt;-&lt;tissue_weight&gt;-df.&lt;dilution_factor&gt;</code></li>
</ul>
<p>Here <code>&lt;sample&gt;</code> itself is composite:</p>
<ul>
<li><code>&lt;family&gt;_&lt;individual&gt;_&lt;temperature&gt;</code></li>
</ul>
<p>E.g. <code>1_06_ambient-glyc-11.0-df.200</code> is family 1, individual 06, ambient exposure, glycogen assay, 11.0 mg of ctenidia tissue, diluted 1:200.</p>
<p>Standards follow <code>STD-&lt;assay_type&gt;-&lt;concentration&gt;</code>, e.g.&nbsp;<code>STD-glyc-20</code> (20 µg/mL glycogen); the buffer-only well is <code>NEG-glyc</code>.</p>
</section>
<section id="important-notes" class="level2">
<h2 class="anchored" data-anchor-id="important-notes">1.2 Important note(s)</h2>
<ol type="1">
<li><strong>Tissue weights</strong> are taken from the plate layout labels rather than a separate weights CSV, and match the corresponding weights in the original 2026-07-30 run exactly, confirming these are re-assays of the same homogenates rather than newly prepared samples.</li>
</ol>
</section>
</section>
<section id="setup" class="level1">
<h1>2 SETUP</h1>
<section id="libraries" class="level2">
<h2 class="anchored" data-anchor-id="libraries">2.1 Libraries</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Attaching package: 'dplyr'

## The following objects are masked from 'package:stats':
## 
##     filter, lag

## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">echo =</span> <span class="cn">TRUE</span>,         <span class="co"># Display code chunks</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">eval =</span> <span class="cn">TRUE</span>,         <span class="co"># Evaluate code chunks</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">warning =</span> <span class="cn">FALSE</span>,     <span class="co"># Hide warnings</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">message =</span> <span class="cn">FALSE</span>,     <span class="co"># Hide messages</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">comment =</span> <span class="st">""</span>,        <span class="co"># Prevents appending '##' to beginning of lines in code output</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">results =</span> <span class="st">'hold'</span>     <span class="co"># Holds output so it's all printed together after code chunk</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="output-directory" class="level2">
<h2 class="anchored" data-anchor-id="output-directory">2.2 Output directory</h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Output directory for this analysis (matches this file's name, per ../code/README.md)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>output_dir <span class="ot">&lt;-</span> <span class="st">"../output/Gen5-20260803-mgig-fams1_9-glycogen-glo"</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(output_dir, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"--- output_dir: destination for all figures and tables ---</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(output_dir)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>--- output_dir: destination for all figures and tables ---
 chr "../output/Gen5-20260803-mgig-fams1_9-glycogen-glo"</code></pre>
</section>
</section>
<section id="data" class="level1">
<h1>3 DATA</h1>
<p>Data are read from the local repo (<code>../data/raw_luminescence/</code>) so this document renders before/after the files are pushed to GitHub. A single plate holds both the five re-assayed samples and the fresh standard curve/negative control.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data_dir <span class="ot">&lt;-</span> <span class="st">"../data/raw_luminescence"</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>plate_layout <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">file.path</span>(data_dir, <span class="st">"layout-Gen5-20260803-mgig-fams1_9-plate-01.csv"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">header =</span> <span class="cn">FALSE</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>raw_luminescence <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">file.path</span>(data_dir, <span class="st">"raw_lum-Gen5-20260803-mgig-fams1_9-plate-01.csv"</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">header =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Plate layout:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(plate_layout)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Raw luminescence:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(raw_luminescence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Plate layout:

'data.frame':   8 obs. of  12 variables:
 $ V1 : chr  "9_05-ambient-glyc-9.2-df.200" "1_05_36C-glyc-25.7-df.200" "STD-glyc-20" "STD-glyc-0.02" ...
 $ V2 : chr  "9_05-ambient-glyc-9.2-df.200" "1_05_36C-glyc-25.7-df.200" "STD-glyc-20" "STD-glyc-0.02" ...
 $ V3 : chr  "9_05-ambient-glyc-9.2-df.200" "1_05_36C-glyc-25.7-df.200" "STD-glyc-20" "STD-glyc-0.02" ...
 $ V4 : chr  "1_06_ambient-glyc-11.0-df.200" "" "STD-glyc-10" "STD-glyc-0" ...
 $ V5 : chr  "1_06_ambient-glyc-11.0-df.200" "" "STD-glyc-10" "STD-glyc-0" ...
 $ V6 : chr  "1_06_ambient-glyc-11.0-df.200" "" "STD-glyc-10" "STD-glyc-0" ...
 $ V7 : chr  "1_08_ambient-glyc-24.8-df.200" "" "STD-glyc-2" "" ...
 $ V8 : chr  "1_08_ambient-glyc-24.8-df.200" "" "STD-glyc-2" "" ...
 $ V9 : chr  "1_08_ambient-glyc-24.8-df.200" "" "STD-glyc-2" "" ...
 $ V10: chr  "1_04_36C-glyc-12.4-df.200" "" "STD-glyc-0.2" "" ...
 $ V11: chr  "1_04_36C-glyc-12.4-df.200" "" "STD-glyc-0.2" "" ...
 $ V12: chr  "1_04_36C-glyc-12.4-df.200" "" "STD-glyc-0.2" "" ...

Raw luminescence:

'data.frame':   8 obs. of  12 variables:
 $ V1 : int  6528 8906 61432 804 570 7 8 3
 $ V2 : int  6498 8471 62800 631 576 5 8 6
 $ V3 : int  6599 8849 60190 608 604 7 4 5
 $ V4 : int  9137 29 28374 499 9 9 5 4
 $ V5 : int  9214 19 27652 418 4 5 3 4
 $ V6 : int  9304 16 28683 21 7 4 7 4
 $ V7 : int  31079 30 11790 10 7 4 7 5
 $ V8 : int  30545 27 12124 10 6 8 5 2
 $ V9 : int  30678 21 12465 11 9 5 4 2
 $ V10: int  833 12 3474 8 5 4 6 8
 $ V11: int  776 5 1771 6 6 4 3 4
 $ V12: int  860 6 1415 5 5 4 5 4</code></pre>
<section id="reshape-plate-to-long-format" class="level2">
<h2 class="anchored" data-anchor-id="reshape-plate-to-long-format">3.1 Reshape plate to long format</h2>
<div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert a paired layout/luminescence plate into one row per well</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>plate_to_long <span class="ot">&lt;-</span> <span class="cf">function</span>(layout, luminescence, plate_label) {</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  n_row <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  n_col <span class="ot">&lt;-</span> <span class="dv">12</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">plate_row_idx =</span> <span class="dv">1</span><span class="sc">:</span>n_row, <span class="at">plate_col =</span> <span class="dv">1</span><span class="sc">:</span>n_col)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  out<span class="sc">$</span>plate       <span class="ot">&lt;-</span> plate_label</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  out<span class="sc">$</span>plate_row   <span class="ot">&lt;-</span> LETTERS[out<span class="sc">$</span>plate_row_idx]</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  out<span class="sc">$</span>well        <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"%s%02d"</span>, out<span class="sc">$</span>plate_row, out<span class="sc">$</span>plate_col)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  out<span class="sc">$</span>label       <span class="ot">&lt;-</span> <span class="fu">trimws</span>(<span class="fu">as.character</span>(<span class="fu">mapply</span>(<span class="cf">function</span>(i, j) layout[i, j],</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>                                                out<span class="sc">$</span>plate_row_idx, out<span class="sc">$</span>plate_col)))</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  out<span class="sc">$</span>luminescence <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">mapply</span>(<span class="cf">function</span>(i, j) luminescence[i, j],</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>                                        out<span class="sc">$</span>plate_row_idx, out<span class="sc">$</span>plate_col))</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> out[<span class="fu">order</span>(out<span class="sc">$</span>plate_row_idx, out<span class="sc">$</span>plate_col), ]</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  out[out<span class="sc">$</span>label <span class="sc">!=</span> <span class="st">""</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(out<span class="sc">$</span>label), ]</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>plate1_long <span class="ot">&lt;-</span> <span class="fu">plate_to_long</span>(plate_layout, raw_luminescence, <span class="st">"plate-01"</span>)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"--- plate_to_long(): layout + luminescence -&gt; one row per well ---</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(<span class="fu">args</span>(plate_to_long))</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- plate1_long: one row per occupied well ---</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(plate1_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>--- plate_to_long(): layout + luminescence -&gt; one row per well ---

function (layout, luminescence, plate_label)  

--- plate1_long: one row per occupied well ---

'data.frame':   36 obs. of  7 variables:
 $ plate_row_idx: int  1 1 1 1 1 1 1 1 1 1 ...
 $ plate_col    : int  1 2 3 4 5 6 7 8 9 10 ...
 $ plate        : chr  "plate-01" "plate-01" "plate-01" "plate-01" ...
 $ plate_row    : chr  "A" "A" "A" "A" ...
 $ well         : chr  "A01" "A02" "A03" "A04" ...
 $ label        : chr  "9_05-ambient-glyc-9.2-df.200" "9_05-ambient-glyc-9.2-df.200" "9_05-ambient-glyc-9.2-df.200" "1_06_ambient-glyc-11.0-df.200" ...
 $ luminescence : num  6528 6498 6599 9137 9214 ...
 - attr(*, "out.attrs")=List of 2
  ..$ dim     : Named int [1:2] 8 12
  .. ..- attr(*, "names")= chr [1:2] "plate_row_idx" "plate_col"
  ..$ dimnames:List of 2
  .. ..$ plate_row_idx: chr [1:8] "plate_row_idx=1" "plate_row_idx=2" "plate_row_idx=3" "plate_row_idx=4" ...
  .. ..$ plate_col    : chr [1:12] "plate_col= 1" "plate_col= 2" "plate_col= 3" "plate_col= 4" ...</code></pre>
</section>
</section>
<section id="standard-curve" class="level1">
<h1>4 STANDARD CURVE</h1>
<section id="extract-luminescence-data" class="level2">
<h2 class="anchored" data-anchor-id="extract-luminescence-data">4.1 Extract luminescence data</h2>
<p>Row C holds the 20, 10, 2, and 0.2 µg/mL standards; row D holds the 0.02 and 0 µg/mL standards; row E columns 1-3 hold the <code>NEG-glyc</code> buffer-only negative control – all in triplicate, on the same plate as the re-assayed samples.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>standards <span class="ot">&lt;-</span> plate1_long <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"^STD-glyc-"</span>, label)) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">glyc_concentration =</span> <span class="fu">as.numeric</span>(<span class="fu">sub</span>(<span class="st">"^STD-glyc-"</span>, <span class="st">""</span>, label)))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>negative_control <span class="ot">&lt;-</span> plate1_long <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"^NEG-glyc"</span>, label))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Standard concentrations (ug/mL):"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(standards<span class="sc">$</span>glyc_concentration)), <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Replicates per standard:"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(<span class="fu">unique</span>(<span class="fu">table</span>(standards<span class="sc">$</span>glyc_concentration)), <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Negative control (buffer only) luminescence:"</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(negative_control<span class="sc">$</span>luminescence, <span class="at">collapse =</span> <span class="st">", "</span>),</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"| mean ="</span>, <span class="fu">round</span>(<span class="fu">mean</span>(negative_control<span class="sc">$</span>luminescence), <span class="dv">1</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Zero glycogen standard luminescence:  mean ="</span>,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(<span class="fu">mean</span>(standards<span class="sc">$</span>luminescence[standards<span class="sc">$</span>glyc_concentration <span class="sc">==</span> <span class="dv">0</span>]), <span class="dv">1</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- standards: standard curve wells with parsed concentration ---</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(standards)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- negative_control: buffer-only wells ---</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(negative_control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Standard concentrations (ug/mL): 0, 0.02, 0.2, 2, 10, 20 
Replicates per standard: 3 

Negative control (buffer only) luminescence: 570, 576, 604 | mean = 583.3 
Zero glycogen standard luminescence:  mean = 312.7 

--- standards: standard curve wells with parsed concentration ---
'data.frame':   18 obs. of  8 variables:
 $ plate_row_idx     : int  3 3 3 3 3 3 3 3 3 3 ...
 $ plate_col         : int  1 2 3 4 5 6 7 8 9 10 ...
 $ plate             : chr  "plate-01" "plate-01" "plate-01" "plate-01" ...
 $ plate_row         : chr  "C" "C" "C" "C" ...
 $ well              : chr  "C01" "C02" "C03" "C04" ...
 $ label             : chr  "STD-glyc-20" "STD-glyc-20" "STD-glyc-20" "STD-glyc-10" ...
 $ luminescence      : num  61432 62800 60190 28374 27652 ...
 $ glyc_concentration: num  20 20 20 10 10 10 2 2 2 0.2 ...
 - attr(*, "out.attrs")=List of 2
  ..$ dim     : Named int [1:2] 8 12
  .. ..- attr(*, "names")= chr [1:2] "plate_row_idx" "plate_col"
  ..$ dimnames:List of 2
  .. ..$ plate_row_idx: chr [1:8] "plate_row_idx=1" "plate_row_idx=2" "plate_row_idx=3" "plate_row_idx=4" ...
  .. ..$ plate_col    : chr [1:12] "plate_col= 1" "plate_col= 2" "plate_col= 3" "plate_col= 4" ...

--- negative_control: buffer-only wells ---
'data.frame':   3 obs. of  7 variables:
 $ plate_row_idx: int  5 5 5
 $ plate_col    : int  1 2 3
 $ plate        : chr  "plate-01" "plate-01" "plate-01"
 $ plate_row    : chr  "E" "E" "E"
 $ well         : chr  "E01" "E02" "E03"
 $ label        : chr  "NEG-glyc" "NEG-glyc" "NEG-glyc"
 $ luminescence : num  570 576 604
 - attr(*, "out.attrs")=List of 2
  ..$ dim     : Named int [1:2] 8 12
  .. ..- attr(*, "names")= chr [1:2] "plate_row_idx" "plate_col"
  ..$ dimnames:List of 2
  .. ..$ plate_row_idx: chr [1:8] "plate_row_idx=1" "plate_row_idx=2" "plate_row_idx=3" "plate_row_idx=4" ...
  .. ..$ plate_col    : chr [1:12] "plate_col= 1" "plate_col= 2" "plate_col= 3" "plate_col= 4" ...</code></pre>
<p>The buffer-only negative control and the zero-glycogen standard are again in close agreement (913 vs.&nbsp;910 RLU in the original run; see below), as expected.</p>
</section>
<section id="glycogen-standard-curve-summary-statistics-and-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="glycogen-standard-curve-summary-statistics-and-linear-regression">4.2 Glycogen standard curve summary statistics and linear regression</h2>
<div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>glycogen_summary_data <span class="ot">&lt;-</span> standards <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(glyc_concentration) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">glyc_mean_luminescence =</span> <span class="fu">mean</span>(luminescence),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">glyc_sd                =</span> <span class="fu">sd</span>(luminescence),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">glyc_se                =</span> <span class="fu">sd</span>(luminescence) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">n</span>()),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">glyc_cv                =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">sd</span>(luminescence) <span class="sc">/</span> <span class="fu">mean</span>(luminescence),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">glyc_n                 =</span> <span class="fu">n</span>(),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(glyc_concentration)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>lm_model      <span class="ot">&lt;-</span> <span class="fu">lm</span>(glyc_mean_luminescence <span class="sc">~</span> glyc_concentration, <span class="at">data =</span> glycogen_summary_data)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>glyc_slope     <span class="ot">&lt;-</span> <span class="fu">coef</span>(lm_model)[<span class="dv">2</span>]</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>glyc_intercept <span class="ot">&lt;-</span> <span class="fu">coef</span>(lm_model)[<span class="dv">1</span>]</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>glyc_r_squared <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_model)<span class="sc">$</span>r.squared</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>lm_model_reps    <span class="ot">&lt;-</span> <span class="fu">lm</span>(luminescence <span class="sc">~</span> glyc_concentration, <span class="at">data =</span> standards)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>glyc_r2_reps     <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_model_reps)<span class="sc">$</span>r.squared</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>glyc_conc_min_nonzero <span class="ot">&lt;-</span> <span class="fu">min</span>(glycogen_summary_data<span class="sc">$</span>glyc_concentration[</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>  glycogen_summary_data<span class="sc">$</span>glyc_concentration <span class="sc">&gt;</span> <span class="dv">0</span>])</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>glyc_conc_max <span class="ot">&lt;-</span> <span class="fu">max</span>(glycogen_summary_data<span class="sc">$</span>glyc_concentration)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(glycogen_summary_data,</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">0</span>),</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Glycogen (ug/mL)"</span>, <span class="st">"Mean luminescence"</span>, <span class="st">"SD"</span>, <span class="st">"SEM"</span>, <span class="st">"CV (%)"</span>, <span class="st">"n"</span>),</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Glycogen standard curve summary statistics (this plate)"</span>)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Fit to concentration means:      y ="</span>, <span class="fu">sprintf</span>(<span class="st">"%.1f"</span>, glyc_slope), <span class="st">"x +"</span>,</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%.1f"</span>, glyc_intercept), <span class="st">" R^2 ="</span>, <span class="fu">sprintf</span>(<span class="st">"%.4f"</span>, glyc_r_squared), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Fit to individual replicates:    R^2 ="</span>, <span class="fu">sprintf</span>(<span class="st">"%.4f"</span>, glyc_r2_reps), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Quantifiable range (standards):"</span>, glyc_conc_min_nonzero, <span class="st">"-"</span>, glyc_conc_max, <span class="st">"ug/mL</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- glycogen_summary_data: per-concentration summary statistics ---</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(glycogen_summary_data)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- lm_model: regression on per-concentration means ---</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(lm_model, <span class="at">max.level =</span> <span class="dv">1</span>, <span class="at">give.attr =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Glycogen (ug/mL)</th>
<th style="text-align: right;">Mean luminescence</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">SEM</th>
<th style="text-align: right;">CV (%)</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">312.7</td>
<td style="text-align: right;">255.8</td>
<td style="text-align: right;">147.7</td>
<td style="text-align: right;">81.82</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">681.0</td>
<td style="text-align: right;">107.1</td>
<td style="text-align: right;">61.9</td>
<td style="text-align: right;">15.73</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">2220.0</td>
<td style="text-align: right;">1100.5</td>
<td style="text-align: right;">635.4</td>
<td style="text-align: right;">49.57</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">12126.3</td>
<td style="text-align: right;">337.5</td>
<td style="text-align: right;">194.9</td>
<td style="text-align: right;">2.78</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">28236.3</td>
<td style="text-align: right;">529.1</td>
<td style="text-align: right;">305.5</td>
<td style="text-align: right;">1.87</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">20.00</td>
<td style="text-align: right;">61474.0</td>
<td style="text-align: right;">1305.5</td>
<td style="text-align: right;">753.7</td>
<td style="text-align: right;">2.12</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
<p>Glycogen standard curve summary statistics (this plate)</p>
<pre><code>Fit to concentration means:      y = 2937.7 x + 1733.0  R^2 = 0.9886 
Fit to individual replicates:    R^2 = 0.9878 
Quantifiable range (standards): 0.02 - 20 ug/mL

--- glycogen_summary_data: per-concentration summary statistics ---
tibble [6 × 6] (S3: tbl_df/tbl/data.frame)
 $ glyc_concentration    : num [1:6] 0 0.02 0.2 2 10 20
 $ glyc_mean_luminescence: num [1:6] 313 681 2220 12126 28236 ...
 $ glyc_sd               : num [1:6] 256 107 1100 338 529 ...
 $ glyc_se               : num [1:6] 147.7 61.9 635.4 194.9 305.5 ...
 $ glyc_cv               : num [1:6] 81.82 15.73 49.57 2.78 1.87 ...
 $ glyc_n                : int [1:6] 3 3 3 3 3 3

--- lm_model: regression on per-concentration means ---
List of 12
 $ coefficients : Named num [1:2] 1733 2938
 $ residuals    : Named num [1:6] -1420 -1111 -100 4518 -2874 ...
 $ effects      : Named num [1:6] -42887 53448 426 4987 -2659 ...
 $ rank         : int 2
 $ fitted.values: Named num [1:6] 1733 1792 2320 7608 31110 ...
 $ assign       : int [1:2] 0 1
 $ qr           :List of 5
 $ df.residual  : int 4
 $ xlevels      : Named list()
 $ call         : language lm(formula = glyc_mean_luminescence ~ glyc_concentration, data = glycogen_summary_data)
 $ terms        :Classes 'terms', 'formula'  language glyc_mean_luminescence ~ glyc_concentration
 $ model        :'data.frame':  6 obs. of  2 variables:</code></pre>
<p><strong>Standard curve QC note.</strong> The 0 and 0.2 µg/mL standards show high triplicate CV (81.8% and 49.6% respectively) – both are low-signal wells where a small absolute RLU difference translates to a large percentage swing, and one 0 µg/mL well (21 RLU) reads well below its two replicates (499, 418 RLU). Excluding that single well changes the fitted slope/intercept by &lt;2%, and has a negligible effect on back-calculated concentrations for the samples below (e.g.&nbsp;<code>1_04_36C</code>’s well concentration shifts from -0.310 to -0.323 µg/mL) – this variability at the assay’s low end does not materially affect the regression, but it is consistent with <code>1_04_36C</code> reading close enough to background that its sign is not reliable (see Out-of-range / floor-effect check below). The curve overall fits tightly (R^2 = 0.9886, individual-replicate R^2 = 0.9878), consistent with the original run’s standard curve quality.</p>
</section>
<section id="extract-sample-data-and-calculate-glycogen-levels" class="level2">
<h2 class="anchored" data-anchor-id="extract-sample-data-and-calculate-glycogen-levels">4.3 Extract sample data and calculate glycogen levels</h2>
<div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>samples_wells <span class="ot">&lt;-</span> plate1_long <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"^STD-glyc-"</span>, label) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"^NEG-glyc"</span>, label)) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Normalize `-` to `_` in the &lt;family&gt;-&lt;individual&gt;-&lt;temperature&gt; prefix</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label_clean =</span> <span class="fu">sub</span>(<span class="st">"^([19])[-_]([0-9]{2})[-_](ambient|36C)-"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1_</span><span class="sc">\\</span><span class="st">2_</span><span class="sc">\\</span><span class="st">3-"</span>, label)) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_id  =</span> <span class="fu">sub</span>(<span class="st">"-glyc-.*$"</span>, <span class="st">""</span>, label_clean),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">family     =</span> <span class="fu">sub</span>(<span class="st">"^([19])_.*$"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, label_clean),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">individual =</span> <span class="fu">sub</span>(<span class="st">"^[19]_([0-9]{2})_.*$"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, label_clean),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">temperature =</span> <span class="fu">sub</span>(<span class="st">"^[19]_[0-9]{2}_([^-]+)-.*$"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, label_clean),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">weight_mg  =</span> <span class="fu">as.numeric</span>(<span class="fu">sub</span>(<span class="st">"^.*-glyc-([0-9.]+)-df</span><span class="sc">\\</span><span class="st">..*$"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, label_clean)),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">dilution   =</span> <span class="fu">as.numeric</span>(<span class="fu">sub</span>(<span class="st">"^.*-df</span><span class="sc">\\</span><span class="st">."</span>, <span class="st">""</span>, label_clean))</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">family      =</span> <span class="fu">factor</span>(<span class="fu">paste</span>(<span class="st">"Family"</span>, family), <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Family 1"</span>, <span class="st">"Family 9"</span>)),</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">temperature =</span> <span class="fu">factor</span>(temperature, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"ambient"</span>, <span class="st">"36C"</span>))</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Fail loudly rather than silently dropping malformed labels</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">any</span>(<span class="fu">is.na</span>(samples_wells<span class="sc">$</span>weight_mg)),</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>          <span class="sc">!</span><span class="fu">any</span>(<span class="fu">is.na</span>(samples_wells<span class="sc">$</span>dilution)),</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>          <span class="sc">!</span><span class="fu">any</span>(<span class="fu">is.na</span>(samples_wells<span class="sc">$</span>temperature)))</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Wells parsed:"</span>, <span class="fu">nrow</span>(samples_wells),</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"| unique samples:"</span>, <span class="fu">length</span>(<span class="fu">unique</span>(samples_wells<span class="sc">$</span>sample_id)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Dilution factor(s) used:"</span>, <span class="fu">paste</span>(<span class="fu">unique</span>(samples_wells<span class="sc">$</span>dilution), <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Samples re-assayed:"</span>, <span class="fu">paste</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(samples_wells<span class="sc">$</span>sample_id)), <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Tissue weight range (mg):"</span>,</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(<span class="fu">range</span>(samples_wells<span class="sc">$</span>weight_mg), <span class="at">collapse =</span> <span class="st">" - "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- samples_wells: one row per sample well, metadata parsed from label ---</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(samples_wells)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Wells parsed: 15 | unique samples: 5 
Dilution factor(s) used: 200 

Samples re-assayed: 1_04_36C, 1_05_36C, 1_06_ambient, 1_08_ambient, 9_05_ambient 
Tissue weight range (mg): 9.2 - 25.7 

--- samples_wells: one row per sample well, metadata parsed from label ---
'data.frame':   15 obs. of  14 variables:
 $ plate_row_idx: int  1 1 1 1 1 1 1 1 1 1 ...
 $ plate_col    : int  1 2 3 4 5 6 7 8 9 10 ...
 $ plate        : chr  "plate-01" "plate-01" "plate-01" "plate-01" ...
 $ plate_row    : chr  "A" "A" "A" "A" ...
 $ well         : chr  "A01" "A02" "A03" "A04" ...
 $ label        : chr  "9_05-ambient-glyc-9.2-df.200" "9_05-ambient-glyc-9.2-df.200" "9_05-ambient-glyc-9.2-df.200" "1_06_ambient-glyc-11.0-df.200" ...
 $ luminescence : num  6528 6498 6599 9137 9214 ...
 $ label_clean  : chr  "9_05_ambient-glyc-9.2-df.200" "9_05_ambient-glyc-9.2-df.200" "9_05_ambient-glyc-9.2-df.200" "1_06_ambient-glyc-11.0-df.200" ...
 $ sample_id    : chr  "9_05_ambient" "9_05_ambient" "9_05_ambient" "1_06_ambient" ...
 $ family       : Factor w/ 2 levels "Family 1","Family 9": 2 2 2 1 1 1 1 1 1 1 ...
 $ individual   : chr  "05" "05" "05" "06" ...
 $ temperature  : Factor w/ 2 levels "ambient","36C": 1 1 1 1 1 1 1 1 1 2 ...
 $ weight_mg    : num  9.2 9.2 9.2 11 11 11 24.8 24.8 24.8 12.4 ...
 $ dilution     : num  200 200 200 200 200 200 200 200 200 200 ...
 - attr(*, "out.attrs")=List of 2
  ..$ dim     : Named int [1:2] 8 12
  .. ..- attr(*, "names")= chr [1:2] "plate_row_idx" "plate_col"
  ..$ dimnames:List of 2
  .. ..$ plate_row_idx: chr [1:8] "plate_row_idx=1" "plate_row_idx=2" "plate_row_idx=3" "plate_row_idx=4" ...
  .. ..$ plate_col    : chr [1:12] "plate_col= 1" "plate_col= 2" "plate_col= 3" "plate_col= 4" ...</code></pre>
<p>Per-sample values are computed identically to the original analysis: mean of the technical triplicate, back-calculated through this plate’s own standard curve.</p>
<ol type="1">
<li><strong>Well concentration</strong> = <code>(mean luminescence - intercept) / slope</code> → µg/mL in the assayed (diluted) well.</li>
<li><strong>Homogenate concentration</strong> = well concentration × dilution factor (200) → µg/mL in the undiluted homogenate.</li>
<li><strong>Normalized glycogen</strong> = homogenate concentration / tissue weight → µg/mL per mg tissue.</li>
</ol>
<div class="sourceCode" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>sample_glycogen <span class="ot">&lt;-</span> samples_wells <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sample_id, family, individual, temperature, weight_mg, dilution) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_reps        =</span> <span class="fu">n</span>(),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_lum      =</span> <span class="fu">mean</span>(luminescence),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_lum        =</span> <span class="fu">sd</span>(luminescence),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">cv_lum        =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">sd</span>(luminescence) <span class="sc">/</span> <span class="fu">mean</span>(luminescence),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">well_conc_ug_mL       =</span> (mean_lum <span class="sc">-</span> glyc_intercept) <span class="sc">/</span> glyc_slope,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">homogenate_conc_ug_mL =</span> well_conc_ug_mL <span class="sc">*</span> dilution,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">norm_glycogen         =</span> homogenate_conc_ug_mL <span class="sc">/</span> weight_mg,</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">in_std_range          =</span> well_conc_ug_mL <span class="sc">&gt;=</span> glyc_conc_min_nonzero <span class="sc">&amp;</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>                            well_conc_ug_mL <span class="sc">&lt;=</span> glyc_conc_max</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(family, temperature, individual)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Samples quantified:"</span>, <span class="fu">nrow</span>(sample_glycogen), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- sample_glycogen: one row per individual, triplicate averaged and back-calculated ---</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sample_glycogen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Samples quantified: 5 

--- sample_glycogen: one row per individual, triplicate averaged and back-calculated ---
tibble [5 × 14] (S3: tbl_df/tbl/data.frame)
 $ sample_id            : chr [1:5] "1_06_ambient" "1_08_ambient" "1_04_36C" "1_05_36C" ...
 $ family               : Factor w/ 2 levels "Family 1","Family 9": 1 1 1 1 2
 $ individual           : chr [1:5] "06" "08" "04" "05" ...
 $ temperature          : Factor w/ 2 levels "ambient","36C": 1 1 2 2 1
 $ weight_mg            : num [1:5] 11 24.8 12.4 25.7 9.2
 $ dilution             : num [1:5] 200 200 200 200 200
 $ n_reps               : int [1:5] 3 3 3 3 3
 $ mean_lum             : num [1:5] 9218 30767 823 8742 6542
 $ sd_lum               : num [1:5] 83.6 278 42.9 236.4 51.9
 $ cv_lum               : num [1:5] 0.907 0.903 5.211 2.704 0.793
 $ well_conc_ug_mL      : num [1:5] 2.55 9.88 -0.31 2.39 1.64
 $ homogenate_conc_ug_mL: num [1:5] 510 1977 -62 477 327
 $ norm_glycogen        : num [1:5] 46.3 79.7 -5 18.6 35.6
 $ in_std_range         : logi [1:5] TRUE TRUE FALSE TRUE TRUE</code></pre>
</section>
<section id="plot-standard-curve-with-re-assayed-sample-points" class="level2">
<h2 class="anchored" data-anchor-id="plot-standard-curve-with-re-assayed-sample-points">4.4 Plot standard curve with re-assayed sample points</h2>
<div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>std_curve_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(glycogen_summary_data,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">aes</span>(<span class="at">x =</span> glyc_concentration, <span class="at">y =</span> glyc_mean_luminescence)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"grey60"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> glyc_mean_luminescence <span class="sc">-</span> glyc_se,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> glyc_mean_luminescence <span class="sc">+</span> glyc_se), <span class="at">width =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"#3182bd"</span>) <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> sample_glycogen,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> well_conc_ug_mL, <span class="at">y =</span> mean_lum, <span class="at">shape =</span> in_std_range),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"#d94801"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">`</span><span class="at">TRUE</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">16</span>, <span class="st">`</span><span class="at">FALSE</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">4</span>),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">`</span><span class="at">TRUE</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"in range"</span>, <span class="st">`</span><span class="at">FALSE</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"out of range / floor"</span>),</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">name =</span> <span class="st">"Re-assayed sample"</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Glycogen standard curve (this plate) with re-assayed sample points"</span>,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Glycogen (ug/mL)"</span>, <span class="at">y =</span> <span class="st">"Mean luminescence (RLU)"</span>) <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"--- std_curve_plot: ggplot object structure ---</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(std_curve_plot)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(output_dir, <span class="st">"glycogen_standard_curve_rerun.png"</span>), std_curve_plot,</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">10</span>, <span class="at">height =</span> <span class="dv">6</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>std_curve_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Gen5-20260803-mgig-fams1_9-glycogen-glo_files/figure-gfm/plot-glycogen-standard-curve-1.png" class="img-fluid"><!-- --></p>
<pre><code>--- std_curve_plot: ggplot object structure ---

data: glyc_concentration, glyc_mean_luminescence, glyc_sd, glyc_se,
  glyc_cv, glyc_n [6x6]
mapping:  x = ~glyc_concentration, y = ~glyc_mean_luminescence
scales:   shape 
faceting:  &lt;empty&gt; 
-----------------------------------
geom_smooth: na.rm = FALSE, orientation = NA, se = FALSE
stat_smooth: na.rm = FALSE, orientation = NA, se = FALSE, method = lm
position_identity 

mapping: ymin = ~glyc_mean_luminescence - glyc_se, ymax = ~glyc_mean_luminescence + glyc_se 
geom_errorbar: na.rm = FALSE, orientation = NA, lineend = butt, width = 0.3
stat_identity: na.rm = FALSE
position_identity 

geom_point: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity 

mapping: x = ~well_conc_ug_mL, y = ~mean_lum, shape = ~in_std_range 
geom_point: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity </code></pre>
</section>
</section>
<section id="quality-control" class="level1">
<h1>5 QUALITY CONTROL</h1>
<section id="technical-replicate-variability" class="level2">
<h2 class="anchored" data-anchor-id="technical-replicate-variability">5.1 Technical replicate variability</h2>
<div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Coefficient of variation across technical triplicates (%):</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(sample_glycogen<span class="sc">$</span>cv_lum, <span class="dv">2</span>))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Samples with CV &gt; 15%:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>high_cv <span class="ot">&lt;-</span> sample_glycogen <span class="sc">%&gt;%</span> <span class="fu">filter</span>(cv_lum <span class="sc">&gt;</span> <span class="dv">15</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sample_id, mean_lum, sd_lum, cv_lum)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">nrow</span>(high_cv) <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"  none</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">as.data.frame</span>(high_cv), <span class="at">row.names =</span> <span class="cn">FALSE</span>, <span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- high_cv: samples exceeding the 15% triplicate CV threshold ---</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(high_cv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Coefficient of variation across technical triplicates (%):
[1] 0.91 0.90 5.21 2.70 0.79

Samples with CV &gt; 15%:
  none

--- high_cv: samples exceeding the 15% triplicate CV threshold ---

tibble [0 × 4] (S3: tbl_df/tbl/data.frame)
 $ sample_id: chr(0) 
 $ mean_lum : num(0) 
 $ sd_lum   : num(0) 
 $ cv_lum   : num(0) </code></pre>
<p><code>1_04_36C</code> – re-assayed specifically because of a 30.1% CV in the original run – now has a CV of 5.2%, well below threshold: the higher dilution resolved the reproducibility problem it was re-run for. See below for why this improvement in precision did not translate into a usable concentration estimate.</p>
</section>
<section id="out-of-range-floor-effect-check" class="level2">
<h2 class="anchored" data-anchor-id="out-of-range-floor-effect-check">5.2 Out-of-range / floor-effect check</h2>
<div class="sourceCode" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>oor <span class="ot">&lt;-</span> sample_glycogen <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sample_id, family, temperature, mean_lum, well_conc_ug_mL,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>         weight_mg, norm_glycogen, in_std_range) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(well_conc_ug_mL))</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(oor, <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">0</span>),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Sample"</span>, <span class="st">"Family"</span>, <span class="st">"Temp"</span>, <span class="st">"Mean lum."</span>, <span class="st">"Well conc. (ug/mL)"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Tissue (mg)"</span>, <span class="st">"Normalized glycogen"</span>, <span class="st">"In std range"</span>),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Re-assayed samples: back-calculated concentrations at 1:200 dilution"</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- Full re-assay results, all 5 samples ---</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(oor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Family</th>
<th style="text-align: left;">Temp</th>
<th style="text-align: right;">Mean lum.</th>
<th style="text-align: right;">Well conc. (ug/mL)</th>
<th style="text-align: right;">Tissue (mg)</th>
<th style="text-align: right;">Normalized glycogen</th>
<th style="text-align: left;">In std range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1_08_ambient</td>
<td style="text-align: left;">Family 1</td>
<td style="text-align: left;">ambient</td>
<td style="text-align: right;">30767</td>
<td style="text-align: right;">9.883</td>
<td style="text-align: right;">24.8</td>
<td style="text-align: right;">79.70</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="even">
<td style="text-align: left;">1_06_ambient</td>
<td style="text-align: left;">Family 1</td>
<td style="text-align: left;">ambient</td>
<td style="text-align: right;">9218</td>
<td style="text-align: right;">2.548</td>
<td style="text-align: right;">11.0</td>
<td style="text-align: right;">46.33</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1_05_36C</td>
<td style="text-align: left;">Family 1</td>
<td style="text-align: left;">36C</td>
<td style="text-align: right;">8742</td>
<td style="text-align: right;">2.386</td>
<td style="text-align: right;">25.7</td>
<td style="text-align: right;">18.57</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="even">
<td style="text-align: left;">9_05_ambient</td>
<td style="text-align: left;">Family 9</td>
<td style="text-align: left;">ambient</td>
<td style="text-align: right;">6542</td>
<td style="text-align: right;">1.637</td>
<td style="text-align: right;">9.2</td>
<td style="text-align: right;">35.58</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1_04_36C</td>
<td style="text-align: left;">Family 1</td>
<td style="text-align: left;">36C</td>
<td style="text-align: right;">823</td>
<td style="text-align: right;">-0.310</td>
<td style="text-align: right;">12.4</td>
<td style="text-align: right;">-5.00</td>
<td style="text-align: left;">FALSE</td>
</tr>
</tbody>
</table>
<p>Re-assayed samples: back-calculated concentrations at 1:200 dilution</p>
<pre><code>--- Full re-assay results, all 5 samples ---

tibble [5 × 8] (S3: tbl_df/tbl/data.frame)
 $ sample_id      : chr [1:5] "1_08_ambient" "1_06_ambient" "1_05_36C" "9_05_ambient" ...
 $ family         : Factor w/ 2 levels "Family 1","Family 9": 1 1 1 2 1
 $ temperature    : Factor w/ 2 levels "ambient","36C": 1 1 2 1 2
 $ mean_lum       : num [1:5] 30767 9218 8742 6542 823
 $ well_conc_ug_mL: num [1:5] 9.88 2.55 2.39 1.64 -0.31
 $ weight_mg      : num [1:5] 24.8 11 25.7 9.2 12.4
 $ norm_glycogen  : num [1:5] 79.7 46.3 18.6 35.6 -5
 $ in_std_range   : logi [1:5] TRUE TRUE TRUE TRUE FALSE</code></pre>
<p>Four of the five samples (<code>1_08_ambient</code>, <code>1_06_ambient</code>, <code>1_05_36C</code>, <code>9_05_ambient</code>) now fall comfortably within the standard curve’s quantifiable range (0.02-20 µg/mL) at 1:200 – the 8× dilution increase successfully resolved the original extrapolation problem for all four.</p>
<p>The fifth, <code>1_04_36C</code>, was <strong>not</strong> originally out-of-range (it was re-assayed for high CV, not for reading above the curve); at 1:200 its mean luminescence (823 RLU) falls below the fitted intercept, producing a <strong>negative</strong> back-calculated well concentration. It was accidentally diluted at 1:200 for this re-assay, when it should have been re-assayed with its original dilution of 1:25.</p>
</section>
</section>
<section id="comparison-to-original-run" class="level1">
<h1>6 COMPARISON TO ORIGINAL RUN</h1>
<div class="sourceCode" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>original_path <span class="ot">&lt;-</span> <span class="st">"../output/Gen5-20260730-mgig-fams1_9-glycogen-glo/sample_glycogen_results.csv"</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>original <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(original_path)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>original_sub <span class="ot">&lt;-</span> original <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sample <span class="sc">%in%</span> sample_glycogen<span class="sc">$</span>sample_id) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_id             =</span> Sample,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">dilution_orig         =</span> Dilution,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_lum_orig         =</span> Mean.lum.,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">cv_orig               =</span> CV....,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">norm_glycogen_orig    =</span> Normalized.glycogen..ug.mL.mg.,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">in_range_orig         =</span> In.std.range</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>rerun_sub <span class="ot">&lt;-</span> sample_glycogen <span class="sc">%&gt;%</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_id          =</span> sample_id,</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">dilution_rerun     =</span> dilution,</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_lum_rerun     =</span> <span class="fu">round</span>(mean_lum, <span class="dv">0</span>),</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">cv_rerun           =</span> <span class="fu">round</span>(cv_lum, <span class="dv">1</span>),</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">norm_glycogen_rerun =</span> <span class="fu">round</span>(norm_glycogen, <span class="dv">2</span>),</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">in_range_rerun     =</span> <span class="fu">ifelse</span>(in_std_range, <span class="st">"yes"</span>, <span class="st">"NO - extrapolated"</span>)</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>comparison <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(original_sub, rerun_sub, <span class="at">by =</span> <span class="st">"sample_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(sample_id)</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(comparison,</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Sample"</span>, <span class="st">"Dilution (orig)"</span>, <span class="st">"Mean lum. (orig)"</span>, <span class="st">"CV % (orig)"</span>,</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Norm. glycogen (orig)"</span>, <span class="st">"In range (orig)"</span>,</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Dilution (re-run)"</span>, <span class="st">"Mean lum. (re-run)"</span>, <span class="st">"CV % (re-run)"</span>,</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Norm. glycogen (re-run)"</span>, <span class="st">"In range (re-run)"</span>),</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Original run (2026-07-30, 1:25) vs. targeted re-assay (2026-08-03, 1:200)"</span>)</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- comparison: original vs. re-assay results, side by side ---</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(comparison)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: right;">Dilution (orig)</th>
<th style="text-align: right;">Mean lum. (orig)</th>
<th style="text-align: right;">CV % (orig)</th>
<th style="text-align: right;">Norm. glycogen (orig)</th>
<th style="text-align: left;">In range (orig)</th>
<th style="text-align: right;">Dilution (re-run)</th>
<th style="text-align: right;">Mean lum. (re-run)</th>
<th style="text-align: right;">CV % (re-run)</th>
<th style="text-align: right;">Norm. glycogen (re-run)</th>
<th style="text-align: left;">In range (re-run)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1_04_36C</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">5075</td>
<td style="text-align: right;">30.1</td>
<td style="text-align: right;">2.83</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">823</td>
<td style="text-align: right;">5.2</td>
<td style="text-align: right;">-5.00</td>
<td style="text-align: left;">NO - extrapolated</td>
</tr>
<tr class="even">
<td style="text-align: left;">1_05_36C</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">94104</td>
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">29.86</td>
<td style="text-align: left;">NO - extrapolated</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">8742</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">18.57</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1_06_ambient</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">97291</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">72.15</td>
<td style="text-align: left;">NO - extrapolated</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">9218</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">46.33</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">1_08_ambient</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">200961</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">66.38</td>
<td style="text-align: left;">NO - extrapolated</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">30767</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">79.70</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9_05_ambient</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">70209</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">62.05</td>
<td style="text-align: left;">NO - extrapolated</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">6542</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">35.58</td>
<td style="text-align: left;">yes</td>
</tr>
</tbody>
</table>
<p>Original run (2026-07-30, 1:25) vs.&nbsp;targeted re-assay (2026-08-03, 1:200)</p>
<pre><code>--- comparison: original vs. re-assay results, side by side ---

'data.frame':   5 obs. of  11 variables:
 $ sample_id          : chr  "1_04_36C" "1_05_36C" "1_06_ambient" "1_08_ambient" ...
 $ dilution_orig      : int  25 25 25 25 25
 $ mean_lum_orig      : int  5075 94104 97291 200961 70209
 $ cv_orig            : num  30.1 4.9 6 0.2 1.1
 $ norm_glycogen_orig : num  2.83 29.86 72.15 66.38 62.05
 $ in_range_orig      : chr  "yes" "NO - extrapolated" "NO - extrapolated" "NO - extrapolated" ...
 $ dilution_rerun     : num  200 200 200 200 200
 $ mean_lum_rerun     : num  823 8742 9218 30767 6542
 $ cv_rerun           : num  5.2 2.7 0.9 0.9 0.8
 $ norm_glycogen_rerun: num  -5 18.6 46.3 79.7 35.6
 $ in_range_rerun     : chr  "NO - extrapolated" "yes" "yes" "yes" ...</code></pre>
<section id="plot-original-vs.-re-assayed-normalized-glycogen" class="level2">
<h2 class="anchored" data-anchor-id="plot-original-vs.-re-assayed-normalized-glycogen">6.1 Plot: original vs.&nbsp;re-assayed normalized glycogen</h2>
<div class="sourceCode" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>comparison_long <span class="ot">&lt;-</span> comparison <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sample_id, in_range_orig, in_range_rerun,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>         norm_glycogen_orig, norm_glycogen_rerun) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(norm_glycogen_orig, norm_glycogen_rerun),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"run"</span>, <span class="at">values_to =</span> <span class="st">"norm_glycogen"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">run =</span> <span class="fu">recode</span>(run, <span class="at">norm_glycogen_orig =</span> <span class="st">"Original (1:25)"</span>, <span class="at">norm_glycogen_rerun =</span> <span class="st">"Re-assay (1:200)"</span>),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">run =</span> <span class="fu">factor</span>(run, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Original (1:25)"</span>, <span class="st">"Re-assay (1:200)"</span>)),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">in_range =</span> <span class="fu">ifelse</span>(run <span class="sc">==</span> <span class="st">"Original (1:25)"</span>, in_range_orig, in_range_rerun),</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">in_range =</span> <span class="fu">ifelse</span>(in_range <span class="sc">==</span> <span class="st">"yes"</span>, <span class="st">"in range"</span>, <span class="st">"out of range / floor"</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>comparison_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(comparison_long, <span class="fu">aes</span>(<span class="at">x =</span> run, <span class="at">y =</span> norm_glycogen, <span class="at">group =</span> sample_id)) <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"grey60"</span>, <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> sample_id, <span class="at">shape =</span> in_range), <span class="at">size =</span> <span class="fl">3.2</span>) <span class="sc">+</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"in range"</span> <span class="ot">=</span> <span class="dv">16</span>, <span class="st">"out of range / floor"</span> <span class="ot">=</span> <span class="dv">4</span>)) <span class="sc">+</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Normalized glycogen: original run vs. targeted re-assay"</span>,</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Points connected by sample; 'x' marks values flagged out-of-range or below the detection floor"</span>,</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Normalized glycogen (ug/mL/mg tissue)"</span>, <span class="at">color =</span> <span class="st">"Sample"</span>, <span class="at">shape =</span> <span class="st">"Status"</span>) <span class="sc">+</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"right"</span>)</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"--- comparison_plot: ggplot object structure ---</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(comparison_plot)</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(output_dir, <span class="st">"original_vs_rerun_comparison.png"</span>), comparison_plot,</span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">9</span>, <span class="at">height =</span> <span class="fl">5.5</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>comparison_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Gen5-20260803-mgig-fams1_9-glycogen-glo_files/figure-gfm/plot-comparison-1.png" class="img-fluid"><!-- --></p>
<pre><code>--- comparison_plot: ggplot object structure ---

data: sample_id, in_range_orig, in_range_rerun, run, norm_glycogen,
  in_range [10x6]
mapping:  x = ~run, y = ~norm_glycogen, group = ~sample_id
scales:   shape 
faceting:  &lt;empty&gt; 
-----------------------------------
geom_line: na.rm = FALSE, orientation = NA, arrow = NULL, arrow.fill = NULL, lineend = butt, linejoin = round, linemitre = 10
stat_identity: na.rm = FALSE
position_identity 

mapping: colour = ~sample_id, shape = ~in_range 
geom_point: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity </code></pre>
</section>
</section>
<section id="sample-glycogen-table" class="level1">
<h1>7 SAMPLE GLYCOGEN TABLE</h1>
<div class="sourceCode" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>sample_table <span class="ot">&lt;-</span> sample_glycogen <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sample        =</span> sample_id,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Family        =</span> family,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Temperature   =</span> temperature,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Individual    =</span> individual,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Tissue (mg)</span><span class="st">`</span> <span class="ot">=</span> weight_mg,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Dilution</span><span class="st">`</span>    <span class="ot">=</span> dilution,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Mean lum.</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">round</span>(mean_lum, <span class="dv">0</span>),</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">CV (%)</span><span class="st">`</span>      <span class="ot">=</span> <span class="fu">round</span>(cv_lum, <span class="dv">1</span>),</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Well glycogen (ug/mL)</span><span class="st">`</span>        <span class="ot">=</span> <span class="fu">round</span>(well_conc_ug_mL, <span class="dv">3</span>),</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Homogenate glycogen (ug/mL)</span><span class="st">`</span>  <span class="ot">=</span> <span class="fu">round</span>(homogenate_conc_ug_mL, <span class="dv">2</span>),</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Normalized glycogen (ug/mL/mg)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(norm_glycogen, <span class="dv">2</span>),</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">In std range</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(in_std_range, <span class="st">"yes"</span>, <span class="st">"NO - extrapolated"</span>)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(sample_table, <span class="at">caption =</span> <span class="st">"Per-sample glycogen quantification, targeted re-assay (mean of technical triplicate)"</span>)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(sample_table, <span class="fu">file.path</span>(output_dir, <span class="st">"sample_glycogen_results.csv"</span>), <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- sample_table: formatted per-sample results written to CSV ---</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sample_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Family</th>
<th style="text-align: left;">Temperature</th>
<th style="text-align: left;">Individual</th>
<th style="text-align: right;">Tissue (mg)</th>
<th style="text-align: right;">Dilution</th>
<th style="text-align: right;">Mean lum.</th>
<th style="text-align: right;">CV (%)</th>
<th style="text-align: right;">Well glycogen (ug/mL)</th>
<th style="text-align: right;">Homogenate glycogen (ug/mL)</th>
<th style="text-align: right;">Normalized glycogen (ug/mL/mg)</th>
<th style="text-align: left;">In std range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1_06_ambient</td>
<td style="text-align: left;">Family 1</td>
<td style="text-align: left;">ambient</td>
<td style="text-align: left;">06</td>
<td style="text-align: right;">11.0</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">9218</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">2.548</td>
<td style="text-align: right;">509.61</td>
<td style="text-align: right;">46.33</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">1_08_ambient</td>
<td style="text-align: left;">Family 1</td>
<td style="text-align: left;">ambient</td>
<td style="text-align: left;">08</td>
<td style="text-align: right;">24.8</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">30767</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">9.883</td>
<td style="text-align: right;">1976.68</td>
<td style="text-align: right;">79.70</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1_04_36C</td>
<td style="text-align: left;">Family 1</td>
<td style="text-align: left;">36C</td>
<td style="text-align: left;">04</td>
<td style="text-align: right;">12.4</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">823</td>
<td style="text-align: right;">5.2</td>
<td style="text-align: right;">-0.310</td>
<td style="text-align: right;">-61.95</td>
<td style="text-align: right;">-5.00</td>
<td style="text-align: left;">NO - extrapolated</td>
</tr>
<tr class="even">
<td style="text-align: left;">1_05_36C</td>
<td style="text-align: left;">Family 1</td>
<td style="text-align: left;">36C</td>
<td style="text-align: left;">05</td>
<td style="text-align: right;">25.7</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">8742</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">2.386</td>
<td style="text-align: right;">477.18</td>
<td style="text-align: right;">18.57</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9_05_ambient</td>
<td style="text-align: left;">Family 9</td>
<td style="text-align: left;">ambient</td>
<td style="text-align: left;">05</td>
<td style="text-align: right;">9.2</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">6542</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">1.637</td>
<td style="text-align: right;">327.38</td>
<td style="text-align: right;">35.58</td>
<td style="text-align: left;">yes</td>
</tr>
</tbody>
</table>
<p>Per-sample glycogen quantification, targeted re-assay (mean of technical triplicate)</p>
<pre><code>--- sample_table: formatted per-sample results written to CSV ---

tibble [5 × 12] (S3: tbl_df/tbl/data.frame)
 $ Sample                        : chr [1:5] "1_06_ambient" "1_08_ambient" "1_04_36C" "1_05_36C" ...
 $ Family                        : Factor w/ 2 levels "Family 1","Family 9": 1 1 1 1 2
 $ Temperature                   : Factor w/ 2 levels "ambient","36C": 1 1 2 2 1
 $ Individual                    : chr [1:5] "06" "08" "04" "05" ...
 $ Tissue (mg)                   : num [1:5] 11 24.8 12.4 25.7 9.2
 $ Dilution                      : num [1:5] 200 200 200 200 200
 $ Mean lum.                     : num [1:5] 9218 30767 823 8742 6542
 $ CV (%)                        : num [1:5] 0.9 0.9 5.2 2.7 0.8
 $ Well glycogen (ug/mL)         : num [1:5] 2.55 9.88 -0.31 2.39 1.64
 $ Homogenate glycogen (ug/mL)   : num [1:5] 510 1977 -62 477 327
 $ Normalized glycogen (ug/mL/mg): num [1:5] 46.3 79.7 -5 18.6 35.6
 $ In std range                  : chr [1:5] "yes" "yes" "NO - extrapolated" "yes" ...</code></pre>
</section>
<section id="summary" class="level1">
<h1>8 SUMMARY</h1>
<p><strong>What this re-assay was for.</strong> Five samples from the 2026-07-30 run were re-assayed at a higher dilution (1:200 vs.&nbsp;1:25): four that read above the standard curve’s top standard (<code>1_08_ambient</code>, <code>1_06_ambient</code>, <code>1_05_36C</code>, <code>9_05_ambient</code>) and one with a high technical-replicate CV (<code>1_04_36C</code>, 30.1% originally).</p>
<p><strong>Standard curve.</strong> This plate’s standard curve fit well (y = 2937.7 x + 1733.0, R^2 = 0.9886), comparable in quality to the original run’s curve.</p>
<p><strong>Dilution outcome: 4 of 5 successful.</strong> The 8× dilution increase worked as intended for all four samples that were originally out-of-range – all four now fall within the standard curve’s quantifiable range, with comfortable margin below the top standard (well concentrations 1.6-9.9 µg/mL vs.&nbsp;the 0.02-20 µg/mL curve). Their re-assayed normalized glycogen values are lower than the original (extrapolated) estimates in every case, consistent with extrapolation beyond a standard curve’s top point tending to overestimate concentration:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 41%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: right;">Original (1:25, extrapolated)</th>
<th style="text-align: right;">Re-assay (1:200, in range)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>1_08_ambient</code></td>
<td style="text-align: right;">66.4</td>
<td style="text-align: right;">79.7</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>1_06_ambient</code></td>
<td style="text-align: right;">72.2</td>
<td style="text-align: right;">46.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>1_05_36C</code></td>
<td style="text-align: right;">29.9</td>
<td style="text-align: right;">18.6</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>9_05_ambient</code></td>
<td style="text-align: right;">62.1</td>
<td style="text-align: right;">35.6</td>
</tr>
</tbody>
</table>
<p>(Note <code>1_08_ambient</code> is the exception – its re-assayed value is <em>higher</em> than the original extrapolated estimate, underscoring that extrapolation error is not predictably one-directional and is exactly why re-assay within range matters rather than trusting the extrapolated numbers.)</p>
<p>Sample <code>1_04_36C</code> should <em>NOT</em> have been diluted, as it previously failed QC due to a high CV. This should be re-assayed.</p>
<p><strong>Using these results going forward.</strong> For <code>1_08_ambient</code>, <code>1_06_ambient</code>, <code>1_05_36C</code>, and <code>9_05_ambient</code>, the values in this document’s <code>sample_glycogen_results.csv</code> should replace the corresponding rows from the 2026-07-30 run in any downstream analysis (e.g.&nbsp;the family/temperature ANOVA), since they are now interpolated rather than extrapolated and were measured with a same-plate standard curve.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/robertslab\.github\.io\/sams-notebook");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>