---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
date: 2016-12-01 04:24:23+00:00
layout: post
slug: computing-an-excercuse-in-futility
title: Computing - An Excercise in Futility
categories:
  - "2016"
  - "jupyter notebook"
  - "R"
---

Trying to continue my [Oly GBS analsyis from the other day](https://robertslab.github.io/sams-notebook/posts/2016/2016-11-18-data-analysis-initial-o-lurida-fst-determination-from-gbs-data/) and follow along with [Katherine Silliman's notebook](https://github.com/ksil91/2016_Notebook/blob/master/2bRAD%20Subset%20Population%20Structure%20Analysis.ipynb)

However, I hit a major snag: I can't seem to run R in my Jupyter notebook! This is a major pain, since the notebook needs to be able to switch between languages; that's the beauty of using these notebooks.

Below, is a documentation of my torments today.

Currently, I'm creating a new Docker image that uses the Debian Apt repository to install R version 3.1.1. Going through Apt instead of installing from source (as I had been previously done in the Dockerfile) should install all the necessary dependencies for R and get resolve some of the error messages I'm seeing.

Otherwise, the last resort will be to use R outside of the notebook and document that process separately.

Anyway, this is the kind of stuff that is immensely time consuming and frustrating that most people don't realize goes on with all of this computing stuff...

Notebook: [20161129_docker_R_magics_failure.ipynb](https://github.com/sr320/LabDocs/blob/master/jupyter_nbs/sam/20161129_docker_R_magics_failure.ipynb)

<iframe src="https://nbviewer.org/github/sr320/LabDocs/blob/master/jupyter_nbs/sam/20161129_docker_R_magics_failure.ipynb" width="100%" height="2000" scrolling="yes"></iframe>
