---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
date: 2018-02-21 18:39:20+00:00
layout: post
slug: novaseq-assembly-the-struggle-is-real-real-annoying
title: NovaSeq Assembly - The Struggle is Real - Real Annoying!
categories: 
  - "2018"
  - "Geoduck Genome Sequencing"
  - "AllPaths-LG"
  - "assembly"
  - "geoduck"
  - "jr-assembler"
  - "meraculous"
  - "mox"
  - "NovaSeq"
  - "Panopea generosa"
  - "SOAPdenovo2"
---

Well, I continue to struggle to makek progress on assembling the geoduck Illumina NovaSeq data. Granted, there is a _ton_ of data (374GB!!!!), but it's still frustrating that we can't get an assembly anywhere...

Here are some of the struggles so far:

**Meraculous**:





  * Can't run locally because:



    * [Ran out of hard drive space](../2018-02-05-novaseq-assembly-trimmed-geoduck-novaseq-with-meraculous/index.qmd) - due to hardware limitations of our Apple Xserve


    * [Fixed HDD space issue, but Roadrunner locks up and has to be restarted](../2018-02-05-novaseq-assembly-trimmed-geoduck-novaseq-with-meraculous/index.qmd); no error message(s) in log files to help troubleshoot




  * Can't run on Mox because:



    * Can't figure out how to install needed dependencies that don't already exist on Mox. More specifically, friggin' Boost libraries! Trying to install these properly has been an issue in the past for non-Mox computers, too. I remember a few times discussing the pain of installing Boost with Sean Bennett.





**[SOAPdenovo2](https://github.com/aquaskyline/SOAPdenovo2)**





  * Our [Mox node can't handle the memory requirements](../2018-02-19-assembly-geoduck-illumina-novaseq-soapdenovo2-on-mox-fail/index.qmd) needed for assembly.



**[JR-Assembler](https://jr-assembler.iis.sinica.edu.tw/index.htm)**





  * Can't install one of the dependencies ([SOAP error correction](https://sourceforge.net/projects/soapdenovo2/files/ErrorCorrection/))


  * Actually, I need to try the binary version of this, instead of the source version (the source version fails at the `make` step)



So, next up will trying the following two assemblers:



  * [JR-Assembler](https://jr-assembler.iis.sinica.edu.tw/index.htm): Will see if SOAPec binary will work, and then run an assembly.


  * [AllPaths-LG](ftp://ftp.broadinstitute.org/pub/crd/ALLPATHS/Release-LG/AllPaths-LG_Manual.pdf): I was able to install this successfully on Mox.



Additionally, we've ordered some additional hard drives and will be converting the old head/master node on the Apple Xserve cluster to Linux. The old master node is a little better equipped than the other Apple Xserve "birds", so will try to re-run Meraculous on it once we get it converted.
