---
author: Sam White
toc-title: Contents
toc-depth: 5
toc-location: left
title: RNA Quantification - C.gigas PolyIC Mechanical Trials RNA from 20250902
date: '2025-09-10'
draft: false
engine: knitr
categories: 
  - "2025"
  - "Crassostrea gigas"
  - "Pacific oyster"
  - "Qubit"
  - "RNA Quantfication"
  - "Magallana gigas"
  - "Poly IC"
---
# INTRO

I [previously isolated RNA](../2025-09-02-RNA-Isolation---C.gigas-PolyIC-Mechanical-Trials-for-Valentina-Using-Quick-DNA-RNA-Miniprep-Plus-Kit/index.qmd) and needed to quantify it.

# MATERIALS & METHODS

All samples were quantified using the Roberts Lab Qubit 3.0 with the broad range (BR) RNA Assay Kit.

Samples were measured using 1uL of sample. 

::: {.callout-note}
Some samples ended were too low concentration for the broad range assay using 1uL. They were re-measured using 5uL of sample with the broad range assay.
:::


# RESULTS

## Qubit data

Raw Qubit data is here:

- [`20250910-qubit-cgig-polyIC-brRNA.csv`](./20250910-qubit-cgig-polyIC-brRNA.csv) (CSV)

::: {.callout-important}
The following seven samples yielded no RNA and their tubes were discarded:

- `C4PC`
- `C5PC`
- `C1PM`
- `C2PM`
- `C3PM`
- `C4PM`
- `C5PM`

:::

| SampleID | Volume (uL) | Dilution (uL) | Qubit Concentration (ng/u)L | Final Concentration (ng/uL) | Yield (ng) |
|----------|-------------|---------------|-----------------------------|-----------------------------|------------|
| A1C      | 40          | 1             | 610                         | 610                         | 24400      |
| A2C      | 40          | 1             | 244                         | 244                         | 9760       |
| A3C      | 40          | 1             | 580                         | 580                         | 23200      |
| A4C      | 40          | 1             | 458                         | 458                         | 18320      |
| A5C      | 40          | 1             | 534                         | 534                         | 21360      |
| B1C      | 40          | 1             | 260                         | 260                         | 10400      |
| B2C      | 40          | 1             | 512                         | 512                         | 20480      |
| B3C      | 40          | 1             | 394                         | 394                         | 15760      |
| B4C      | 40          | 1             | 532                         | 532                         | 21280      |
| B5C      | 40          | 1             | 574                         | 574                         | 22960      |
| C1C      | 40          | 1             | 752                         | 752                         | 30080      |
| C2C      | 40          | 1             | 304                         | 304                         | 12160      |
| C3C      | 40          | 1             | 624                         | 624                         | 24960      |
| C4C      | 40          | 1             | 544                         | 544                         | 21760      |
| C5C      | 40          | 1             | 542                         | 542                         | 21680      |
| D1C      | 40          | 1             | 204                         | 204                         | 8160       |
| D2C      | 40          | 1             | 318                         | 318                         | 12720      |
| D3C      | 40          | 1             | 512                         | 512                         | 20480      |
| D4C      | 40          | 1             | 374                         | 374                         | 14960      |
| D5C      | 40          | 1             | 570                         | 570                         | 22800      |
| A1M      | 40          | 1             | 340                         | 340                         | 13600      |
| A2M      | 40          | 1             | 316                         | 316                         | 12640      |
| A3M      | 40          | 1             | 388                         | 388                         | 15520      |
| A4M      | 40          | 1             | 444                         | 444                         | 17760      |
| A5M      | 40          | 1             | 642                         | 642                         | 25680      |
| B1M      | 40          | 1             | 336                         | 336                         | 13440      |
| B2M      | 40          | 1             | 294                         | 294                         | 11760      |
| B3M      | 40          | 1             | 608                         | 608                         | 24320      |
| B4M      | 40          | 1             | 171                         | 171                         | 6840       |
| B5M      | 40          | 1             | 436                         | 436                         | 17440      |
| C1M      | 40          | 1             | 252                         | 252                         | 10080      |
| C2M      | 40          | 1             | 154                         | 154                         | 6160       |
| C3M      | 40          | 1             | 408                         | 408                         | 16320      |
| C4M      | 40          | 1             | 630                         | 630                         | 25200      |
| C5M      | 40          | 1             | 131                         | 131                         | 5240       |
| D1M      | 40          | 1             | 184                         | 184                         | 7360       |
| D2M      | 40          | 1             | 103                         | 103                         | 4120       |
| D3M      | 40          | 1             | 111                         | 111                         | 4440       |
| D4M      | 40          | 1             | 410                         | 410                         | 16400      |
| D5M      | 40          | 1             | 264                         | 264                         | 10560      |
| A1T      | 40          | 1             | 358                         | 358                         | 14320      |
| A2T      | 40          | 1             | 484                         | 484                         | 19360      |
| A3T      | 40          | 1             | 206                         | 206                         | 8240       |
| A4T      | 40          | 1             | 248                         | 248                         | 9920       |
| A5T      | 40          | 1             | 139                         | 139                         | 5560       |
| B1T      | 40          | 1             | 292                         | 292                         | 11680      |
| B2T      | 40          | 1             | 276                         | 276                         | 11040      |
| B3T      | 40          | 1             | 356                         | 356                         | 14240      |
| B4T      | 40          | 1             | 392                         | 392                         | 15680      |
| B5T      | 40          | 1             | 500                         | 500                         | 20000      |
| C1T      | 40          | 1             | 488                         | 488                         | 19520      |
| C2T      | 40          | 1             | 662                         | 662                         | 26480      |
| C3T      | 40          | 1             | 594                         | 594                         | 23760      |
| C4T      | 40          | 1             | 340                         | 340                         | 13600      |
| C5T      | 40          | 1             | 598                         | 598                         | 23920      |
| D1T      | 40          | 1             | 350                         | 350                         | 14000      |
| D2T      | 40          | 1             | 922                         | 922                         | 36880      |
| D3T      | 40          | 1             | 328                         | 328                         | 13120      |
| D4T      | 40          | 1             | 274                         | 274                         | 10960      |
| D5T      | 40          | 1             | 248                         | 248                         | 9920       |
| C1PC     | 40          | 1             | 518                         | 518                         | 20720      |
| C2PC     | 40          | 1             | 432                         | 432                         | 17280      |
| C3PC     | 40          | 1             | 362                         | 362                         | 14480      |
| C4PC     | 40          | 1             | Out of range                | 0                           | 0          |
| C5PC     | 40          | 1             | Out of range                | 0                           | 0          |
| D1PC     | 40          | 1             | 248                         | 248                         | 9920       |
| D2PC     | 40          | 1             | 342                         | 342                         | 13680      |
| D3PC     | 40          | 1             | 352                         | 352                         | 14080      |
| D4PC     | 40          | 1             | 300                         | 300                         | 12000      |
| D5PC     | 40          | 1             | 416                         | 416                         | 16640      |
| C1PM     | 40          | 1             | Out of range                | 0                           | 0          |
| C2PM     | 40          | 1             | Out of range                | 0                           | 0          |
| C3PM     | 40          | 1             | Out of range                | 0                           | 0          |
| C4PM     | 40          | 1             | Out of range                | 0                           | 0          |
| C5PM     | 40          | 1             | Out of range                | 0                           | 0          |
| D1PM     | 40          | 1             | 216                         | 216                         | 8640       |
| D2PM     | 40          | 1             | 374                         | 374                         | 14960      |
| D3PM     | 40          | 1             | 622                         | 622                         | 24880      |
| D4PM     | 40          | 1             | 406                         | 406                         | 16240      |
| D4PM     | 40          | 1             | 332                         | 332                         | 13280      |
| A1PT     | 40          | 1             | 740                         | 740                         | 29600      |
| A2PT     | 40          | 1             | 498                         | 498                         | 19920      |
| A3PT     | 40          | 1             | 516                         | 516                         | 20640      |
| A4PT     | 40          | 1             | 392                         | 392                         | 15680      |
| A5PT     | 40          | 1             | 542                         | 542                         | 21680      |
| B1PT     | 40          | 1             | 378                         | 378                         | 15120      |
| B2PT     | 40          | 1             | 712                         | 712                         | 28480      |
| B3PT     | 40          | 1             | 606                         | 606                         | 24240      |
| B4PT     | 40          | 1             | 496                         | 496                         | 19840      |
| B5PT     | 40          | 1             | 342                         | 342                         | 13680      |
| C1PT     | 40          | 1             | 318                         | 318                         | 12720      |
| C2PT     | 40          | 1             | 370                         | 370                         | 14800      |
| C3PT     | 40          | 1             | 552                         | 552                         | 22080      |
| C4PT     | 40          | 1             | 704                         | 704                         | 28160      |
| C5PT     | 40          | 1             | 422                         | 422                         | 16880      |
| D1PT     | 40          | 1             | 664                         | 664                         | 26560      |
| D2PT     | 40          | 1             | 1020                        | 1020                        | 40800      |
| D3PT     | 40          | 1             | 542                         | 542                         | 21680      |
| D4PT     | 40          | 1             | 482                         | 482                         | 19280      |
| D5PT     | 40          | 1             | 476                         | 476                         | 19040      |
| C4PC_5uL | 40          | 1             | Out of range                | 0                           | 0          |
| C5PC_5uL | 40          | 1             | Out of range                | 0                           | 0          |
| C1PM_5uL | 40          | 1             | Out of range                | 0                           | 0          |
| C2PM_5uL | 40          | 1             | Out of range                | 0                           | 0          |
| C3PM_5uL | 40          | 1             | Out of range                | 0                           | 0          |
| C4PM_5uL | 40          | 1             | Out of range                | 0                           | 0          |
| C5PM_5uL | 40          | 1             | Out of range                | 0                           | 0          |


Samples were stored in Valentina's original boxes in the middle -80<sup>o</sup>C.